// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: operator_game.proto

package server

import (
	"context"

	"oa.98ent.com/p9/operator-game/rpc/internal/logic/publishdataservice"
	"oa.98ent.com/p9/operator-game/rpc/internal/svc"
	"oa.98ent.com/p9/operator-game/rpc/pb/operator_game"
)

type PublishDataServiceServer struct {
	svcCtx *svc.ServiceContext
	operator_game.UnimplementedPublishDataServiceServer
}

func NewPublishDataServiceServer(svcCtx *svc.ServiceContext) *PublishDataServiceServer {
	return &PublishDataServiceServer{
		svcCtx: svcCtx,
	}
}

// 同步已发布的游戏数据到分站
func (s *PublishDataServiceServer) SyncPublishedData(ctx context.Context, in *operator_game.SyncPublishedDataRequest) (*operator_game.SyncPublishedDataResp, error) {
	l := publishdataservicelogic.NewSyncPublishedDataLogic(ctx, s.svcCtx)
	return l.SyncPublishedData(in)
}
