// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: operator_game.proto

package server

import (
	"context"

	"oa.98ent.com/p9/operator-game/rpc/internal/logic/gameproviderservice"
	"oa.98ent.com/p9/operator-game/rpc/internal/svc"
	"oa.98ent.com/p9/operator-game/rpc/pb/operator_game"
)

type GameProviderServiceServer struct {
	svcCtx *svc.ServiceContext
	operator_game.UnimplementedGameProviderServiceServer
}

func NewGameProviderServiceServer(svcCtx *svc.ServiceContext) *GameProviderServiceServer {
	return &GameProviderServiceServer{
		svcCtx: svcCtx,
	}
}

// 获取游戏供应商列表
func (s *GameProviderServiceServer) GetGameProviderList(ctx context.Context, in *operator_game.GetGameProviderListRequest) (*operator_game.GetGameProviderListResp, error) {
	l := gameproviderservicelogic.NewGetGameProviderListLogic(ctx, s.svcCtx)
	return l.GetGameProviderList(in)
}

// 获取单个游戏供应商
func (s *GameProviderServiceServer) GetGameProvider(ctx context.Context, in *operator_game.GetGameProviderRequest) (*operator_game.GetGameProviderResp, error) {
	l := gameproviderservicelogic.NewGetGameProviderLogic(ctx, s.svcCtx)
	return l.GetGameProvider(in)
}

// 更新游戏供应商
func (s *GameProviderServiceServer) UpdateGameProvider(ctx context.Context, in *operator_game.UpdateGameProviderRequest) (*operator_game.UpdateGameProviderResp, error) {
	l := gameproviderservicelogic.NewUpdateGameProviderLogic(ctx, s.svcCtx)
	return l.UpdateGameProvider(in)
}
