// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: node_dispatch.proto

package server

import (
	"context"

	"oa.98ent.com/p9/node-dispatch/rpc/internal/logic/operatornodeservice"
	"oa.98ent.com/p9/node-dispatch/rpc/internal/svc"
	"oa.98ent.com/p9/node-dispatch/rpc/pb/nodedispatchrpc"
	"oa.98ent.com/p9/node-dispatch/rpc/pb/nodedispatchrpc/operatornodepb"
)

type OperatorNodeServiceServer struct {
	svcCtx *svc.ServiceContext
	nodedispatchrpc.UnimplementedOperatorNodeServiceServer
}

func NewOperatorNodeServiceServer(svcCtx *svc.ServiceContext) *OperatorNodeServiceServer {
	return &OperatorNodeServiceServer{
		svcCtx: svcCtx,
	}
}

// 保存分站部署节点
func (s *OperatorNodeServiceServer) Save(ctx context.Context, in *operatornodepb.SaveOperatorNodeRequest) (*operatornodepb.SaveOperatorNodeResponse, error) {
	l := operatornodeservicelogic.NewSaveLogic(ctx, s.svcCtx)
	return l.Save(in)
}

// 获取分站部署节点
func (s *OperatorNodeServiceServer) Get(ctx context.Context, in *operatornodepb.GetOperatorNodeRequest) (*operatornodepb.GetOperatorNodeResponse, error) {
	l := operatornodeservicelogic.NewGetLogic(ctx, s.svcCtx)
	return l.Get(in)
}
