// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.32.1
// source: crm.proto

package crmrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	pingpb "oa.98ent.com/p9/operator-crm/service/crm/rpc/pb/crmrpc/pingpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_crm_proto protoreflect.FileDescriptor

const file_crm_proto_rawDesc = "" +
	"\n" +
	"\tcrm.proto\x12\x03crm\x1a\x14types/crm_ping.proto2D\n" +
	"\vPingService\x125\n" +
	"\x04Ping\x12\x15.crm_ping.PingRequest\x1a\x16.crm_ping.PingResponseB8Z6oa.98ent.com/p9/operator-crm/service/crm/rpc/pb/crmrpcb\x06proto3"

var file_crm_proto_goTypes = []any{
	(*pingpb.PingRequest)(nil),  // 0: crm_ping.PingRequest
	(*pingpb.PingResponse)(nil), // 1: crm_ping.PingResponse
}
var file_crm_proto_depIdxs = []int32{
	0, // 0: crm.PingService.Ping:input_type -> crm_ping.PingRequest
	1, // 1: crm.PingService.Ping:output_type -> crm_ping.PingResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_crm_proto_init() }
func file_crm_proto_init() {
	if File_crm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_crm_proto_rawDesc), len(file_crm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_crm_proto_goTypes,
		DependencyIndexes: file_crm_proto_depIdxs,
	}.Build()
	File_crm_proto = out.File
	file_crm_proto_goTypes = nil
	file_crm_proto_depIdxs = nil
}
