FROM alpine:3.22

ARG AUTHOR="p9.work@gmail.com"
LABEL org.opencontainers.image.authors=${AUTHOR}

WORKDIR /app

# 设置容器时区并安装运行依赖
ENV TZ=Asia/Shanghai
RUN apk add --no-cache tzdata ca-certificates

# 复制Settlement RPC程序及配置文件
COPY ./settlement_rpc ./settlement_rpc
COPY ./service/settlement/rpc/etc/settlement.yaml ./etc/settlement.yaml
RUN chmod +x ./settlement_rpc

EXPOSE 39004

ENTRYPOINT ["./settlement_rpc"]
CMD ["-f", "etc/settlement.yaml"]
