FROM alpine:3.22

ARG AUTHOR="p9.work@gmail.com"
LABEL org.opencontainers.image.authors=${AUTHOR}

WORKDIR /app

# 设置容器时区并安装运行依赖
ENV TZ=Asia/Shanghai
RUN apk add --no-cache tzdata ca-certificates

# 复制CRM RPC程序及配置文件
COPY ./crm_rpc ./crm_rpc
COPY ./service/crm/rpc/etc/crm.yaml ./etc/crm.yaml
RUN chmod +x ./crm_rpc

EXPOSE 39002

ENTRYPOINT ["./crm_rpc"]
CMD ["-f", "etc/crm.yaml"]
