Name: operator03-core-api
Host: 0.0.0.0
Port: 38300
Mode: dev

Log:
  Mode: console
  Level: info

# 模式 on分站，off总网
PartnerMode: "on"

CROSConf:
  Address: '*'

CoreRpc:
  Endpoints:
    - operator-node03-core-rpc:39300
  NonBlock: true
  Timeout: 10000

# 链路追踪, 生产建议 Sampler 0.01~0.1
Telemetry:
  Name: operator03-core-api
  Endpoint: 192.168.0.15:4317
  Sampler: 1.0
  Batcher: otlpgrpc
