# API 服务配置
Name: platform-game-api
Host: 0.0.0.0
Port: 18003
Timeout: 10000
Mode: test

I18n:
  DefaultLanguage: zh-CN

CoreRpc:
  Target: 192.168.0.15:19000
  Timeout: 10000

# Swagger 配置
Swagger:
  Protocol: https

PlatformGameRpc:
  Etcd:
    Hosts:
      - 192.168.0.15:2379
    Key: platform-game-rpc

# 链路追踪, 生产建议 Sampler 0.01~0.1
Telemetry:
  Name: platform-game-api
  Endpoint: 192.168.0.15:4317
  Sampler: 1.0
  Batcher: otlpgrpc
