// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"oa.98ent.com/p9/node-dispatch/rpc/ent/dispatchtask"
	"oa.98ent.com/p9/node-dispatch/rpc/ent/predicate"
)

// DispatchTaskUpdate is the builder for updating DispatchTask entities.
type DispatchTaskUpdate struct {
	config
	hooks    []Hook
	mutation *DispatchTaskMutation
}

// Where appends a list predicates to the DispatchTaskUpdate builder.
func (_u *DispatchTaskUpdate) Where(ps ...predicate.DispatchTask) *DispatchTaskUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DispatchTaskUpdate) SetUpdatedAt(v time.Time) *DispatchTaskUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *DispatchTaskUpdate) SetStatus(v int64) *DispatchTaskUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DispatchTaskUpdate) SetNillableStatus(v *int64) *DispatchTaskUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *DispatchTaskUpdate) AddStatus(v int64) *DispatchTaskUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// SetResult sets the "result" field.
func (_u *DispatchTaskUpdate) SetResult(v json.RawMessage) *DispatchTaskUpdate {
	_u.mutation.SetResult(v)
	return _u
}

// AppendResult appends value to the "result" field.
func (_u *DispatchTaskUpdate) AppendResult(v json.RawMessage) *DispatchTaskUpdate {
	_u.mutation.AppendResult(v)
	return _u
}

// ClearResult clears the value of the "result" field.
func (_u *DispatchTaskUpdate) ClearResult() *DispatchTaskUpdate {
	_u.mutation.ClearResult()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *DispatchTaskUpdate) SetErrorMessage(v string) *DispatchTaskUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *DispatchTaskUpdate) SetNillableErrorMessage(v *string) *DispatchTaskUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *DispatchTaskUpdate) ClearErrorMessage() *DispatchTaskUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *DispatchTaskUpdate) SetStartedAt(v time.Time) *DispatchTaskUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *DispatchTaskUpdate) SetNillableStartedAt(v *time.Time) *DispatchTaskUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *DispatchTaskUpdate) ClearStartedAt() *DispatchTaskUpdate {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *DispatchTaskUpdate) SetFinishedAt(v time.Time) *DispatchTaskUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *DispatchTaskUpdate) SetNillableFinishedAt(v *time.Time) *DispatchTaskUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *DispatchTaskUpdate) ClearFinishedAt() *DispatchTaskUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// Mutation returns the DispatchTaskMutation object of the builder.
func (_u *DispatchTaskUpdate) Mutation() *DispatchTaskMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DispatchTaskUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DispatchTaskUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DispatchTaskUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DispatchTaskUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DispatchTaskUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := dispatchtask.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DispatchTaskUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := dispatchtask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DispatchTask.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorMessage(); ok {
		if err := dispatchtask.ErrorMessageValidator(v); err != nil {
			return &ValidationError{Name: "error_message", err: fmt.Errorf(`ent: validator failed for field "DispatchTask.error_message": %w`, err)}
		}
	}
	if _u.mutation.NodeCleared() && len(_u.mutation.NodeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DispatchTask.node"`)
	}
	return nil
}

func (_u *DispatchTaskUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dispatchtask.Table, dispatchtask.Columns, sqlgraph.NewFieldSpec(dispatchtask.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(dispatchtask.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(dispatchtask.FieldStatus, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(dispatchtask.FieldStatus, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Result(); ok {
		_spec.SetField(dispatchtask.FieldResult, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedResult(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, dispatchtask.FieldResult, value)
		})
	}
	if _u.mutation.ResultCleared() {
		_spec.ClearField(dispatchtask.FieldResult, field.TypeJSON)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(dispatchtask.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(dispatchtask.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(dispatchtask.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(dispatchtask.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(dispatchtask.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(dispatchtask.FieldFinishedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dispatchtask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DispatchTaskUpdateOne is the builder for updating a single DispatchTask entity.
type DispatchTaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DispatchTaskMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DispatchTaskUpdateOne) SetUpdatedAt(v time.Time) *DispatchTaskUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *DispatchTaskUpdateOne) SetStatus(v int64) *DispatchTaskUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DispatchTaskUpdateOne) SetNillableStatus(v *int64) *DispatchTaskUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *DispatchTaskUpdateOne) AddStatus(v int64) *DispatchTaskUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// SetResult sets the "result" field.
func (_u *DispatchTaskUpdateOne) SetResult(v json.RawMessage) *DispatchTaskUpdateOne {
	_u.mutation.SetResult(v)
	return _u
}

// AppendResult appends value to the "result" field.
func (_u *DispatchTaskUpdateOne) AppendResult(v json.RawMessage) *DispatchTaskUpdateOne {
	_u.mutation.AppendResult(v)
	return _u
}

// ClearResult clears the value of the "result" field.
func (_u *DispatchTaskUpdateOne) ClearResult() *DispatchTaskUpdateOne {
	_u.mutation.ClearResult()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *DispatchTaskUpdateOne) SetErrorMessage(v string) *DispatchTaskUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *DispatchTaskUpdateOne) SetNillableErrorMessage(v *string) *DispatchTaskUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *DispatchTaskUpdateOne) ClearErrorMessage() *DispatchTaskUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *DispatchTaskUpdateOne) SetStartedAt(v time.Time) *DispatchTaskUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *DispatchTaskUpdateOne) SetNillableStartedAt(v *time.Time) *DispatchTaskUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *DispatchTaskUpdateOne) ClearStartedAt() *DispatchTaskUpdateOne {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *DispatchTaskUpdateOne) SetFinishedAt(v time.Time) *DispatchTaskUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *DispatchTaskUpdateOne) SetNillableFinishedAt(v *time.Time) *DispatchTaskUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *DispatchTaskUpdateOne) ClearFinishedAt() *DispatchTaskUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// Mutation returns the DispatchTaskMutation object of the builder.
func (_u *DispatchTaskUpdateOne) Mutation() *DispatchTaskMutation {
	return _u.mutation
}

// Where appends a list predicates to the DispatchTaskUpdate builder.
func (_u *DispatchTaskUpdateOne) Where(ps ...predicate.DispatchTask) *DispatchTaskUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DispatchTaskUpdateOne) Select(field string, fields ...string) *DispatchTaskUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DispatchTask entity.
func (_u *DispatchTaskUpdateOne) Save(ctx context.Context) (*DispatchTask, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DispatchTaskUpdateOne) SaveX(ctx context.Context) *DispatchTask {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DispatchTaskUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DispatchTaskUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DispatchTaskUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := dispatchtask.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DispatchTaskUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := dispatchtask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DispatchTask.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorMessage(); ok {
		if err := dispatchtask.ErrorMessageValidator(v); err != nil {
			return &ValidationError{Name: "error_message", err: fmt.Errorf(`ent: validator failed for field "DispatchTask.error_message": %w`, err)}
		}
	}
	if _u.mutation.NodeCleared() && len(_u.mutation.NodeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DispatchTask.node"`)
	}
	return nil
}

func (_u *DispatchTaskUpdateOne) sqlSave(ctx context.Context) (_node *DispatchTask, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dispatchtask.Table, dispatchtask.Columns, sqlgraph.NewFieldSpec(dispatchtask.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DispatchTask.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dispatchtask.FieldID)
		for _, f := range fields {
			if !dispatchtask.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dispatchtask.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(dispatchtask.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(dispatchtask.FieldStatus, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(dispatchtask.FieldStatus, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Result(); ok {
		_spec.SetField(dispatchtask.FieldResult, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedResult(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, dispatchtask.FieldResult, value)
		})
	}
	if _u.mutation.ResultCleared() {
		_spec.ClearField(dispatchtask.FieldResult, field.TypeJSON)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(dispatchtask.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(dispatchtask.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(dispatchtask.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(dispatchtask.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(dispatchtask.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(dispatchtask.FieldFinishedAt, field.TypeTime)
	}
	_node = &DispatchTask{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dispatchtask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
