// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: operator_game.proto

package gameservice

import (
	"context"

	"oa.98ent.com/p9/operator-game/rpc/pb/operator_game"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetGameListRequest = operator_game.GetGameListRequest
	GetGameListResp    = operator_game.GetGameListResp
	GetGameRequest     = operator_game.GetGameRequest
	GetGameResp        = operator_game.GetGameResp
	UpdateGameRequest  = operator_game.UpdateGameRequest
	UpdateGameResp     = operator_game.UpdateGameResp

	GameService interface {
		// 获取游戏列表
		GetGameList(ctx context.Context, in *GetGameListRequest, opts ...grpc.CallOption) (*GetGameListResp, error)
		// 获取单个游戏详情
		GetGame(ctx context.Context, in *GetGameRequest, opts ...grpc.CallOption) (*GetGameResp, error)
		// 更新游戏
		UpdateGame(ctx context.Context, in *UpdateGameRequest, opts ...grpc.CallOption) (*UpdateGameResp, error)
	}

	defaultGameService struct {
		cli zrpc.Client
	}
)

func NewGameService(cli zrpc.Client) GameService {
	return &defaultGameService{
		cli: cli,
	}
}

// 获取游戏列表
func (m *defaultGameService) GetGameList(ctx context.Context, in *GetGameListRequest, opts ...grpc.CallOption) (*GetGameListResp, error) {
	client := operator_game.NewGameServiceClient(m.cli.Conn())
	return client.GetGameList(ctx, in, opts...)
}

// 获取单个游戏详情
func (m *defaultGameService) GetGame(ctx context.Context, in *GetGameRequest, opts ...grpc.CallOption) (*GetGameResp, error) {
	client := operator_game.NewGameServiceClient(m.cli.Conn())
	return client.GetGame(ctx, in, opts...)
}

// 更新游戏
func (m *defaultGameService) UpdateGame(ctx context.Context, in *UpdateGameRequest, opts ...grpc.CallOption) (*UpdateGameResp, error) {
	client := operator_game.NewGameServiceClient(m.cli.Conn())
	return client.UpdateGame(ctx, in, opts...)
}
