// Code generated by ent, DO NOT EDIT.

package gamechannel

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"oa.98ent.com/p9/operator-game/rpc/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldLTE(FieldID, id))
}

// ChannelCode applies equality check predicate on the "channel_code" field. It's identical to ChannelCodeEQ.
func ChannelCode(v string) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldEQ(FieldChannelCode, v))
}

// SortNo applies equality check predicate on the "sort_no" field. It's identical to SortNoEQ.
func SortNo(v int64) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldEQ(FieldSortNo, v))
}

// LoadType applies equality check predicate on the "load_type" field. It's identical to LoadTypeEQ.
func LoadType(v int64) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldEQ(FieldLoadType, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v int64) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldEQ(FieldStatus, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldEQ(FieldUpdatedAt, v))
}

// ChannelCodeEQ applies the EQ predicate on the "channel_code" field.
func ChannelCodeEQ(v string) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldEQ(FieldChannelCode, v))
}

// ChannelCodeNEQ applies the NEQ predicate on the "channel_code" field.
func ChannelCodeNEQ(v string) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldNEQ(FieldChannelCode, v))
}

// ChannelCodeIn applies the In predicate on the "channel_code" field.
func ChannelCodeIn(vs ...string) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldIn(FieldChannelCode, vs...))
}

// ChannelCodeNotIn applies the NotIn predicate on the "channel_code" field.
func ChannelCodeNotIn(vs ...string) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldNotIn(FieldChannelCode, vs...))
}

// ChannelCodeGT applies the GT predicate on the "channel_code" field.
func ChannelCodeGT(v string) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldGT(FieldChannelCode, v))
}

// ChannelCodeGTE applies the GTE predicate on the "channel_code" field.
func ChannelCodeGTE(v string) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldGTE(FieldChannelCode, v))
}

// ChannelCodeLT applies the LT predicate on the "channel_code" field.
func ChannelCodeLT(v string) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldLT(FieldChannelCode, v))
}

// ChannelCodeLTE applies the LTE predicate on the "channel_code" field.
func ChannelCodeLTE(v string) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldLTE(FieldChannelCode, v))
}

// ChannelCodeContains applies the Contains predicate on the "channel_code" field.
func ChannelCodeContains(v string) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldContains(FieldChannelCode, v))
}

// ChannelCodeHasPrefix applies the HasPrefix predicate on the "channel_code" field.
func ChannelCodeHasPrefix(v string) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldHasPrefix(FieldChannelCode, v))
}

// ChannelCodeHasSuffix applies the HasSuffix predicate on the "channel_code" field.
func ChannelCodeHasSuffix(v string) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldHasSuffix(FieldChannelCode, v))
}

// ChannelCodeEqualFold applies the EqualFold predicate on the "channel_code" field.
func ChannelCodeEqualFold(v string) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldEqualFold(FieldChannelCode, v))
}

// ChannelCodeContainsFold applies the ContainsFold predicate on the "channel_code" field.
func ChannelCodeContainsFold(v string) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldContainsFold(FieldChannelCode, v))
}

// SortNoEQ applies the EQ predicate on the "sort_no" field.
func SortNoEQ(v int64) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldEQ(FieldSortNo, v))
}

// SortNoNEQ applies the NEQ predicate on the "sort_no" field.
func SortNoNEQ(v int64) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldNEQ(FieldSortNo, v))
}

// SortNoIn applies the In predicate on the "sort_no" field.
func SortNoIn(vs ...int64) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldIn(FieldSortNo, vs...))
}

// SortNoNotIn applies the NotIn predicate on the "sort_no" field.
func SortNoNotIn(vs ...int64) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldNotIn(FieldSortNo, vs...))
}

// SortNoGT applies the GT predicate on the "sort_no" field.
func SortNoGT(v int64) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldGT(FieldSortNo, v))
}

// SortNoGTE applies the GTE predicate on the "sort_no" field.
func SortNoGTE(v int64) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldGTE(FieldSortNo, v))
}

// SortNoLT applies the LT predicate on the "sort_no" field.
func SortNoLT(v int64) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldLT(FieldSortNo, v))
}

// SortNoLTE applies the LTE predicate on the "sort_no" field.
func SortNoLTE(v int64) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldLTE(FieldSortNo, v))
}

// LoadTypeEQ applies the EQ predicate on the "load_type" field.
func LoadTypeEQ(v int64) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldEQ(FieldLoadType, v))
}

// LoadTypeNEQ applies the NEQ predicate on the "load_type" field.
func LoadTypeNEQ(v int64) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldNEQ(FieldLoadType, v))
}

// LoadTypeIn applies the In predicate on the "load_type" field.
func LoadTypeIn(vs ...int64) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldIn(FieldLoadType, vs...))
}

// LoadTypeNotIn applies the NotIn predicate on the "load_type" field.
func LoadTypeNotIn(vs ...int64) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldNotIn(FieldLoadType, vs...))
}

// LoadTypeGT applies the GT predicate on the "load_type" field.
func LoadTypeGT(v int64) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldGT(FieldLoadType, v))
}

// LoadTypeGTE applies the GTE predicate on the "load_type" field.
func LoadTypeGTE(v int64) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldGTE(FieldLoadType, v))
}

// LoadTypeLT applies the LT predicate on the "load_type" field.
func LoadTypeLT(v int64) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldLT(FieldLoadType, v))
}

// LoadTypeLTE applies the LTE predicate on the "load_type" field.
func LoadTypeLTE(v int64) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldLTE(FieldLoadType, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v int64) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v int64) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...int64) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...int64) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v int64) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v int64) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v int64) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v int64) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldLTE(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.GameChannel {
	return predicate.GameChannel(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GameChannel) predicate.GameChannel {
	return predicate.GameChannel(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GameChannel) predicate.GameChannel {
	return predicate.GameChannel(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GameChannel) predicate.GameChannel {
	return predicate.GameChannel(sql.NotPredicates(p))
}
