// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.32.0
// source: platform_operator.proto

package platformoperatorrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	adminpb "oa.98ent.com/p9/platform-operator/rpc/pb/platformoperatorrpc/adminpb"
	agentlineallocationpb "oa.98ent.com/p9/platform-operator/rpc/pb/platformoperatorrpc/agentlineallocationpb"
	basicresourceallocationpb "oa.98ent.com/p9/platform-operator/rpc/pb/platformoperatorrpc/basicresourceallocationpb"
	domainpb "oa.98ent.com/p9/platform-operator/rpc/pb/platformoperatorrpc/domainpb"
	languageallocationpb "oa.98ent.com/p9/platform-operator/rpc/pb/platformoperatorrpc/languageallocationpb"
	operatornodepb "oa.98ent.com/p9/platform-operator/rpc/pb/platformoperatorrpc/operatornodepb"
	operatorpb "oa.98ent.com/p9/platform-operator/rpc/pb/platformoperatorrpc/operatorpb"
	pingpb "oa.98ent.com/p9/platform-operator/rpc/pb/platformoperatorrpc/pingpb"
	profilepb "oa.98ent.com/p9/platform-operator/rpc/pb/platformoperatorrpc/profilepb"
	regionallocationpb "oa.98ent.com/p9/platform-operator/rpc/pb/platformoperatorrpc/regionallocationpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_platform_operator_proto protoreflect.FileDescriptor

const file_platform_operator_proto_rawDesc = "" +
	"\n" +
	"\x17platform_operator.proto\x12\x11platform_operator\x1a\"types/platform_operator_ping.proto\x1a&types/platform_operator_operator.proto\x1a+types/platform_operator_operator_node.proto\x1a%types/platform_operator_profile.proto\x1a$types/platform_operator_domain.proto\x1a#types/platform_operator_admin.proto\x1a7types/platform_operator_basic_resource_allocation.proto\x1a1types/platform_operator_language_allocation.proto\x1a/types/platform_operator_region_allocation.proto\x1a3types/platform_operator_agent_line_allocation.proto2`\n" +
	"\vPingService\x12Q\n" +
	"\x04Ping\x12#.platform_operator_ping.PingRequest\x1a$.platform_operator_ping.PingResponse2\xbf\t\n" +
	"\x0fOperatorService\x12o\n" +
	"\x06Create\x121.platform_operator_operator.CreateOperatorRequest\x1a2.platform_operator_operator.CreateOperatorResponse\x12o\n" +
	"\x06Update\x121.platform_operator_operator.UpdateOperatorRequest\x1a2.platform_operator_operator.UpdateOperatorResponse\x12f\n" +
	"\x03Get\x12..platform_operator_operator.GetOperatorRequest\x1a/.platform_operator_operator.GetOperatorResponse\x12\x8c\x01\n" +
	"\x15GetInitializationData\x128.platform_operator_operator.GetInitializationDataRequest\x1a9.platform_operator_operator.GetInitializationDataResponse\x12k\n" +
	"\x04List\x120.platform_operator_operator.ListOperatorsRequest\x1a1.platform_operator_operator.ListOperatorsResponse\x12u\n" +
	"\bComplete\x123.platform_operator_operator.CompleteOperatorRequest\x1a4.platform_operator_operator.CompleteOperatorResponse\x12r\n" +
	"\aPublish\x122.platform_operator_operator.PublishOperatorRequest\x1a3.platform_operator_operator.PublishOperatorResponse\x12\x80\x01\n" +
	"\x11SyncPublishStatus\x124.platform_operator_operator.SyncPublishStatusRequest\x1a5.platform_operator_operator.SyncPublishStatusResponse\x12\x86\x01\n" +
	"\x13HandlePublishResult\x126.platform_operator_operator.HandlePublishResultRequest\x1a7.platform_operator_operator.HandlePublishResultResponse\x12o\n" +
	"\x06Delete\x121.platform_operator_operator.DeleteOperatorRequest\x1a2.platform_operator_operator.DeleteOperatorResponse2\x8c\x02\n" +
	"\x13OperatorNodeService\x12{\n" +
	"\x04Save\x128.platform_operator_operator_node.SaveOperatorNodeRequest\x1a9.platform_operator_operator_node.SaveOperatorNodeResponse\x12x\n" +
	"\x03Get\x127.platform_operator_operator_node.GetOperatorNodeRequest\x1a8.platform_operator_operator_node.GetOperatorNodeResponse2\x86\x03\n" +
	"\x16OperatorProfileService\x12{\n" +
	"\x06Create\x127.platform_operator_profile.CreateOperatorProfileRequest\x1a8.platform_operator_profile.CreateOperatorProfileResponse\x12{\n" +
	"\x06Update\x127.platform_operator_profile.UpdateOperatorProfileRequest\x1a8.platform_operator_profile.UpdateOperatorProfileResponse\x12r\n" +
	"\x03Get\x124.platform_operator_profile.GetOperatorProfileRequest\x1a5.platform_operator_profile.GetOperatorProfileResponse2\x97\x04\n" +
	"\x15OperatorDomainService\x12g\n" +
	"\x06Create\x12-.platform_operator_domain.CreateDomainRequest\x1a..platform_operator_domain.CreateDomainResponse\x12g\n" +
	"\x06Update\x12-.platform_operator_domain.UpdateDomainRequest\x1a..platform_operator_domain.UpdateDomainResponse\x12^\n" +
	"\x03Get\x12*.platform_operator_domain.GetDomainRequest\x1a+.platform_operator_domain.GetDomainResponse\x12c\n" +
	"\x04List\x12,.platform_operator_domain.ListDomainsRequest\x1a-.platform_operator_domain.ListDomainsResponse\x12g\n" +
	"\x06Delete\x12-.platform_operator_domain.DeleteDomainRequest\x1a..platform_operator_domain.DeleteDomainResponse2\xa4\a\n" +
	"\x14OperatorAdminService\x12c\n" +
	"\x06Create\x12+.platform_operator_admin.CreateAdminRequest\x1a,.platform_operator_admin.CreateAdminResponse\x12_\n" +
	"\x04List\x12*.platform_operator_admin.ListAdminsRequest\x1a+.platform_operator_admin.ListAdminsResponse\x12x\n" +
	"\rResetPassword\x122.platform_operator_admin.ResetAdminPasswordRequest\x1a3.platform_operator_admin.ResetAdminPasswordResponse\x12c\n" +
	"\x06Update\x12+.platform_operator_admin.UpdateAdminRequest\x1a,.platform_operator_admin.UpdateAdminResponse\x12u\n" +
	"\fUpdateStatus\x121.platform_operator_admin.UpdateAdminStatusRequest\x1a2.platform_operator_admin.UpdateAdminStatusResponse\x12\x89\x01\n" +
	"\x12DeleteByOperatorId\x128.platform_operator_admin.DeleteAdminsByOperatorIdRequest\x1a9.platform_operator_admin.DeleteAdminsByOperatorIdResponse\x12\x87\x01\n" +
	"\x12ExistsByOperatorId\x127.platform_operator_admin.ExistsAdminByOperatorIdRequest\x1a8.platform_operator_admin.ExistsAdminByOperatorIdResponse\x12Z\n" +
	"\x03Get\x12(.platform_operator_admin.GetAdminRequest\x1a).platform_operator_admin.GetAdminResponse2\xce\x01\n" +
	"\x1eBasicResourceAllocationService\x12\xab\x01\n" +
	"\x04List\x12P.platform_operator_basic_resource_allocation.ListBasicResourceAllocationsRequest\x1aQ.platform_operator_basic_resource_allocation.ListBasicResourceAllocationsResponse2\xcb\x02\n" +
	"\x19LanguageAllocationService\x12\x95\x01\n" +
	"\x04List\x12E.platform_operator_language_allocation.ListLanguageAllocationsRequest\x1aF.platform_operator_language_allocation.ListLanguageAllocationsResponse\x12\x95\x01\n" +
	"\x04Save\x12E.platform_operator_language_allocation.SaveLanguageAllocationsRequest\x1aF.platform_operator_language_allocation.SaveLanguageAllocationsResponse2\xb9\x02\n" +
	"\x17RegionAllocationService\x12\x8d\x01\n" +
	"\x04List\x12A.platform_operator_region_allocation.ListRegionAllocationsRequest\x1aB.platform_operator_region_allocation.ListRegionAllocationsResponse\x12\x8d\x01\n" +
	"\x04Save\x12A.platform_operator_region_allocation.SaveRegionAllocationsRequest\x1aB.platform_operator_region_allocation.SaveRegionAllocationsResponse2\xd8\x02\n" +
	"\x1aAgentLineAllocationService\x12\x9b\x01\n" +
	"\x04List\x12H.platform_operator_agent_line_allocation.ListAgentLineAllocationsRequest\x1aI.platform_operator_agent_line_allocation.ListAgentLineAllocationsResponse\x12\x9b\x01\n" +
	"\x04Save\x12H.platform_operator_agent_line_allocation.SaveAgentLineAllocationsRequest\x1aI.platform_operator_agent_line_allocation.SaveAgentLineAllocationsResponseB>Z<oa.98ent.com/p9/platform-operator/rpc/pb/platformoperatorrpcb\x06proto3"

var file_platform_operator_proto_goTypes = []any{
	(*pingpb.PingRequest)(nil),                                             // 0: platform_operator_ping.PingRequest
	(*operatorpb.CreateOperatorRequest)(nil),                               // 1: platform_operator_operator.CreateOperatorRequest
	(*operatorpb.UpdateOperatorRequest)(nil),                               // 2: platform_operator_operator.UpdateOperatorRequest
	(*operatorpb.GetOperatorRequest)(nil),                                  // 3: platform_operator_operator.GetOperatorRequest
	(*operatorpb.GetInitializationDataRequest)(nil),                        // 4: platform_operator_operator.GetInitializationDataRequest
	(*operatorpb.ListOperatorsRequest)(nil),                                // 5: platform_operator_operator.ListOperatorsRequest
	(*operatorpb.CompleteOperatorRequest)(nil),                             // 6: platform_operator_operator.CompleteOperatorRequest
	(*operatorpb.PublishOperatorRequest)(nil),                              // 7: platform_operator_operator.PublishOperatorRequest
	(*operatorpb.SyncPublishStatusRequest)(nil),                            // 8: platform_operator_operator.SyncPublishStatusRequest
	(*operatorpb.HandlePublishResultRequest)(nil),                          // 9: platform_operator_operator.HandlePublishResultRequest
	(*operatorpb.DeleteOperatorRequest)(nil),                               // 10: platform_operator_operator.DeleteOperatorRequest
	(*operatornodepb.SaveOperatorNodeRequest)(nil),                         // 11: platform_operator_operator_node.SaveOperatorNodeRequest
	(*operatornodepb.GetOperatorNodeRequest)(nil),                          // 12: platform_operator_operator_node.GetOperatorNodeRequest
	(*profilepb.CreateOperatorProfileRequest)(nil),                         // 13: platform_operator_profile.CreateOperatorProfileRequest
	(*profilepb.UpdateOperatorProfileRequest)(nil),                         // 14: platform_operator_profile.UpdateOperatorProfileRequest
	(*profilepb.GetOperatorProfileRequest)(nil),                            // 15: platform_operator_profile.GetOperatorProfileRequest
	(*domainpb.CreateDomainRequest)(nil),                                   // 16: platform_operator_domain.CreateDomainRequest
	(*domainpb.UpdateDomainRequest)(nil),                                   // 17: platform_operator_domain.UpdateDomainRequest
	(*domainpb.GetDomainRequest)(nil),                                      // 18: platform_operator_domain.GetDomainRequest
	(*domainpb.ListDomainsRequest)(nil),                                    // 19: platform_operator_domain.ListDomainsRequest
	(*domainpb.DeleteDomainRequest)(nil),                                   // 20: platform_operator_domain.DeleteDomainRequest
	(*adminpb.CreateAdminRequest)(nil),                                     // 21: platform_operator_admin.CreateAdminRequest
	(*adminpb.ListAdminsRequest)(nil),                                      // 22: platform_operator_admin.ListAdminsRequest
	(*adminpb.ResetAdminPasswordRequest)(nil),                              // 23: platform_operator_admin.ResetAdminPasswordRequest
	(*adminpb.UpdateAdminRequest)(nil),                                     // 24: platform_operator_admin.UpdateAdminRequest
	(*adminpb.UpdateAdminStatusRequest)(nil),                               // 25: platform_operator_admin.UpdateAdminStatusRequest
	(*adminpb.DeleteAdminsByOperatorIdRequest)(nil),                        // 26: platform_operator_admin.DeleteAdminsByOperatorIdRequest
	(*adminpb.ExistsAdminByOperatorIdRequest)(nil),                         // 27: platform_operator_admin.ExistsAdminByOperatorIdRequest
	(*adminpb.GetAdminRequest)(nil),                                        // 28: platform_operator_admin.GetAdminRequest
	(*basicresourceallocationpb.ListBasicResourceAllocationsRequest)(nil),  // 29: platform_operator_basic_resource_allocation.ListBasicResourceAllocationsRequest
	(*languageallocationpb.ListLanguageAllocationsRequest)(nil),            // 30: platform_operator_language_allocation.ListLanguageAllocationsRequest
	(*languageallocationpb.SaveLanguageAllocationsRequest)(nil),            // 31: platform_operator_language_allocation.SaveLanguageAllocationsRequest
	(*regionallocationpb.ListRegionAllocationsRequest)(nil),                // 32: platform_operator_region_allocation.ListRegionAllocationsRequest
	(*regionallocationpb.SaveRegionAllocationsRequest)(nil),                // 33: platform_operator_region_allocation.SaveRegionAllocationsRequest
	(*agentlineallocationpb.ListAgentLineAllocationsRequest)(nil),          // 34: platform_operator_agent_line_allocation.ListAgentLineAllocationsRequest
	(*agentlineallocationpb.SaveAgentLineAllocationsRequest)(nil),          // 35: platform_operator_agent_line_allocation.SaveAgentLineAllocationsRequest
	(*pingpb.PingResponse)(nil),                                            // 36: platform_operator_ping.PingResponse
	(*operatorpb.CreateOperatorResponse)(nil),                              // 37: platform_operator_operator.CreateOperatorResponse
	(*operatorpb.UpdateOperatorResponse)(nil),                              // 38: platform_operator_operator.UpdateOperatorResponse
	(*operatorpb.GetOperatorResponse)(nil),                                 // 39: platform_operator_operator.GetOperatorResponse
	(*operatorpb.GetInitializationDataResponse)(nil),                       // 40: platform_operator_operator.GetInitializationDataResponse
	(*operatorpb.ListOperatorsResponse)(nil),                               // 41: platform_operator_operator.ListOperatorsResponse
	(*operatorpb.CompleteOperatorResponse)(nil),                            // 42: platform_operator_operator.CompleteOperatorResponse
	(*operatorpb.PublishOperatorResponse)(nil),                             // 43: platform_operator_operator.PublishOperatorResponse
	(*operatorpb.SyncPublishStatusResponse)(nil),                           // 44: platform_operator_operator.SyncPublishStatusResponse
	(*operatorpb.HandlePublishResultResponse)(nil),                         // 45: platform_operator_operator.HandlePublishResultResponse
	(*operatorpb.DeleteOperatorResponse)(nil),                              // 46: platform_operator_operator.DeleteOperatorResponse
	(*operatornodepb.SaveOperatorNodeResponse)(nil),                        // 47: platform_operator_operator_node.SaveOperatorNodeResponse
	(*operatornodepb.GetOperatorNodeResponse)(nil),                         // 48: platform_operator_operator_node.GetOperatorNodeResponse
	(*profilepb.CreateOperatorProfileResponse)(nil),                        // 49: platform_operator_profile.CreateOperatorProfileResponse
	(*profilepb.UpdateOperatorProfileResponse)(nil),                        // 50: platform_operator_profile.UpdateOperatorProfileResponse
	(*profilepb.GetOperatorProfileResponse)(nil),                           // 51: platform_operator_profile.GetOperatorProfileResponse
	(*domainpb.CreateDomainResponse)(nil),                                  // 52: platform_operator_domain.CreateDomainResponse
	(*domainpb.UpdateDomainResponse)(nil),                                  // 53: platform_operator_domain.UpdateDomainResponse
	(*domainpb.GetDomainResponse)(nil),                                     // 54: platform_operator_domain.GetDomainResponse
	(*domainpb.ListDomainsResponse)(nil),                                   // 55: platform_operator_domain.ListDomainsResponse
	(*domainpb.DeleteDomainResponse)(nil),                                  // 56: platform_operator_domain.DeleteDomainResponse
	(*adminpb.CreateAdminResponse)(nil),                                    // 57: platform_operator_admin.CreateAdminResponse
	(*adminpb.ListAdminsResponse)(nil),                                     // 58: platform_operator_admin.ListAdminsResponse
	(*adminpb.ResetAdminPasswordResponse)(nil),                             // 59: platform_operator_admin.ResetAdminPasswordResponse
	(*adminpb.UpdateAdminResponse)(nil),                                    // 60: platform_operator_admin.UpdateAdminResponse
	(*adminpb.UpdateAdminStatusResponse)(nil),                              // 61: platform_operator_admin.UpdateAdminStatusResponse
	(*adminpb.DeleteAdminsByOperatorIdResponse)(nil),                       // 62: platform_operator_admin.DeleteAdminsByOperatorIdResponse
	(*adminpb.ExistsAdminByOperatorIdResponse)(nil),                        // 63: platform_operator_admin.ExistsAdminByOperatorIdResponse
	(*adminpb.GetAdminResponse)(nil),                                       // 64: platform_operator_admin.GetAdminResponse
	(*basicresourceallocationpb.ListBasicResourceAllocationsResponse)(nil), // 65: platform_operator_basic_resource_allocation.ListBasicResourceAllocationsResponse
	(*languageallocationpb.ListLanguageAllocationsResponse)(nil),           // 66: platform_operator_language_allocation.ListLanguageAllocationsResponse
	(*languageallocationpb.SaveLanguageAllocationsResponse)(nil),           // 67: platform_operator_language_allocation.SaveLanguageAllocationsResponse
	(*regionallocationpb.ListRegionAllocationsResponse)(nil),               // 68: platform_operator_region_allocation.ListRegionAllocationsResponse
	(*regionallocationpb.SaveRegionAllocationsResponse)(nil),               // 69: platform_operator_region_allocation.SaveRegionAllocationsResponse
	(*agentlineallocationpb.ListAgentLineAllocationsResponse)(nil),         // 70: platform_operator_agent_line_allocation.ListAgentLineAllocationsResponse
	(*agentlineallocationpb.SaveAgentLineAllocationsResponse)(nil),         // 71: platform_operator_agent_line_allocation.SaveAgentLineAllocationsResponse
}
var file_platform_operator_proto_depIdxs = []int32{
	0,  // 0: platform_operator.PingService.Ping:input_type -> platform_operator_ping.PingRequest
	1,  // 1: platform_operator.OperatorService.Create:input_type -> platform_operator_operator.CreateOperatorRequest
	2,  // 2: platform_operator.OperatorService.Update:input_type -> platform_operator_operator.UpdateOperatorRequest
	3,  // 3: platform_operator.OperatorService.Get:input_type -> platform_operator_operator.GetOperatorRequest
	4,  // 4: platform_operator.OperatorService.GetInitializationData:input_type -> platform_operator_operator.GetInitializationDataRequest
	5,  // 5: platform_operator.OperatorService.List:input_type -> platform_operator_operator.ListOperatorsRequest
	6,  // 6: platform_operator.OperatorService.Complete:input_type -> platform_operator_operator.CompleteOperatorRequest
	7,  // 7: platform_operator.OperatorService.Publish:input_type -> platform_operator_operator.PublishOperatorRequest
	8,  // 8: platform_operator.OperatorService.SyncPublishStatus:input_type -> platform_operator_operator.SyncPublishStatusRequest
	9,  // 9: platform_operator.OperatorService.HandlePublishResult:input_type -> platform_operator_operator.HandlePublishResultRequest
	10, // 10: platform_operator.OperatorService.Delete:input_type -> platform_operator_operator.DeleteOperatorRequest
	11, // 11: platform_operator.OperatorNodeService.Save:input_type -> platform_operator_operator_node.SaveOperatorNodeRequest
	12, // 12: platform_operator.OperatorNodeService.Get:input_type -> platform_operator_operator_node.GetOperatorNodeRequest
	13, // 13: platform_operator.OperatorProfileService.Create:input_type -> platform_operator_profile.CreateOperatorProfileRequest
	14, // 14: platform_operator.OperatorProfileService.Update:input_type -> platform_operator_profile.UpdateOperatorProfileRequest
	15, // 15: platform_operator.OperatorProfileService.Get:input_type -> platform_operator_profile.GetOperatorProfileRequest
	16, // 16: platform_operator.OperatorDomainService.Create:input_type -> platform_operator_domain.CreateDomainRequest
	17, // 17: platform_operator.OperatorDomainService.Update:input_type -> platform_operator_domain.UpdateDomainRequest
	18, // 18: platform_operator.OperatorDomainService.Get:input_type -> platform_operator_domain.GetDomainRequest
	19, // 19: platform_operator.OperatorDomainService.List:input_type -> platform_operator_domain.ListDomainsRequest
	20, // 20: platform_operator.OperatorDomainService.Delete:input_type -> platform_operator_domain.DeleteDomainRequest
	21, // 21: platform_operator.OperatorAdminService.Create:input_type -> platform_operator_admin.CreateAdminRequest
	22, // 22: platform_operator.OperatorAdminService.List:input_type -> platform_operator_admin.ListAdminsRequest
	23, // 23: platform_operator.OperatorAdminService.ResetPassword:input_type -> platform_operator_admin.ResetAdminPasswordRequest
	24, // 24: platform_operator.OperatorAdminService.Update:input_type -> platform_operator_admin.UpdateAdminRequest
	25, // 25: platform_operator.OperatorAdminService.UpdateStatus:input_type -> platform_operator_admin.UpdateAdminStatusRequest
	26, // 26: platform_operator.OperatorAdminService.DeleteByOperatorId:input_type -> platform_operator_admin.DeleteAdminsByOperatorIdRequest
	27, // 27: platform_operator.OperatorAdminService.ExistsByOperatorId:input_type -> platform_operator_admin.ExistsAdminByOperatorIdRequest
	28, // 28: platform_operator.OperatorAdminService.Get:input_type -> platform_operator_admin.GetAdminRequest
	29, // 29: platform_operator.BasicResourceAllocationService.List:input_type -> platform_operator_basic_resource_allocation.ListBasicResourceAllocationsRequest
	30, // 30: platform_operator.LanguageAllocationService.List:input_type -> platform_operator_language_allocation.ListLanguageAllocationsRequest
	31, // 31: platform_operator.LanguageAllocationService.Save:input_type -> platform_operator_language_allocation.SaveLanguageAllocationsRequest
	32, // 32: platform_operator.RegionAllocationService.List:input_type -> platform_operator_region_allocation.ListRegionAllocationsRequest
	33, // 33: platform_operator.RegionAllocationService.Save:input_type -> platform_operator_region_allocation.SaveRegionAllocationsRequest
	34, // 34: platform_operator.AgentLineAllocationService.List:input_type -> platform_operator_agent_line_allocation.ListAgentLineAllocationsRequest
	35, // 35: platform_operator.AgentLineAllocationService.Save:input_type -> platform_operator_agent_line_allocation.SaveAgentLineAllocationsRequest
	36, // 36: platform_operator.PingService.Ping:output_type -> platform_operator_ping.PingResponse
	37, // 37: platform_operator.OperatorService.Create:output_type -> platform_operator_operator.CreateOperatorResponse
	38, // 38: platform_operator.OperatorService.Update:output_type -> platform_operator_operator.UpdateOperatorResponse
	39, // 39: platform_operator.OperatorService.Get:output_type -> platform_operator_operator.GetOperatorResponse
	40, // 40: platform_operator.OperatorService.GetInitializationData:output_type -> platform_operator_operator.GetInitializationDataResponse
	41, // 41: platform_operator.OperatorService.List:output_type -> platform_operator_operator.ListOperatorsResponse
	42, // 42: platform_operator.OperatorService.Complete:output_type -> platform_operator_operator.CompleteOperatorResponse
	43, // 43: platform_operator.OperatorService.Publish:output_type -> platform_operator_operator.PublishOperatorResponse
	44, // 44: platform_operator.OperatorService.SyncPublishStatus:output_type -> platform_operator_operator.SyncPublishStatusResponse
	45, // 45: platform_operator.OperatorService.HandlePublishResult:output_type -> platform_operator_operator.HandlePublishResultResponse
	46, // 46: platform_operator.OperatorService.Delete:output_type -> platform_operator_operator.DeleteOperatorResponse
	47, // 47: platform_operator.OperatorNodeService.Save:output_type -> platform_operator_operator_node.SaveOperatorNodeResponse
	48, // 48: platform_operator.OperatorNodeService.Get:output_type -> platform_operator_operator_node.GetOperatorNodeResponse
	49, // 49: platform_operator.OperatorProfileService.Create:output_type -> platform_operator_profile.CreateOperatorProfileResponse
	50, // 50: platform_operator.OperatorProfileService.Update:output_type -> platform_operator_profile.UpdateOperatorProfileResponse
	51, // 51: platform_operator.OperatorProfileService.Get:output_type -> platform_operator_profile.GetOperatorProfileResponse
	52, // 52: platform_operator.OperatorDomainService.Create:output_type -> platform_operator_domain.CreateDomainResponse
	53, // 53: platform_operator.OperatorDomainService.Update:output_type -> platform_operator_domain.UpdateDomainResponse
	54, // 54: platform_operator.OperatorDomainService.Get:output_type -> platform_operator_domain.GetDomainResponse
	55, // 55: platform_operator.OperatorDomainService.List:output_type -> platform_operator_domain.ListDomainsResponse
	56, // 56: platform_operator.OperatorDomainService.Delete:output_type -> platform_operator_domain.DeleteDomainResponse
	57, // 57: platform_operator.OperatorAdminService.Create:output_type -> platform_operator_admin.CreateAdminResponse
	58, // 58: platform_operator.OperatorAdminService.List:output_type -> platform_operator_admin.ListAdminsResponse
	59, // 59: platform_operator.OperatorAdminService.ResetPassword:output_type -> platform_operator_admin.ResetAdminPasswordResponse
	60, // 60: platform_operator.OperatorAdminService.Update:output_type -> platform_operator_admin.UpdateAdminResponse
	61, // 61: platform_operator.OperatorAdminService.UpdateStatus:output_type -> platform_operator_admin.UpdateAdminStatusResponse
	62, // 62: platform_operator.OperatorAdminService.DeleteByOperatorId:output_type -> platform_operator_admin.DeleteAdminsByOperatorIdResponse
	63, // 63: platform_operator.OperatorAdminService.ExistsByOperatorId:output_type -> platform_operator_admin.ExistsAdminByOperatorIdResponse
	64, // 64: platform_operator.OperatorAdminService.Get:output_type -> platform_operator_admin.GetAdminResponse
	65, // 65: platform_operator.BasicResourceAllocationService.List:output_type -> platform_operator_basic_resource_allocation.ListBasicResourceAllocationsResponse
	66, // 66: platform_operator.LanguageAllocationService.List:output_type -> platform_operator_language_allocation.ListLanguageAllocationsResponse
	67, // 67: platform_operator.LanguageAllocationService.Save:output_type -> platform_operator_language_allocation.SaveLanguageAllocationsResponse
	68, // 68: platform_operator.RegionAllocationService.List:output_type -> platform_operator_region_allocation.ListRegionAllocationsResponse
	69, // 69: platform_operator.RegionAllocationService.Save:output_type -> platform_operator_region_allocation.SaveRegionAllocationsResponse
	70, // 70: platform_operator.AgentLineAllocationService.List:output_type -> platform_operator_agent_line_allocation.ListAgentLineAllocationsResponse
	71, // 71: platform_operator.AgentLineAllocationService.Save:output_type -> platform_operator_agent_line_allocation.SaveAgentLineAllocationsResponse
	36, // [36:72] is the sub-list for method output_type
	0,  // [0:36] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_platform_operator_proto_init() }
func file_platform_operator_proto_init() {
	if File_platform_operator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_platform_operator_proto_rawDesc), len(file_platform_operator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   10,
		},
		GoTypes:           file_platform_operator_proto_goTypes,
		DependencyIndexes: file_platform_operator_proto_depIdxs,
	}.Build()
	File_platform_operator_proto = out.File
	file_platform_operator_proto_goTypes = nil
	file_platform_operator_proto_depIdxs = nil
}
