// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: platform_operator.proto

package operatornodeservice

import (
	"context"

	"oa.98ent.com/p9/platform-operator/rpc/pb/platformoperatorrpc"

	"oa.98ent.com/p9/platform-operator/rpc/pb/platformoperatorrpc/operatornodepb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	OperatorNodeService interface {
		// 保存分站部署节点
		Save(ctx context.Context, in *operatornodepb.SaveOperatorNodeRequest, opts ...grpc.CallOption) (*operatornodepb.SaveOperatorNodeResponse, error)
		// 获取分站部署节点
		Get(ctx context.Context, in *operatornodepb.GetOperatorNodeRequest, opts ...grpc.CallOption) (*operatornodepb.GetOperatorNodeResponse, error)
	}

	defaultOperatorNodeService struct {
		cli zrpc.Client
	}
)

func NewOperatorNodeService(cli zrpc.Client) OperatorNodeService {
	return &defaultOperatorNodeService{
		cli: cli,
	}
}

// 保存分站部署节点
func (m *defaultOperatorNodeService) Save(ctx context.Context, in *operatornodepb.SaveOperatorNodeRequest, opts ...grpc.CallOption) (*operatornodepb.SaveOperatorNodeResponse, error) {
	client := platformoperatorrpc.NewOperatorNodeServiceClient(m.cli.Conn())
	return client.Save(ctx, in, opts...)
}

// 获取分站部署节点
func (m *defaultOperatorNodeService) Get(ctx context.Context, in *operatornodepb.GetOperatorNodeRequest, opts ...grpc.CallOption) (*operatornodepb.GetOperatorNodeResponse, error) {
	client := platformoperatorrpc.NewOperatorNodeServiceClient(m.cli.Conn())
	return client.Get(ctx, in, opts...)
}
