// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: settlement.proto

package server

import (
	"context"

	"oa.98ent.com/p9/operator-crm/service/settlement/rpc/internal/logic/pingservice"
	"oa.98ent.com/p9/operator-crm/service/settlement/rpc/internal/svc"
	"oa.98ent.com/p9/operator-crm/service/settlement/rpc/pb/settlementrpc"
	"oa.98ent.com/p9/operator-crm/service/settlement/rpc/pb/settlementrpc/pingpb"
)

type PingServiceServer struct {
	svcCtx *svc.ServiceContext
	settlementrpc.UnimplementedPingServiceServer
}

func NewPingServiceServer(svcCtx *svc.ServiceContext) *PingServiceServer {
	return &PingServiceServer{
		svcCtx: svcCtx,
	}
}

// 健康检查
func (s *PingServiceServer) Ping(ctx context.Context, in *pingpb.PingRequest) (*pingpb.PingResponse, error) {
	l := pingservicelogic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
