// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: operator_base.proto

package operatorservice

import (
	"context"

	"oa.98ent.com/p9/operator-base/rpc/pb/operatorbaserpc"

	"oa.98ent.com/p9/operator-base/rpc/pb/operatorbaserpc/operatorpb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	OperatorService interface {
		// 初始化厅 operator
		Initialize(ctx context.Context, in *operatorpb.InitializeOperatorRequest, opts ...grpc.CallOption) (*operatorpb.InitializeOperatorResponse, error)
		// 初始化基础资源分配到指定分站
		InitializeBasicResources(ctx context.Context, in *operatorpb.InitializeBasicResourcesRequest, opts ...grpc.CallOption) (*operatorpb.InitializeBasicResourcesResponse, error)
	}

	defaultOperatorService struct {
		cli zrpc.Client
	}
)

func NewOperatorService(cli zrpc.Client) OperatorService {
	return &defaultOperatorService{
		cli: cli,
	}
}

// 初始化厅 operator
func (m *defaultOperatorService) Initialize(ctx context.Context, in *operatorpb.InitializeOperatorRequest, opts ...grpc.CallOption) (*operatorpb.InitializeOperatorResponse, error) {
	client := operatorbaserpc.NewOperatorServiceClient(m.cli.Conn())
	return client.Initialize(ctx, in, opts...)
}

// 初始化基础资源分配到指定分站
func (m *defaultOperatorService) InitializeBasicResources(ctx context.Context, in *operatorpb.InitializeBasicResourcesRequest, opts ...grpc.CallOption) (*operatorpb.InitializeBasicResourcesResponse, error) {
	client := operatorbaserpc.NewOperatorServiceClient(m.cli.Conn())
	return client.InitializeBasicResources(ctx, in, opts...)
}
