// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: operator_game.proto

package gamecategoryservice

import (
	"context"

	"oa.98ent.com/p9/operator-game/rpc/pb/operator_game"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetGameCategoryListRequest = operator_game.GetGameCategoryListRequest
	GetGameCategoryListResp    = operator_game.GetGameCategoryListResp
	GetGameCategoryRequest     = operator_game.GetGameCategoryRequest
	GetGameCategoryResp        = operator_game.GetGameCategoryResp
	UpdateGameCategoryRequest  = operator_game.UpdateGameCategoryRequest
	UpdateGameCategoryResp     = operator_game.UpdateGameCategoryResp

	GameCategoryService interface {
		// 获取游戏分类列表
		GetGameCategoryList(ctx context.Context, in *GetGameCategoryListRequest, opts ...grpc.CallOption) (*GetGameCategoryListResp, error)
		// 获取单个游戏分类
		GetGameCategory(ctx context.Context, in *GetGameCategoryRequest, opts ...grpc.CallOption) (*GetGameCategoryResp, error)
		// 更新游戏分类
		UpdateGameCategory(ctx context.Context, in *UpdateGameCategoryRequest, opts ...grpc.CallOption) (*UpdateGameCategoryResp, error)
	}

	defaultGameCategoryService struct {
		cli zrpc.Client
	}
)

func NewGameCategoryService(cli zrpc.Client) GameCategoryService {
	return &defaultGameCategoryService{
		cli: cli,
	}
}

// 获取游戏分类列表
func (m *defaultGameCategoryService) GetGameCategoryList(ctx context.Context, in *GetGameCategoryListRequest, opts ...grpc.CallOption) (*GetGameCategoryListResp, error) {
	client := operator_game.NewGameCategoryServiceClient(m.cli.Conn())
	return client.GetGameCategoryList(ctx, in, opts...)
}

// 获取单个游戏分类
func (m *defaultGameCategoryService) GetGameCategory(ctx context.Context, in *GetGameCategoryRequest, opts ...grpc.CallOption) (*GetGameCategoryResp, error) {
	client := operator_game.NewGameCategoryServiceClient(m.cli.Conn())
	return client.GetGameCategory(ctx, in, opts...)
}

// 更新游戏分类
func (m *defaultGameCategoryService) UpdateGameCategory(ctx context.Context, in *UpdateGameCategoryRequest, opts ...grpc.CallOption) (*UpdateGameCategoryResp, error) {
	client := operator_game.NewGameCategoryServiceClient(m.cli.Conn())
	return client.UpdateGameCategory(ctx, in, opts...)
}
