// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.19.4
// source: types/published_currency.proto

package platform_game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PublishedGameCurrencyInfo 已发布的游戏货币信息
type PublishedGameCurrencyInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GameCode      string                 `protobuf:"bytes,2,opt,name=game_code,json=gameCode,proto3" json:"game_code,omitempty"`
	CurrencyCode  string                 `protobuf:"bytes,3,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishedGameCurrencyInfo) Reset() {
	*x = PublishedGameCurrencyInfo{}
	mi := &file_types_published_currency_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishedGameCurrencyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishedGameCurrencyInfo) ProtoMessage() {}

func (x *PublishedGameCurrencyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_types_published_currency_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishedGameCurrencyInfo.ProtoReflect.Descriptor instead.
func (*PublishedGameCurrencyInfo) Descriptor() ([]byte, []int) {
	return file_types_published_currency_proto_rawDescGZIP(), []int{0}
}

func (x *PublishedGameCurrencyInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PublishedGameCurrencyInfo) GetGameCode() string {
	if x != nil {
		return x.GameCode
	}
	return ""
}

func (x *PublishedGameCurrencyInfo) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *PublishedGameCurrencyInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PublishedGameCurrencyInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *PublishedGameCurrencyInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// GetPublishedGameCurrencyListRequest 获取已发布游戏货币列表请求
type GetPublishedGameCurrencyListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpCode        string                 `protobuf:"bytes,1,opt,name=op_code,json=opCode,proto3" json:"op_code,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublishedGameCurrencyListRequest) Reset() {
	*x = GetPublishedGameCurrencyListRequest{}
	mi := &file_types_published_currency_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublishedGameCurrencyListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublishedGameCurrencyListRequest) ProtoMessage() {}

func (x *GetPublishedGameCurrencyListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_published_currency_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublishedGameCurrencyListRequest.ProtoReflect.Descriptor instead.
func (*GetPublishedGameCurrencyListRequest) Descriptor() ([]byte, []int) {
	return file_types_published_currency_proto_rawDescGZIP(), []int{1}
}

func (x *GetPublishedGameCurrencyListRequest) GetOpCode() string {
	if x != nil {
		return x.OpCode
	}
	return ""
}

func (x *GetPublishedGameCurrencyListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetPublishedGameCurrencyListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// GetPublishedGameCurrencyListResp 已发布游戏货币列表响应
type GetPublishedGameCurrencyListResp struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Items         []*PublishedGameCurrencyInfo `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                        `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                        `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                        `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublishedGameCurrencyListResp) Reset() {
	*x = GetPublishedGameCurrencyListResp{}
	mi := &file_types_published_currency_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublishedGameCurrencyListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublishedGameCurrencyListResp) ProtoMessage() {}

func (x *GetPublishedGameCurrencyListResp) ProtoReflect() protoreflect.Message {
	mi := &file_types_published_currency_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublishedGameCurrencyListResp.ProtoReflect.Descriptor instead.
func (*GetPublishedGameCurrencyListResp) Descriptor() ([]byte, []int) {
	return file_types_published_currency_proto_rawDescGZIP(), []int{2}
}

func (x *GetPublishedGameCurrencyListResp) GetItems() []*PublishedGameCurrencyInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetPublishedGameCurrencyListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetPublishedGameCurrencyListResp) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetPublishedGameCurrencyListResp) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_types_published_currency_proto protoreflect.FileDescriptor

const file_types_published_currency_proto_rawDesc = "" +
	"\n" +
	"\x1etypes/published_currency.proto\x12\rplatform_game\"\xc3\x01\n" +
	"\x19PublishedGameCurrencyInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tgame_code\x18\x02 \x01(\tR\bgameCode\x12#\n" +
	"\rcurrency_code\x18\x03 \x01(\tR\fcurrencyCode\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\"o\n" +
	"#GetPublishedGameCurrencyListRequest\x12\x17\n" +
	"\aop_code\x18\x01 \x01(\tR\x06opCode\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\xa9\x01\n" +
	" GetPublishedGameCurrencyListResp\x12>\n" +
	"\x05items\x18\x01 \x03(\v2(.platform_game.PublishedGameCurrencyInfoR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSizeB4Z2oa.98ent.com/p9/platform-game/rpc/pb/platform_gameb\x06proto3"

var (
	file_types_published_currency_proto_rawDescOnce sync.Once
	file_types_published_currency_proto_rawDescData []byte
)

func file_types_published_currency_proto_rawDescGZIP() []byte {
	file_types_published_currency_proto_rawDescOnce.Do(func() {
		file_types_published_currency_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_published_currency_proto_rawDesc), len(file_types_published_currency_proto_rawDesc)))
	})
	return file_types_published_currency_proto_rawDescData
}

var file_types_published_currency_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_types_published_currency_proto_goTypes = []any{
	(*PublishedGameCurrencyInfo)(nil),           // 0: platform_game.PublishedGameCurrencyInfo
	(*GetPublishedGameCurrencyListRequest)(nil), // 1: platform_game.GetPublishedGameCurrencyListRequest
	(*GetPublishedGameCurrencyListResp)(nil),    // 2: platform_game.GetPublishedGameCurrencyListResp
}
var file_types_published_currency_proto_depIdxs = []int32{
	0, // 0: platform_game.GetPublishedGameCurrencyListResp.items:type_name -> platform_game.PublishedGameCurrencyInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_types_published_currency_proto_init() }
func file_types_published_currency_proto_init() {
	if File_types_published_currency_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_published_currency_proto_rawDesc), len(file_types_published_currency_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_published_currency_proto_goTypes,
		DependencyIndexes: file_types_published_currency_proto_depIdxs,
		MessageInfos:      file_types_published_currency_proto_msgTypes,
	}.Build()
	File_types_published_currency_proto = out.File
	file_types_published_currency_proto_goTypes = nil
	file_types_published_currency_proto_depIdxs = nil
}
