// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.19.4
// source: types/published_game.proto

package platform_game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PublishedGameInfo 已发布的游戏信息
type PublishedGameInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SourceId         int64                  `protobuf:"varint,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	GameCode         string                 `protobuf:"bytes,3,opt,name=game_code,json=gameCode,proto3" json:"game_code,omitempty"`
	CategoryCode     string                 `protobuf:"bytes,4,opt,name=category_code,json=categoryCode,proto3" json:"category_code,omitempty"`
	ProviderCode     string                 `protobuf:"bytes,5,opt,name=provider_code,json=providerCode,proto3" json:"provider_code,omitempty"`
	ChannelCode      string                 `protobuf:"bytes,6,opt,name=channel_code,json=channelCode,proto3" json:"channel_code,omitempty"`
	Name             string                 `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	CurrencyCodeList []string               `protobuf:"bytes,8,rep,name=currency_code_list,json=currencyCodeList,proto3" json:"currency_code_list,omitempty"`
	ProviderKey      string                 `protobuf:"bytes,9,opt,name=provider_key,json=providerKey,proto3" json:"provider_key,omitempty"`
	ImageUrl         string                 `protobuf:"bytes,10,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	SortNo           int64                  `protobuf:"varint,11,opt,name=sort_no,json=sortNo,proto3" json:"sort_no,omitempty"`
	SupportsEmbed    bool                   `protobuf:"varint,12,opt,name=supports_embed,json=supportsEmbed,proto3" json:"supports_embed,omitempty"`
	SupportsRedirect bool                   `protobuf:"varint,13,opt,name=supports_redirect,json=supportsRedirect,proto3" json:"supports_redirect,omitempty"`
	Status           int32                  `protobuf:"varint,14,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt        int64                  `protobuf:"varint,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        int64                  `protobuf:"varint,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PublishedGameInfo) Reset() {
	*x = PublishedGameInfo{}
	mi := &file_types_published_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishedGameInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishedGameInfo) ProtoMessage() {}

func (x *PublishedGameInfo) ProtoReflect() protoreflect.Message {
	mi := &file_types_published_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishedGameInfo.ProtoReflect.Descriptor instead.
func (*PublishedGameInfo) Descriptor() ([]byte, []int) {
	return file_types_published_game_proto_rawDescGZIP(), []int{0}
}

func (x *PublishedGameInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PublishedGameInfo) GetSourceId() int64 {
	if x != nil {
		return x.SourceId
	}
	return 0
}

func (x *PublishedGameInfo) GetGameCode() string {
	if x != nil {
		return x.GameCode
	}
	return ""
}

func (x *PublishedGameInfo) GetCategoryCode() string {
	if x != nil {
		return x.CategoryCode
	}
	return ""
}

func (x *PublishedGameInfo) GetProviderCode() string {
	if x != nil {
		return x.ProviderCode
	}
	return ""
}

func (x *PublishedGameInfo) GetChannelCode() string {
	if x != nil {
		return x.ChannelCode
	}
	return ""
}

func (x *PublishedGameInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PublishedGameInfo) GetCurrencyCodeList() []string {
	if x != nil {
		return x.CurrencyCodeList
	}
	return nil
}

func (x *PublishedGameInfo) GetProviderKey() string {
	if x != nil {
		return x.ProviderKey
	}
	return ""
}

func (x *PublishedGameInfo) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *PublishedGameInfo) GetSortNo() int64 {
	if x != nil {
		return x.SortNo
	}
	return 0
}

func (x *PublishedGameInfo) GetSupportsEmbed() bool {
	if x != nil {
		return x.SupportsEmbed
	}
	return false
}

func (x *PublishedGameInfo) GetSupportsRedirect() bool {
	if x != nil {
		return x.SupportsRedirect
	}
	return false
}

func (x *PublishedGameInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PublishedGameInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *PublishedGameInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// GetPublishedGameListRequest 获取已发布游戏列表请求
type GetPublishedGameListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpCode        string                 `protobuf:"bytes,1,opt,name=op_code,json=opCode,proto3" json:"op_code,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	CategoryCode  string                 `protobuf:"bytes,4,opt,name=category_code,json=categoryCode,proto3" json:"category_code,omitempty"`
	ProviderCode  string                 `protobuf:"bytes,5,opt,name=provider_code,json=providerCode,proto3" json:"provider_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublishedGameListRequest) Reset() {
	*x = GetPublishedGameListRequest{}
	mi := &file_types_published_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublishedGameListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublishedGameListRequest) ProtoMessage() {}

func (x *GetPublishedGameListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_published_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublishedGameListRequest.ProtoReflect.Descriptor instead.
func (*GetPublishedGameListRequest) Descriptor() ([]byte, []int) {
	return file_types_published_game_proto_rawDescGZIP(), []int{1}
}

func (x *GetPublishedGameListRequest) GetOpCode() string {
	if x != nil {
		return x.OpCode
	}
	return ""
}

func (x *GetPublishedGameListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetPublishedGameListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetPublishedGameListRequest) GetCategoryCode() string {
	if x != nil {
		return x.CategoryCode
	}
	return ""
}

func (x *GetPublishedGameListRequest) GetProviderCode() string {
	if x != nil {
		return x.ProviderCode
	}
	return ""
}

// GetPublishedGameListResp 已发布游戏列表响应
type GetPublishedGameListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameItems     []*PublishedGameInfo   `protobuf:"bytes,1,rep,name=game_items,json=gameItems,proto3" json:"game_items,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublishedGameListResp) Reset() {
	*x = GetPublishedGameListResp{}
	mi := &file_types_published_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublishedGameListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublishedGameListResp) ProtoMessage() {}

func (x *GetPublishedGameListResp) ProtoReflect() protoreflect.Message {
	mi := &file_types_published_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublishedGameListResp.ProtoReflect.Descriptor instead.
func (*GetPublishedGameListResp) Descriptor() ([]byte, []int) {
	return file_types_published_game_proto_rawDescGZIP(), []int{2}
}

func (x *GetPublishedGameListResp) GetGameItems() []*PublishedGameInfo {
	if x != nil {
		return x.GameItems
	}
	return nil
}

func (x *GetPublishedGameListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetPublishedGameListResp) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetPublishedGameListResp) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_types_published_game_proto protoreflect.FileDescriptor

const file_types_published_game_proto_rawDesc = "" +
	"\n" +
	"\x1atypes/published_game.proto\x12\rplatform_game\"\x8f\x04\n" +
	"\x11PublishedGameInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tsource_id\x18\x02 \x01(\x03R\bsourceId\x12\x1b\n" +
	"\tgame_code\x18\x03 \x01(\tR\bgameCode\x12#\n" +
	"\rcategory_code\x18\x04 \x01(\tR\fcategoryCode\x12#\n" +
	"\rprovider_code\x18\x05 \x01(\tR\fproviderCode\x12!\n" +
	"\fchannel_code\x18\x06 \x01(\tR\vchannelCode\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\x12,\n" +
	"\x12currency_code_list\x18\b \x03(\tR\x10currencyCodeList\x12!\n" +
	"\fprovider_key\x18\t \x01(\tR\vproviderKey\x12\x1b\n" +
	"\timage_url\x18\n" +
	" \x01(\tR\bimageUrl\x12\x17\n" +
	"\asort_no\x18\v \x01(\x03R\x06sortNo\x12%\n" +
	"\x0esupports_embed\x18\f \x01(\bR\rsupportsEmbed\x12+\n" +
	"\x11supports_redirect\x18\r \x01(\bR\x10supportsRedirect\x12\x16\n" +
	"\x06status\x18\x0e \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0f \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\x03R\tupdatedAt\"\xb1\x01\n" +
	"\x1bGetPublishedGameListRequest\x12\x17\n" +
	"\aop_code\x18\x01 \x01(\tR\x06opCode\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12#\n" +
	"\rcategory_code\x18\x04 \x01(\tR\fcategoryCode\x12#\n" +
	"\rprovider_code\x18\x05 \x01(\tR\fproviderCode\"\xa2\x01\n" +
	"\x18GetPublishedGameListResp\x12?\n" +
	"\n" +
	"game_items\x18\x01 \x03(\v2 .platform_game.PublishedGameInfoR\tgameItems\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSizeB4Z2oa.98ent.com/p9/platform-game/rpc/pb/platform_gameb\x06proto3"

var (
	file_types_published_game_proto_rawDescOnce sync.Once
	file_types_published_game_proto_rawDescData []byte
)

func file_types_published_game_proto_rawDescGZIP() []byte {
	file_types_published_game_proto_rawDescOnce.Do(func() {
		file_types_published_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_published_game_proto_rawDesc), len(file_types_published_game_proto_rawDesc)))
	})
	return file_types_published_game_proto_rawDescData
}

var file_types_published_game_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_types_published_game_proto_goTypes = []any{
	(*PublishedGameInfo)(nil),           // 0: platform_game.PublishedGameInfo
	(*GetPublishedGameListRequest)(nil), // 1: platform_game.GetPublishedGameListRequest
	(*GetPublishedGameListResp)(nil),    // 2: platform_game.GetPublishedGameListResp
}
var file_types_published_game_proto_depIdxs = []int32{
	0, // 0: platform_game.GetPublishedGameListResp.game_items:type_name -> platform_game.PublishedGameInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_types_published_game_proto_init() }
func file_types_published_game_proto_init() {
	if File_types_published_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_published_game_proto_rawDesc), len(file_types_published_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_published_game_proto_goTypes,
		DependencyIndexes: file_types_published_game_proto_depIdxs,
		MessageInfos:      file_types_published_game_proto_msgTypes,
	}.Build()
	File_types_published_game_proto = out.File
	file_types_published_game_proto_goTypes = nil
	file_types_published_game_proto_depIdxs = nil
}
