// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.19.4
// source: types/published_provider.proto

package platform_game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PublishedGameProviderInfo 已发布的游戏供应商信息
type PublishedGameProviderInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProviderCode  string                 `protobuf:"bytes,2,opt,name=provider_code,json=providerCode,proto3" json:"provider_code,omitempty"`
	ChannelCode   string                 `protobuf:"bytes,3,opt,name=channel_code,json=channelCode,proto3" json:"channel_code,omitempty"`
	LogoUrl       string                 `protobuf:"bytes,4,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	SortNo        int64                  `protobuf:"varint,5,opt,name=sort_no,json=sortNo,proto3" json:"sort_no,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishedGameProviderInfo) Reset() {
	*x = PublishedGameProviderInfo{}
	mi := &file_types_published_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishedGameProviderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishedGameProviderInfo) ProtoMessage() {}

func (x *PublishedGameProviderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_types_published_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishedGameProviderInfo.ProtoReflect.Descriptor instead.
func (*PublishedGameProviderInfo) Descriptor() ([]byte, []int) {
	return file_types_published_provider_proto_rawDescGZIP(), []int{0}
}

func (x *PublishedGameProviderInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PublishedGameProviderInfo) GetProviderCode() string {
	if x != nil {
		return x.ProviderCode
	}
	return ""
}

func (x *PublishedGameProviderInfo) GetChannelCode() string {
	if x != nil {
		return x.ChannelCode
	}
	return ""
}

func (x *PublishedGameProviderInfo) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

func (x *PublishedGameProviderInfo) GetSortNo() int64 {
	if x != nil {
		return x.SortNo
	}
	return 0
}

func (x *PublishedGameProviderInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PublishedGameProviderInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *PublishedGameProviderInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// GetPublishedGameProviderListRequest 获取已发布游戏供应商列表请求
type GetPublishedGameProviderListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpCode        string                 `protobuf:"bytes,1,opt,name=op_code,json=opCode,proto3" json:"op_code,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublishedGameProviderListRequest) Reset() {
	*x = GetPublishedGameProviderListRequest{}
	mi := &file_types_published_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublishedGameProviderListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublishedGameProviderListRequest) ProtoMessage() {}

func (x *GetPublishedGameProviderListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_published_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublishedGameProviderListRequest.ProtoReflect.Descriptor instead.
func (*GetPublishedGameProviderListRequest) Descriptor() ([]byte, []int) {
	return file_types_published_provider_proto_rawDescGZIP(), []int{1}
}

func (x *GetPublishedGameProviderListRequest) GetOpCode() string {
	if x != nil {
		return x.OpCode
	}
	return ""
}

func (x *GetPublishedGameProviderListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetPublishedGameProviderListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// GetPublishedGameProviderListResp 已发布游戏供应商列表响应
type GetPublishedGameProviderListResp struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Items         []*PublishedGameProviderInfo `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                        `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                        `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                        `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublishedGameProviderListResp) Reset() {
	*x = GetPublishedGameProviderListResp{}
	mi := &file_types_published_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublishedGameProviderListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublishedGameProviderListResp) ProtoMessage() {}

func (x *GetPublishedGameProviderListResp) ProtoReflect() protoreflect.Message {
	mi := &file_types_published_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublishedGameProviderListResp.ProtoReflect.Descriptor instead.
func (*GetPublishedGameProviderListResp) Descriptor() ([]byte, []int) {
	return file_types_published_provider_proto_rawDescGZIP(), []int{2}
}

func (x *GetPublishedGameProviderListResp) GetItems() []*PublishedGameProviderInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetPublishedGameProviderListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetPublishedGameProviderListResp) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetPublishedGameProviderListResp) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_types_published_provider_proto protoreflect.FileDescriptor

const file_types_published_provider_proto_rawDesc = "" +
	"\n" +
	"\x1etypes/published_provider.proto\x12\rplatform_game\"\xfd\x01\n" +
	"\x19PublishedGameProviderInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12#\n" +
	"\rprovider_code\x18\x02 \x01(\tR\fproviderCode\x12!\n" +
	"\fchannel_code\x18\x03 \x01(\tR\vchannelCode\x12\x19\n" +
	"\blogo_url\x18\x04 \x01(\tR\alogoUrl\x12\x17\n" +
	"\asort_no\x18\x05 \x01(\x03R\x06sortNo\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt\"o\n" +
	"#GetPublishedGameProviderListRequest\x12\x17\n" +
	"\aop_code\x18\x01 \x01(\tR\x06opCode\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\xa9\x01\n" +
	" GetPublishedGameProviderListResp\x12>\n" +
	"\x05items\x18\x01 \x03(\v2(.platform_game.PublishedGameProviderInfoR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSizeB4Z2oa.98ent.com/p9/platform-game/rpc/pb/platform_gameb\x06proto3"

var (
	file_types_published_provider_proto_rawDescOnce sync.Once
	file_types_published_provider_proto_rawDescData []byte
)

func file_types_published_provider_proto_rawDescGZIP() []byte {
	file_types_published_provider_proto_rawDescOnce.Do(func() {
		file_types_published_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_published_provider_proto_rawDesc), len(file_types_published_provider_proto_rawDesc)))
	})
	return file_types_published_provider_proto_rawDescData
}

var file_types_published_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_types_published_provider_proto_goTypes = []any{
	(*PublishedGameProviderInfo)(nil),           // 0: platform_game.PublishedGameProviderInfo
	(*GetPublishedGameProviderListRequest)(nil), // 1: platform_game.GetPublishedGameProviderListRequest
	(*GetPublishedGameProviderListResp)(nil),    // 2: platform_game.GetPublishedGameProviderListResp
}
var file_types_published_provider_proto_depIdxs = []int32{
	0, // 0: platform_game.GetPublishedGameProviderListResp.items:type_name -> platform_game.PublishedGameProviderInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_types_published_provider_proto_init() }
func file_types_published_provider_proto_init() {
	if File_types_published_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_published_provider_proto_rawDesc), len(file_types_published_provider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_published_provider_proto_goTypes,
		DependencyIndexes: file_types_published_provider_proto_depIdxs,
		MessageInfos:      file_types_published_provider_proto_msgTypes,
	}.Build()
	File_types_published_provider_proto = out.File
	file_types_published_provider_proto_goTypes = nil
	file_types_published_provider_proto_depIdxs = nil
}
