// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.19.4
// source: types/published_channel.proto

package platform_game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PublishedGameChannelInfo 已发布的游戏渠道信息
type PublishedGameChannelInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ChannelCode   string                 `protobuf:"bytes,2,opt,name=channel_code,json=channelCode,proto3" json:"channel_code,omitempty"`
	SortNo        int64                  `protobuf:"varint,3,opt,name=sort_no,json=sortNo,proto3" json:"sort_no,omitempty"`
	LoadType      int64                  `protobuf:"varint,4,opt,name=load_type,json=loadType,proto3" json:"load_type,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishedGameChannelInfo) Reset() {
	*x = PublishedGameChannelInfo{}
	mi := &file_types_published_channel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishedGameChannelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishedGameChannelInfo) ProtoMessage() {}

func (x *PublishedGameChannelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_types_published_channel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishedGameChannelInfo.ProtoReflect.Descriptor instead.
func (*PublishedGameChannelInfo) Descriptor() ([]byte, []int) {
	return file_types_published_channel_proto_rawDescGZIP(), []int{0}
}

func (x *PublishedGameChannelInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PublishedGameChannelInfo) GetChannelCode() string {
	if x != nil {
		return x.ChannelCode
	}
	return ""
}

func (x *PublishedGameChannelInfo) GetSortNo() int64 {
	if x != nil {
		return x.SortNo
	}
	return 0
}

func (x *PublishedGameChannelInfo) GetLoadType() int64 {
	if x != nil {
		return x.LoadType
	}
	return 0
}

func (x *PublishedGameChannelInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PublishedGameChannelInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *PublishedGameChannelInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// GetPublishedGameChannelListRequest 获取已发布游戏渠道列表请求
type GetPublishedGameChannelListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpCode        string                 `protobuf:"bytes,1,opt,name=op_code,json=opCode,proto3" json:"op_code,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublishedGameChannelListRequest) Reset() {
	*x = GetPublishedGameChannelListRequest{}
	mi := &file_types_published_channel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublishedGameChannelListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublishedGameChannelListRequest) ProtoMessage() {}

func (x *GetPublishedGameChannelListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_published_channel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublishedGameChannelListRequest.ProtoReflect.Descriptor instead.
func (*GetPublishedGameChannelListRequest) Descriptor() ([]byte, []int) {
	return file_types_published_channel_proto_rawDescGZIP(), []int{1}
}

func (x *GetPublishedGameChannelListRequest) GetOpCode() string {
	if x != nil {
		return x.OpCode
	}
	return ""
}

func (x *GetPublishedGameChannelListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetPublishedGameChannelListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// GetPublishedGameChannelListResp 已发布游戏渠道列表响应
type GetPublishedGameChannelListResp struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Items         []*PublishedGameChannelInfo `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                       `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                       `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                       `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublishedGameChannelListResp) Reset() {
	*x = GetPublishedGameChannelListResp{}
	mi := &file_types_published_channel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublishedGameChannelListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublishedGameChannelListResp) ProtoMessage() {}

func (x *GetPublishedGameChannelListResp) ProtoReflect() protoreflect.Message {
	mi := &file_types_published_channel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublishedGameChannelListResp.ProtoReflect.Descriptor instead.
func (*GetPublishedGameChannelListResp) Descriptor() ([]byte, []int) {
	return file_types_published_channel_proto_rawDescGZIP(), []int{2}
}

func (x *GetPublishedGameChannelListResp) GetItems() []*PublishedGameChannelInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetPublishedGameChannelListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetPublishedGameChannelListResp) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetPublishedGameChannelListResp) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_types_published_channel_proto protoreflect.FileDescriptor

const file_types_published_channel_proto_rawDesc = "" +
	"\n" +
	"\x1dtypes/published_channel.proto\x12\rplatform_game\"\xd9\x01\n" +
	"\x18PublishedGameChannelInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\fchannel_code\x18\x02 \x01(\tR\vchannelCode\x12\x17\n" +
	"\asort_no\x18\x03 \x01(\x03R\x06sortNo\x12\x1b\n" +
	"\tload_type\x18\x04 \x01(\x03R\bloadType\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt\"n\n" +
	"\"GetPublishedGameChannelListRequest\x12\x17\n" +
	"\aop_code\x18\x01 \x01(\tR\x06opCode\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\xa7\x01\n" +
	"\x1fGetPublishedGameChannelListResp\x12=\n" +
	"\x05items\x18\x01 \x03(\v2'.platform_game.PublishedGameChannelInfoR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSizeB4Z2oa.98ent.com/p9/platform-game/rpc/pb/platform_gameb\x06proto3"

var (
	file_types_published_channel_proto_rawDescOnce sync.Once
	file_types_published_channel_proto_rawDescData []byte
)

func file_types_published_channel_proto_rawDescGZIP() []byte {
	file_types_published_channel_proto_rawDescOnce.Do(func() {
		file_types_published_channel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_published_channel_proto_rawDesc), len(file_types_published_channel_proto_rawDesc)))
	})
	return file_types_published_channel_proto_rawDescData
}

var file_types_published_channel_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_types_published_channel_proto_goTypes = []any{
	(*PublishedGameChannelInfo)(nil),           // 0: platform_game.PublishedGameChannelInfo
	(*GetPublishedGameChannelListRequest)(nil), // 1: platform_game.GetPublishedGameChannelListRequest
	(*GetPublishedGameChannelListResp)(nil),    // 2: platform_game.GetPublishedGameChannelListResp
}
var file_types_published_channel_proto_depIdxs = []int32{
	0, // 0: platform_game.GetPublishedGameChannelListResp.items:type_name -> platform_game.PublishedGameChannelInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_types_published_channel_proto_init() }
func file_types_published_channel_proto_init() {
	if File_types_published_channel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_published_channel_proto_rawDesc), len(file_types_published_channel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_published_channel_proto_goTypes,
		DependencyIndexes: file_types_published_channel_proto_depIdxs,
		MessageInfos:      file_types_published_channel_proto_msgTypes,
	}.Build()
	File_types_published_channel_proto = out.File
	file_types_published_channel_proto_goTypes = nil
	file_types_published_channel_proto_depIdxs = nil
}
