// Code generated by ent, DO NOT EDIT.

package gamecurrency

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the gamecurrency type in the database.
	Label = "game_currency"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldGameCode holds the string denoting the game_code field in the database.
	FieldGameCode = "game_code"
	// FieldCurrencyCode holds the string denoting the currency_code field in the database.
	FieldCurrencyCode = "currency_code"
	// FieldSourceStatus holds the string denoting the source_status field in the database.
	FieldSourceStatus = "source_status"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the gamecurrency in the database.
	Table = "game_currency"
)

// Columns holds all SQL columns for gamecurrency fields.
var Columns = []string{
	FieldID,
	FieldGameCode,
	FieldCurrencyCode,
	FieldSourceStatus,
	FieldStatus,
	FieldDeletedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(int64) error
)

// OrderOption defines the ordering options for the GameCurrency queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByGameCode orders the results by the game_code field.
func ByGameCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGameCode, opts...).ToFunc()
}

// ByCurrencyCode orders the results by the currency_code field.
func ByCurrencyCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrencyCode, opts...).ToFunc()
}

// BySourceStatus orders the results by the source_status field.
func BySourceStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceStatus, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
