// Code generated by ent, DO NOT EDIT.

package gamecurrency

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"oa.98ent.com/p9/platform-game/rpc/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldLTE(FieldID, id))
}

// GameCode applies equality check predicate on the "game_code" field. It's identical to GameCodeEQ.
func GameCode(v string) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldEQ(FieldGameCode, v))
}

// CurrencyCode applies equality check predicate on the "currency_code" field. It's identical to CurrencyCodeEQ.
func CurrencyCode(v string) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldEQ(FieldCurrencyCode, v))
}

// SourceStatus applies equality check predicate on the "source_status" field. It's identical to SourceStatusEQ.
func SourceStatus(v int64) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldEQ(FieldSourceStatus, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v int64) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldEQ(FieldStatus, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldEQ(FieldDeletedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldEQ(FieldUpdatedAt, v))
}

// GameCodeEQ applies the EQ predicate on the "game_code" field.
func GameCodeEQ(v string) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldEQ(FieldGameCode, v))
}

// GameCodeNEQ applies the NEQ predicate on the "game_code" field.
func GameCodeNEQ(v string) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldNEQ(FieldGameCode, v))
}

// GameCodeIn applies the In predicate on the "game_code" field.
func GameCodeIn(vs ...string) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldIn(FieldGameCode, vs...))
}

// GameCodeNotIn applies the NotIn predicate on the "game_code" field.
func GameCodeNotIn(vs ...string) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldNotIn(FieldGameCode, vs...))
}

// GameCodeGT applies the GT predicate on the "game_code" field.
func GameCodeGT(v string) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldGT(FieldGameCode, v))
}

// GameCodeGTE applies the GTE predicate on the "game_code" field.
func GameCodeGTE(v string) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldGTE(FieldGameCode, v))
}

// GameCodeLT applies the LT predicate on the "game_code" field.
func GameCodeLT(v string) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldLT(FieldGameCode, v))
}

// GameCodeLTE applies the LTE predicate on the "game_code" field.
func GameCodeLTE(v string) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldLTE(FieldGameCode, v))
}

// GameCodeContains applies the Contains predicate on the "game_code" field.
func GameCodeContains(v string) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldContains(FieldGameCode, v))
}

// GameCodeHasPrefix applies the HasPrefix predicate on the "game_code" field.
func GameCodeHasPrefix(v string) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldHasPrefix(FieldGameCode, v))
}

// GameCodeHasSuffix applies the HasSuffix predicate on the "game_code" field.
func GameCodeHasSuffix(v string) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldHasSuffix(FieldGameCode, v))
}

// GameCodeEqualFold applies the EqualFold predicate on the "game_code" field.
func GameCodeEqualFold(v string) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldEqualFold(FieldGameCode, v))
}

// GameCodeContainsFold applies the ContainsFold predicate on the "game_code" field.
func GameCodeContainsFold(v string) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldContainsFold(FieldGameCode, v))
}

// CurrencyCodeEQ applies the EQ predicate on the "currency_code" field.
func CurrencyCodeEQ(v string) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldEQ(FieldCurrencyCode, v))
}

// CurrencyCodeNEQ applies the NEQ predicate on the "currency_code" field.
func CurrencyCodeNEQ(v string) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldNEQ(FieldCurrencyCode, v))
}

// CurrencyCodeIn applies the In predicate on the "currency_code" field.
func CurrencyCodeIn(vs ...string) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldIn(FieldCurrencyCode, vs...))
}

// CurrencyCodeNotIn applies the NotIn predicate on the "currency_code" field.
func CurrencyCodeNotIn(vs ...string) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldNotIn(FieldCurrencyCode, vs...))
}

// CurrencyCodeGT applies the GT predicate on the "currency_code" field.
func CurrencyCodeGT(v string) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldGT(FieldCurrencyCode, v))
}

// CurrencyCodeGTE applies the GTE predicate on the "currency_code" field.
func CurrencyCodeGTE(v string) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldGTE(FieldCurrencyCode, v))
}

// CurrencyCodeLT applies the LT predicate on the "currency_code" field.
func CurrencyCodeLT(v string) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldLT(FieldCurrencyCode, v))
}

// CurrencyCodeLTE applies the LTE predicate on the "currency_code" field.
func CurrencyCodeLTE(v string) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldLTE(FieldCurrencyCode, v))
}

// CurrencyCodeContains applies the Contains predicate on the "currency_code" field.
func CurrencyCodeContains(v string) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldContains(FieldCurrencyCode, v))
}

// CurrencyCodeHasPrefix applies the HasPrefix predicate on the "currency_code" field.
func CurrencyCodeHasPrefix(v string) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldHasPrefix(FieldCurrencyCode, v))
}

// CurrencyCodeHasSuffix applies the HasSuffix predicate on the "currency_code" field.
func CurrencyCodeHasSuffix(v string) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldHasSuffix(FieldCurrencyCode, v))
}

// CurrencyCodeEqualFold applies the EqualFold predicate on the "currency_code" field.
func CurrencyCodeEqualFold(v string) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldEqualFold(FieldCurrencyCode, v))
}

// CurrencyCodeContainsFold applies the ContainsFold predicate on the "currency_code" field.
func CurrencyCodeContainsFold(v string) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldContainsFold(FieldCurrencyCode, v))
}

// SourceStatusEQ applies the EQ predicate on the "source_status" field.
func SourceStatusEQ(v int64) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldEQ(FieldSourceStatus, v))
}

// SourceStatusNEQ applies the NEQ predicate on the "source_status" field.
func SourceStatusNEQ(v int64) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldNEQ(FieldSourceStatus, v))
}

// SourceStatusIn applies the In predicate on the "source_status" field.
func SourceStatusIn(vs ...int64) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldIn(FieldSourceStatus, vs...))
}

// SourceStatusNotIn applies the NotIn predicate on the "source_status" field.
func SourceStatusNotIn(vs ...int64) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldNotIn(FieldSourceStatus, vs...))
}

// SourceStatusGT applies the GT predicate on the "source_status" field.
func SourceStatusGT(v int64) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldGT(FieldSourceStatus, v))
}

// SourceStatusGTE applies the GTE predicate on the "source_status" field.
func SourceStatusGTE(v int64) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldGTE(FieldSourceStatus, v))
}

// SourceStatusLT applies the LT predicate on the "source_status" field.
func SourceStatusLT(v int64) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldLT(FieldSourceStatus, v))
}

// SourceStatusLTE applies the LTE predicate on the "source_status" field.
func SourceStatusLTE(v int64) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldLTE(FieldSourceStatus, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v int64) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v int64) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...int64) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...int64) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v int64) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v int64) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v int64) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v int64) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldLTE(FieldStatus, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldNotNull(FieldDeletedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.GameCurrency {
	return predicate.GameCurrency(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GameCurrency) predicate.GameCurrency {
	return predicate.GameCurrency(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GameCurrency) predicate.GameCurrency {
	return predicate.GameCurrency(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GameCurrency) predicate.GameCurrency {
	return predicate.GameCurrency(sql.NotPredicates(p))
}
