// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: settlement.proto

package pingservice

import (
	"context"

	"oa.98ent.com/p9/operator-crm/service/settlement/rpc/pb/settlementrpc"

	"oa.98ent.com/p9/operator-crm/service/settlement/rpc/pb/settlementrpc/pingpb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	PingService interface {
		// 健康检查
		Ping(ctx context.Context, in *pingpb.PingRequest, opts ...grpc.CallOption) (*pingpb.PingResponse, error)
	}

	defaultPingService struct {
		cli zrpc.Client
	}
)

func NewPingService(cli zrpc.Client) PingService {
	return &defaultPingService{
		cli: cli,
	}
}

// 健康检查
func (m *defaultPingService) Ping(ctx context.Context, in *pingpb.PingRequest, opts ...grpc.CallOption) (*pingpb.PingResponse, error) {
	client := settlementrpc.NewPingServiceClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
