Name: operator02-core-api
Host: 0.0.0.0
Port: 38200

Log:
  Mode: console
  Level: info

# 开发模式
Mode: dev
# 模式 on分站，off总网
PartnerMode: "on"

CROSConf:
  Address: '*'

CoreRpc:
  Endpoints:
    - operator-node02-core-rpc:39200
  NonBlock: true
  Timeout: 3000

# 链路追踪, 生产建议 Sampler 0.01~0.1
Telemetry:
  Name: operator02-core-api
  Endpoint: 192.168.0.15:4317
  Sampler: 1.0
  Batcher: otlpgrpc
