Name: operator02-core-rpc
ListenOn: 0.0.0.0:39200
Timeout: 10000
Mode: dev

Log:
  Mode: console
  Level: info

DB:
  Driver: postgres
  DSN: "host=postgres user=root password=root dbname=p9_operator port=5432 sslmode=disable TimeZone=UTC"

DataRedis:
  Host: redis:6379
  Pass: ""
  DB: 0

Jwt:
  AccessSecret: rbacx-example-secret-node02
  AccessExpire: 86400
  RefreshSecret: rbacx-example-refresh-secret-node02
  RefreshExpire: 604800

# 链路追踪, 生产建议 Sampler 0.01~0.1
Telemetry:
  Name: operator02-core-rpc
  Endpoint: 192.168.0.15:4317
  Sampler: 1.0
  Batcher: otlpgrpc

PartnerMode: "on"
APIPrefix: /admin
InitToken: change-me-init-token

