// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"oa.98ent.com/p9/operator-game/rpc/ent/game"
	"oa.98ent.com/p9/operator-game/rpc/ent/schema"
)

// 分站游戏表
type Game struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// OpCode holds the value of the "op_code" field.
	OpCode string `json:"op_code,omitempty"`
	// GameCode holds the value of the "game_code" field.
	GameCode string `json:"game_code,omitempty"`
	// SourceID holds the value of the "source_id" field.
	SourceID int64 `json:"source_id,omitempty"`
	// CategoryCode holds the value of the "category_code" field.
	CategoryCode string `json:"category_code,omitempty"`
	// ProviderCode holds the value of the "provider_code" field.
	ProviderCode string `json:"provider_code,omitempty"`
	// ChannelCode holds the value of the "channel_code" field.
	ChannelCode string `json:"channel_code,omitempty"`
	// CurrencyList holds the value of the "currency_list" field.
	CurrencyList []schema.CurrencyInfo `json:"currency_list,omitempty"`
	// ProviderKey holds the value of the "provider_key" field.
	ProviderKey string `json:"provider_key,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// ImageURL holds the value of the "image_url" field.
	ImageURL string `json:"image_url,omitempty"`
	// SortNo holds the value of the "sort_no" field.
	SortNo int64 `json:"sort_no,omitempty"`
	// SupportsEmbed holds the value of the "supports_embed" field.
	SupportsEmbed bool `json:"supports_embed,omitempty"`
	// SupportsRedirect holds the value of the "supports_redirect" field.
	SupportsRedirect bool `json:"supports_redirect,omitempty"`
	// Status | 状态
	Status int64 `json:"status,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Game) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case game.FieldCurrencyList:
			values[i] = new([]byte)
		case game.FieldSupportsEmbed, game.FieldSupportsRedirect:
			values[i] = new(sql.NullBool)
		case game.FieldID, game.FieldSourceID, game.FieldSortNo, game.FieldStatus:
			values[i] = new(sql.NullInt64)
		case game.FieldOpCode, game.FieldGameCode, game.FieldCategoryCode, game.FieldProviderCode, game.FieldChannelCode, game.FieldProviderKey, game.FieldName, game.FieldImageURL:
			values[i] = new(sql.NullString)
		case game.FieldCreatedAt, game.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Game fields.
func (_m *Game) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case game.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case game.FieldOpCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field op_code", values[i])
			} else if value.Valid {
				_m.OpCode = value.String
			}
		case game.FieldGameCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field game_code", values[i])
			} else if value.Valid {
				_m.GameCode = value.String
			}
		case game.FieldSourceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field source_id", values[i])
			} else if value.Valid {
				_m.SourceID = value.Int64
			}
		case game.FieldCategoryCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category_code", values[i])
			} else if value.Valid {
				_m.CategoryCode = value.String
			}
		case game.FieldProviderCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_code", values[i])
			} else if value.Valid {
				_m.ProviderCode = value.String
			}
		case game.FieldChannelCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field channel_code", values[i])
			} else if value.Valid {
				_m.ChannelCode = value.String
			}
		case game.FieldCurrencyList:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field currency_list", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.CurrencyList); err != nil {
					return fmt.Errorf("unmarshal field currency_list: %w", err)
				}
			}
		case game.FieldProviderKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_key", values[i])
			} else if value.Valid {
				_m.ProviderKey = value.String
			}
		case game.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case game.FieldImageURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field image_url", values[i])
			} else if value.Valid {
				_m.ImageURL = value.String
			}
		case game.FieldSortNo:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_no", values[i])
			} else if value.Valid {
				_m.SortNo = value.Int64
			}
		case game.FieldSupportsEmbed:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field supports_embed", values[i])
			} else if value.Valid {
				_m.SupportsEmbed = value.Bool
			}
		case game.FieldSupportsRedirect:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field supports_redirect", values[i])
			} else if value.Valid {
				_m.SupportsRedirect = value.Bool
			}
		case game.FieldStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.Int64
			}
		case game.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case game.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Game.
// This includes values selected through modifiers, order, etc.
func (_m *Game) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Game.
// Note that you need to call Game.Unwrap() before calling this method if this Game
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Game) Update() *GameUpdateOne {
	return NewGameClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Game entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Game) Unwrap() *Game {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Game is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Game) String() string {
	var builder strings.Builder
	builder.WriteString("Game(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("op_code=")
	builder.WriteString(_m.OpCode)
	builder.WriteString(", ")
	builder.WriteString("game_code=")
	builder.WriteString(_m.GameCode)
	builder.WriteString(", ")
	builder.WriteString("source_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SourceID))
	builder.WriteString(", ")
	builder.WriteString("category_code=")
	builder.WriteString(_m.CategoryCode)
	builder.WriteString(", ")
	builder.WriteString("provider_code=")
	builder.WriteString(_m.ProviderCode)
	builder.WriteString(", ")
	builder.WriteString("channel_code=")
	builder.WriteString(_m.ChannelCode)
	builder.WriteString(", ")
	builder.WriteString("currency_list=")
	builder.WriteString(fmt.Sprintf("%v", _m.CurrencyList))
	builder.WriteString(", ")
	builder.WriteString("provider_key=")
	builder.WriteString(_m.ProviderKey)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("image_url=")
	builder.WriteString(_m.ImageURL)
	builder.WriteString(", ")
	builder.WriteString("sort_no=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortNo))
	builder.WriteString(", ")
	builder.WriteString("supports_embed=")
	builder.WriteString(fmt.Sprintf("%v", _m.SupportsEmbed))
	builder.WriteString(", ")
	builder.WriteString("supports_redirect=")
	builder.WriteString(fmt.Sprintf("%v", _m.SupportsRedirect))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Games is a parsable slice of Game.
type Games []*Game
