// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"oa.98ent.com/p9/operator-game/rpc/ent/gameprovider"
)

// 分站游戏供应商表
type GameProvider struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// ProviderCode holds the value of the "provider_code" field.
	ProviderCode string `json:"provider_code,omitempty"`
	// ChannelCode holds the value of the "channel_code" field.
	ChannelCode string `json:"channel_code,omitempty"`
	// LogoURL holds the value of the "logo_url" field.
	LogoURL string `json:"logo_url,omitempty"`
	// SortNo holds the value of the "sort_no" field.
	SortNo int64 `json:"sort_no,omitempty"`
	// Status holds the value of the "status" field.
	Status int64 `json:"status,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GameProvider) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case gameprovider.FieldID, gameprovider.FieldSortNo, gameprovider.FieldStatus:
			values[i] = new(sql.NullInt64)
		case gameprovider.FieldProviderCode, gameprovider.FieldChannelCode, gameprovider.FieldLogoURL:
			values[i] = new(sql.NullString)
		case gameprovider.FieldCreatedAt, gameprovider.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GameProvider fields.
func (_m *GameProvider) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case gameprovider.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case gameprovider.FieldProviderCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_code", values[i])
			} else if value.Valid {
				_m.ProviderCode = value.String
			}
		case gameprovider.FieldChannelCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field channel_code", values[i])
			} else if value.Valid {
				_m.ChannelCode = value.String
			}
		case gameprovider.FieldLogoURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field logo_url", values[i])
			} else if value.Valid {
				_m.LogoURL = value.String
			}
		case gameprovider.FieldSortNo:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_no", values[i])
			} else if value.Valid {
				_m.SortNo = value.Int64
			}
		case gameprovider.FieldStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.Int64
			}
		case gameprovider.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case gameprovider.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GameProvider.
// This includes values selected through modifiers, order, etc.
func (_m *GameProvider) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this GameProvider.
// Note that you need to call GameProvider.Unwrap() before calling this method if this GameProvider
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GameProvider) Update() *GameProviderUpdateOne {
	return NewGameProviderClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GameProvider entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GameProvider) Unwrap() *GameProvider {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: GameProvider is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GameProvider) String() string {
	var builder strings.Builder
	builder.WriteString("GameProvider(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("provider_code=")
	builder.WriteString(_m.ProviderCode)
	builder.WriteString(", ")
	builder.WriteString("channel_code=")
	builder.WriteString(_m.ChannelCode)
	builder.WriteString(", ")
	builder.WriteString("logo_url=")
	builder.WriteString(_m.LogoURL)
	builder.WriteString(", ")
	builder.WriteString("sort_no=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortNo))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// GameProviders is a parsable slice of GameProvider.
type GameProviders []*GameProvider
