// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"oa.98ent.com/p9/operator-game/rpc/ent/gameprovider"
	"oa.98ent.com/p9/operator-game/rpc/ent/predicate"
)

// GameProviderUpdate is the builder for updating GameProvider entities.
type GameProviderUpdate struct {
	config
	hooks    []Hook
	mutation *GameProviderMutation
}

// Where appends a list predicates to the GameProviderUpdate builder.
func (_u *GameProviderUpdate) Where(ps ...predicate.GameProvider) *GameProviderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProviderCode sets the "provider_code" field.
func (_u *GameProviderUpdate) SetProviderCode(v string) *GameProviderUpdate {
	_u.mutation.SetProviderCode(v)
	return _u
}

// SetNillableProviderCode sets the "provider_code" field if the given value is not nil.
func (_u *GameProviderUpdate) SetNillableProviderCode(v *string) *GameProviderUpdate {
	if v != nil {
		_u.SetProviderCode(*v)
	}
	return _u
}

// SetChannelCode sets the "channel_code" field.
func (_u *GameProviderUpdate) SetChannelCode(v string) *GameProviderUpdate {
	_u.mutation.SetChannelCode(v)
	return _u
}

// SetNillableChannelCode sets the "channel_code" field if the given value is not nil.
func (_u *GameProviderUpdate) SetNillableChannelCode(v *string) *GameProviderUpdate {
	if v != nil {
		_u.SetChannelCode(*v)
	}
	return _u
}

// ClearChannelCode clears the value of the "channel_code" field.
func (_u *GameProviderUpdate) ClearChannelCode() *GameProviderUpdate {
	_u.mutation.ClearChannelCode()
	return _u
}

// SetLogoURL sets the "logo_url" field.
func (_u *GameProviderUpdate) SetLogoURL(v string) *GameProviderUpdate {
	_u.mutation.SetLogoURL(v)
	return _u
}

// SetNillableLogoURL sets the "logo_url" field if the given value is not nil.
func (_u *GameProviderUpdate) SetNillableLogoURL(v *string) *GameProviderUpdate {
	if v != nil {
		_u.SetLogoURL(*v)
	}
	return _u
}

// ClearLogoURL clears the value of the "logo_url" field.
func (_u *GameProviderUpdate) ClearLogoURL() *GameProviderUpdate {
	_u.mutation.ClearLogoURL()
	return _u
}

// SetSortNo sets the "sort_no" field.
func (_u *GameProviderUpdate) SetSortNo(v int64) *GameProviderUpdate {
	_u.mutation.ResetSortNo()
	_u.mutation.SetSortNo(v)
	return _u
}

// SetNillableSortNo sets the "sort_no" field if the given value is not nil.
func (_u *GameProviderUpdate) SetNillableSortNo(v *int64) *GameProviderUpdate {
	if v != nil {
		_u.SetSortNo(*v)
	}
	return _u
}

// AddSortNo adds value to the "sort_no" field.
func (_u *GameProviderUpdate) AddSortNo(v int64) *GameProviderUpdate {
	_u.mutation.AddSortNo(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *GameProviderUpdate) SetStatus(v int64) *GameProviderUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *GameProviderUpdate) SetNillableStatus(v *int64) *GameProviderUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *GameProviderUpdate) AddStatus(v int64) *GameProviderUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *GameProviderUpdate) SetCreatedAt(v time.Time) *GameProviderUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *GameProviderUpdate) SetNillableCreatedAt(v *time.Time) *GameProviderUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GameProviderUpdate) SetUpdatedAt(v time.Time) *GameProviderUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *GameProviderUpdate) SetNillableUpdatedAt(v *time.Time) *GameProviderUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the GameProviderMutation object of the builder.
func (_u *GameProviderUpdate) Mutation() *GameProviderMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GameProviderUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GameProviderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GameProviderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GameProviderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *GameProviderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(gameprovider.Table, gameprovider.Columns, sqlgraph.NewFieldSpec(gameprovider.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProviderCode(); ok {
		_spec.SetField(gameprovider.FieldProviderCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChannelCode(); ok {
		_spec.SetField(gameprovider.FieldChannelCode, field.TypeString, value)
	}
	if _u.mutation.ChannelCodeCleared() {
		_spec.ClearField(gameprovider.FieldChannelCode, field.TypeString)
	}
	if value, ok := _u.mutation.LogoURL(); ok {
		_spec.SetField(gameprovider.FieldLogoURL, field.TypeString, value)
	}
	if _u.mutation.LogoURLCleared() {
		_spec.ClearField(gameprovider.FieldLogoURL, field.TypeString)
	}
	if value, ok := _u.mutation.SortNo(); ok {
		_spec.SetField(gameprovider.FieldSortNo, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSortNo(); ok {
		_spec.AddField(gameprovider.FieldSortNo, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(gameprovider.FieldStatus, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(gameprovider.FieldStatus, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(gameprovider.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(gameprovider.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{gameprovider.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GameProviderUpdateOne is the builder for updating a single GameProvider entity.
type GameProviderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GameProviderMutation
}

// SetProviderCode sets the "provider_code" field.
func (_u *GameProviderUpdateOne) SetProviderCode(v string) *GameProviderUpdateOne {
	_u.mutation.SetProviderCode(v)
	return _u
}

// SetNillableProviderCode sets the "provider_code" field if the given value is not nil.
func (_u *GameProviderUpdateOne) SetNillableProviderCode(v *string) *GameProviderUpdateOne {
	if v != nil {
		_u.SetProviderCode(*v)
	}
	return _u
}

// SetChannelCode sets the "channel_code" field.
func (_u *GameProviderUpdateOne) SetChannelCode(v string) *GameProviderUpdateOne {
	_u.mutation.SetChannelCode(v)
	return _u
}

// SetNillableChannelCode sets the "channel_code" field if the given value is not nil.
func (_u *GameProviderUpdateOne) SetNillableChannelCode(v *string) *GameProviderUpdateOne {
	if v != nil {
		_u.SetChannelCode(*v)
	}
	return _u
}

// ClearChannelCode clears the value of the "channel_code" field.
func (_u *GameProviderUpdateOne) ClearChannelCode() *GameProviderUpdateOne {
	_u.mutation.ClearChannelCode()
	return _u
}

// SetLogoURL sets the "logo_url" field.
func (_u *GameProviderUpdateOne) SetLogoURL(v string) *GameProviderUpdateOne {
	_u.mutation.SetLogoURL(v)
	return _u
}

// SetNillableLogoURL sets the "logo_url" field if the given value is not nil.
func (_u *GameProviderUpdateOne) SetNillableLogoURL(v *string) *GameProviderUpdateOne {
	if v != nil {
		_u.SetLogoURL(*v)
	}
	return _u
}

// ClearLogoURL clears the value of the "logo_url" field.
func (_u *GameProviderUpdateOne) ClearLogoURL() *GameProviderUpdateOne {
	_u.mutation.ClearLogoURL()
	return _u
}

// SetSortNo sets the "sort_no" field.
func (_u *GameProviderUpdateOne) SetSortNo(v int64) *GameProviderUpdateOne {
	_u.mutation.ResetSortNo()
	_u.mutation.SetSortNo(v)
	return _u
}

// SetNillableSortNo sets the "sort_no" field if the given value is not nil.
func (_u *GameProviderUpdateOne) SetNillableSortNo(v *int64) *GameProviderUpdateOne {
	if v != nil {
		_u.SetSortNo(*v)
	}
	return _u
}

// AddSortNo adds value to the "sort_no" field.
func (_u *GameProviderUpdateOne) AddSortNo(v int64) *GameProviderUpdateOne {
	_u.mutation.AddSortNo(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *GameProviderUpdateOne) SetStatus(v int64) *GameProviderUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *GameProviderUpdateOne) SetNillableStatus(v *int64) *GameProviderUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *GameProviderUpdateOne) AddStatus(v int64) *GameProviderUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *GameProviderUpdateOne) SetCreatedAt(v time.Time) *GameProviderUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *GameProviderUpdateOne) SetNillableCreatedAt(v *time.Time) *GameProviderUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GameProviderUpdateOne) SetUpdatedAt(v time.Time) *GameProviderUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *GameProviderUpdateOne) SetNillableUpdatedAt(v *time.Time) *GameProviderUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the GameProviderMutation object of the builder.
func (_u *GameProviderUpdateOne) Mutation() *GameProviderMutation {
	return _u.mutation
}

// Where appends a list predicates to the GameProviderUpdate builder.
func (_u *GameProviderUpdateOne) Where(ps ...predicate.GameProvider) *GameProviderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GameProviderUpdateOne) Select(field string, fields ...string) *GameProviderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GameProvider entity.
func (_u *GameProviderUpdateOne) Save(ctx context.Context) (*GameProvider, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GameProviderUpdateOne) SaveX(ctx context.Context) *GameProvider {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GameProviderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GameProviderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *GameProviderUpdateOne) sqlSave(ctx context.Context) (_node *GameProvider, err error) {
	_spec := sqlgraph.NewUpdateSpec(gameprovider.Table, gameprovider.Columns, sqlgraph.NewFieldSpec(gameprovider.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GameProvider.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, gameprovider.FieldID)
		for _, f := range fields {
			if !gameprovider.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != gameprovider.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProviderCode(); ok {
		_spec.SetField(gameprovider.FieldProviderCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChannelCode(); ok {
		_spec.SetField(gameprovider.FieldChannelCode, field.TypeString, value)
	}
	if _u.mutation.ChannelCodeCleared() {
		_spec.ClearField(gameprovider.FieldChannelCode, field.TypeString)
	}
	if value, ok := _u.mutation.LogoURL(); ok {
		_spec.SetField(gameprovider.FieldLogoURL, field.TypeString, value)
	}
	if _u.mutation.LogoURLCleared() {
		_spec.ClearField(gameprovider.FieldLogoURL, field.TypeString)
	}
	if value, ok := _u.mutation.SortNo(); ok {
		_spec.SetField(gameprovider.FieldSortNo, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSortNo(); ok {
		_spec.AddField(gameprovider.FieldSortNo, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(gameprovider.FieldStatus, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(gameprovider.FieldStatus, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(gameprovider.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(gameprovider.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &GameProvider{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{gameprovider.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
