// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"oa.98ent.com/p9/operator-game/rpc/ent/gamechannel"
)

// 分站游戏渠道表
type GameChannel struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// ChannelCode holds the value of the "channel_code" field.
	ChannelCode string `json:"channel_code,omitempty"`
	// SortNo holds the value of the "sort_no" field.
	SortNo int64 `json:"sort_no,omitempty"`
	// LoadType holds the value of the "load_type" field.
	LoadType int64 `json:"load_type,omitempty"`
	// Status holds the value of the "status" field.
	Status int64 `json:"status,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GameChannel) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case gamechannel.FieldID, gamechannel.FieldSortNo, gamechannel.FieldLoadType, gamechannel.FieldStatus:
			values[i] = new(sql.NullInt64)
		case gamechannel.FieldChannelCode:
			values[i] = new(sql.NullString)
		case gamechannel.FieldCreatedAt, gamechannel.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GameChannel fields.
func (_m *GameChannel) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case gamechannel.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case gamechannel.FieldChannelCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field channel_code", values[i])
			} else if value.Valid {
				_m.ChannelCode = value.String
			}
		case gamechannel.FieldSortNo:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_no", values[i])
			} else if value.Valid {
				_m.SortNo = value.Int64
			}
		case gamechannel.FieldLoadType:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field load_type", values[i])
			} else if value.Valid {
				_m.LoadType = value.Int64
			}
		case gamechannel.FieldStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.Int64
			}
		case gamechannel.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case gamechannel.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GameChannel.
// This includes values selected through modifiers, order, etc.
func (_m *GameChannel) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this GameChannel.
// Note that you need to call GameChannel.Unwrap() before calling this method if this GameChannel
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GameChannel) Update() *GameChannelUpdateOne {
	return NewGameChannelClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GameChannel entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GameChannel) Unwrap() *GameChannel {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: GameChannel is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GameChannel) String() string {
	var builder strings.Builder
	builder.WriteString("GameChannel(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("channel_code=")
	builder.WriteString(_m.ChannelCode)
	builder.WriteString(", ")
	builder.WriteString("sort_no=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortNo))
	builder.WriteString(", ")
	builder.WriteString("load_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.LoadType))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// GameChannels is a parsable slice of GameChannel.
type GameChannels []*GameChannel
