// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"oa.98ent.com/p9/operator-game/rpc/ent/gamechannel"
	"oa.98ent.com/p9/operator-game/rpc/ent/predicate"
)

// GameChannelUpdate is the builder for updating GameChannel entities.
type GameChannelUpdate struct {
	config
	hooks    []Hook
	mutation *GameChannelMutation
}

// Where appends a list predicates to the GameChannelUpdate builder.
func (_u *GameChannelUpdate) Where(ps ...predicate.GameChannel) *GameChannelUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetChannelCode sets the "channel_code" field.
func (_u *GameChannelUpdate) SetChannelCode(v string) *GameChannelUpdate {
	_u.mutation.SetChannelCode(v)
	return _u
}

// SetNillableChannelCode sets the "channel_code" field if the given value is not nil.
func (_u *GameChannelUpdate) SetNillableChannelCode(v *string) *GameChannelUpdate {
	if v != nil {
		_u.SetChannelCode(*v)
	}
	return _u
}

// SetSortNo sets the "sort_no" field.
func (_u *GameChannelUpdate) SetSortNo(v int64) *GameChannelUpdate {
	_u.mutation.ResetSortNo()
	_u.mutation.SetSortNo(v)
	return _u
}

// SetNillableSortNo sets the "sort_no" field if the given value is not nil.
func (_u *GameChannelUpdate) SetNillableSortNo(v *int64) *GameChannelUpdate {
	if v != nil {
		_u.SetSortNo(*v)
	}
	return _u
}

// AddSortNo adds value to the "sort_no" field.
func (_u *GameChannelUpdate) AddSortNo(v int64) *GameChannelUpdate {
	_u.mutation.AddSortNo(v)
	return _u
}

// SetLoadType sets the "load_type" field.
func (_u *GameChannelUpdate) SetLoadType(v int64) *GameChannelUpdate {
	_u.mutation.ResetLoadType()
	_u.mutation.SetLoadType(v)
	return _u
}

// SetNillableLoadType sets the "load_type" field if the given value is not nil.
func (_u *GameChannelUpdate) SetNillableLoadType(v *int64) *GameChannelUpdate {
	if v != nil {
		_u.SetLoadType(*v)
	}
	return _u
}

// AddLoadType adds value to the "load_type" field.
func (_u *GameChannelUpdate) AddLoadType(v int64) *GameChannelUpdate {
	_u.mutation.AddLoadType(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *GameChannelUpdate) SetStatus(v int64) *GameChannelUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *GameChannelUpdate) SetNillableStatus(v *int64) *GameChannelUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *GameChannelUpdate) AddStatus(v int64) *GameChannelUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *GameChannelUpdate) SetCreatedAt(v time.Time) *GameChannelUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *GameChannelUpdate) SetNillableCreatedAt(v *time.Time) *GameChannelUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GameChannelUpdate) SetUpdatedAt(v time.Time) *GameChannelUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *GameChannelUpdate) SetNillableUpdatedAt(v *time.Time) *GameChannelUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the GameChannelMutation object of the builder.
func (_u *GameChannelUpdate) Mutation() *GameChannelMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GameChannelUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GameChannelUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GameChannelUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GameChannelUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *GameChannelUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(gamechannel.Table, gamechannel.Columns, sqlgraph.NewFieldSpec(gamechannel.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ChannelCode(); ok {
		_spec.SetField(gamechannel.FieldChannelCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortNo(); ok {
		_spec.SetField(gamechannel.FieldSortNo, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSortNo(); ok {
		_spec.AddField(gamechannel.FieldSortNo, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LoadType(); ok {
		_spec.SetField(gamechannel.FieldLoadType, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLoadType(); ok {
		_spec.AddField(gamechannel.FieldLoadType, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(gamechannel.FieldStatus, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(gamechannel.FieldStatus, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(gamechannel.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(gamechannel.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{gamechannel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GameChannelUpdateOne is the builder for updating a single GameChannel entity.
type GameChannelUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GameChannelMutation
}

// SetChannelCode sets the "channel_code" field.
func (_u *GameChannelUpdateOne) SetChannelCode(v string) *GameChannelUpdateOne {
	_u.mutation.SetChannelCode(v)
	return _u
}

// SetNillableChannelCode sets the "channel_code" field if the given value is not nil.
func (_u *GameChannelUpdateOne) SetNillableChannelCode(v *string) *GameChannelUpdateOne {
	if v != nil {
		_u.SetChannelCode(*v)
	}
	return _u
}

// SetSortNo sets the "sort_no" field.
func (_u *GameChannelUpdateOne) SetSortNo(v int64) *GameChannelUpdateOne {
	_u.mutation.ResetSortNo()
	_u.mutation.SetSortNo(v)
	return _u
}

// SetNillableSortNo sets the "sort_no" field if the given value is not nil.
func (_u *GameChannelUpdateOne) SetNillableSortNo(v *int64) *GameChannelUpdateOne {
	if v != nil {
		_u.SetSortNo(*v)
	}
	return _u
}

// AddSortNo adds value to the "sort_no" field.
func (_u *GameChannelUpdateOne) AddSortNo(v int64) *GameChannelUpdateOne {
	_u.mutation.AddSortNo(v)
	return _u
}

// SetLoadType sets the "load_type" field.
func (_u *GameChannelUpdateOne) SetLoadType(v int64) *GameChannelUpdateOne {
	_u.mutation.ResetLoadType()
	_u.mutation.SetLoadType(v)
	return _u
}

// SetNillableLoadType sets the "load_type" field if the given value is not nil.
func (_u *GameChannelUpdateOne) SetNillableLoadType(v *int64) *GameChannelUpdateOne {
	if v != nil {
		_u.SetLoadType(*v)
	}
	return _u
}

// AddLoadType adds value to the "load_type" field.
func (_u *GameChannelUpdateOne) AddLoadType(v int64) *GameChannelUpdateOne {
	_u.mutation.AddLoadType(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *GameChannelUpdateOne) SetStatus(v int64) *GameChannelUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *GameChannelUpdateOne) SetNillableStatus(v *int64) *GameChannelUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *GameChannelUpdateOne) AddStatus(v int64) *GameChannelUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *GameChannelUpdateOne) SetCreatedAt(v time.Time) *GameChannelUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *GameChannelUpdateOne) SetNillableCreatedAt(v *time.Time) *GameChannelUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GameChannelUpdateOne) SetUpdatedAt(v time.Time) *GameChannelUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *GameChannelUpdateOne) SetNillableUpdatedAt(v *time.Time) *GameChannelUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the GameChannelMutation object of the builder.
func (_u *GameChannelUpdateOne) Mutation() *GameChannelMutation {
	return _u.mutation
}

// Where appends a list predicates to the GameChannelUpdate builder.
func (_u *GameChannelUpdateOne) Where(ps ...predicate.GameChannel) *GameChannelUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GameChannelUpdateOne) Select(field string, fields ...string) *GameChannelUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GameChannel entity.
func (_u *GameChannelUpdateOne) Save(ctx context.Context) (*GameChannel, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GameChannelUpdateOne) SaveX(ctx context.Context) *GameChannel {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GameChannelUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GameChannelUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *GameChannelUpdateOne) sqlSave(ctx context.Context) (_node *GameChannel, err error) {
	_spec := sqlgraph.NewUpdateSpec(gamechannel.Table, gamechannel.Columns, sqlgraph.NewFieldSpec(gamechannel.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GameChannel.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, gamechannel.FieldID)
		for _, f := range fields {
			if !gamechannel.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != gamechannel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ChannelCode(); ok {
		_spec.SetField(gamechannel.FieldChannelCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortNo(); ok {
		_spec.SetField(gamechannel.FieldSortNo, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSortNo(); ok {
		_spec.AddField(gamechannel.FieldSortNo, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LoadType(); ok {
		_spec.SetField(gamechannel.FieldLoadType, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLoadType(); ok {
		_spec.AddField(gamechannel.FieldLoadType, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(gamechannel.FieldStatus, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(gamechannel.FieldStatus, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(gamechannel.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(gamechannel.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &GameChannel{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{gamechannel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
