// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"oa.98ent.com/p9/operator-game/rpc/ent/game"
	"oa.98ent.com/p9/operator-game/rpc/ent/gamecategory"
	"oa.98ent.com/p9/operator-game/rpc/ent/gamechannel"
	"oa.98ent.com/p9/operator-game/rpc/ent/gameprovider"
	"oa.98ent.com/p9/operator-game/rpc/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	gameFields := schema.Game{}.Fields()
	_ = gameFields
	// gameDescCreatedAt is the schema descriptor for created_at field.
	gameDescCreatedAt := gameFields[15].Descriptor()
	// game.DefaultCreatedAt holds the default value on creation for the created_at field.
	game.DefaultCreatedAt = gameDescCreatedAt.Default.(func() time.Time)
	// gameDescUpdatedAt is the schema descriptor for updated_at field.
	gameDescUpdatedAt := gameFields[16].Descriptor()
	// game.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	game.DefaultUpdatedAt = gameDescUpdatedAt.Default.(func() time.Time)
	gamecategoryFields := schema.GameCategory{}.Fields()
	_ = gamecategoryFields
	// gamecategoryDescCreatedAt is the schema descriptor for created_at field.
	gamecategoryDescCreatedAt := gamecategoryFields[5].Descriptor()
	// gamecategory.DefaultCreatedAt holds the default value on creation for the created_at field.
	gamecategory.DefaultCreatedAt = gamecategoryDescCreatedAt.Default.(func() time.Time)
	// gamecategoryDescUpdatedAt is the schema descriptor for updated_at field.
	gamecategoryDescUpdatedAt := gamecategoryFields[6].Descriptor()
	// gamecategory.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	gamecategory.DefaultUpdatedAt = gamecategoryDescUpdatedAt.Default.(func() time.Time)
	gamechannelFields := schema.GameChannel{}.Fields()
	_ = gamechannelFields
	// gamechannelDescCreatedAt is the schema descriptor for created_at field.
	gamechannelDescCreatedAt := gamechannelFields[6].Descriptor()
	// gamechannel.DefaultCreatedAt holds the default value on creation for the created_at field.
	gamechannel.DefaultCreatedAt = gamechannelDescCreatedAt.Default.(func() time.Time)
	// gamechannelDescUpdatedAt is the schema descriptor for updated_at field.
	gamechannelDescUpdatedAt := gamechannelFields[7].Descriptor()
	// gamechannel.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	gamechannel.DefaultUpdatedAt = gamechannelDescUpdatedAt.Default.(func() time.Time)
	gameproviderFields := schema.GameProvider{}.Fields()
	_ = gameproviderFields
	// gameproviderDescCreatedAt is the schema descriptor for created_at field.
	gameproviderDescCreatedAt := gameproviderFields[7].Descriptor()
	// gameprovider.DefaultCreatedAt holds the default value on creation for the created_at field.
	gameprovider.DefaultCreatedAt = gameproviderDescCreatedAt.Default.(func() time.Time)
	// gameproviderDescUpdatedAt is the schema descriptor for updated_at field.
	gameproviderDescUpdatedAt := gameproviderFields[8].Descriptor()
	// gameprovider.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	gameprovider.DefaultUpdatedAt = gameproviderDescUpdatedAt.Default.(func() time.Time)
}
