FROM alpine:3.22

# 镜像作者
ARG AUTHOR="p9.work@gmail.com"

LABEL org.opencontainers.image.authors=${AUTHOR}

WORKDIR /app

# 设置容器时区并安装运行依赖
ENV TZ=Asia/Shanghai
RUN apk add --no-cache tzdata ca-certificates

# 复制API可执行文件
COPY ./node_dispatch_api ./
RUN chmod +x ./node_dispatch_api

# 复制API配置文件
COPY ./api/etc/node_dispatch.yaml ./etc/

# API服务端口
EXPOSE 28001

ENTRYPOINT ["./node_dispatch_api"]
CMD ["-f", "etc/node_dispatch.yaml"]