FROM alpine:3.22

# 镜像作者
ARG AUTHOR="p9.work@gmail.com"

LABEL org.opencontainers.image.authors=${AUTHOR}

WORKDIR /app

# 设置容器时区并安装运行依赖
ENV TZ=Asia/Shanghai
RUN apk add --no-cache tzdata ca-certificates

# 复制RPC可执行文件
COPY ./node_dispatch_rpc ./
RUN chmod +x ./node_dispatch_rpc

# 复制RPC配置文件
COPY ./rpc/etc/node_dispatch.yaml ./etc/

# RPC服务端口
EXPOSE 29001

# WebSocket服务端口
EXPOSE 28002

ENTRYPOINT ["./node_dispatch_rpc"]
CMD ["-f", "etc/node_dispatch.yaml"]