// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: operator_game.proto

package server

import (
	"context"

	"oa.98ent.com/p9/operator-game/rpc/internal/logic/gameservice"
	"oa.98ent.com/p9/operator-game/rpc/internal/svc"
	"oa.98ent.com/p9/operator-game/rpc/pb/operator_game"
)

type GameServiceServer struct {
	svcCtx *svc.ServiceContext
	operator_game.UnimplementedGameServiceServer
}

func NewGameServiceServer(svcCtx *svc.ServiceContext) *GameServiceServer {
	return &GameServiceServer{
		svcCtx: svcCtx,
	}
}

// 获取游戏列表
func (s *GameServiceServer) GetGameList(ctx context.Context, in *operator_game.GetGameListRequest) (*operator_game.GetGameListResp, error) {
	l := gameservicelogic.NewGetGameListLogic(ctx, s.svcCtx)
	return l.GetGameList(in)
}

// 获取单个游戏详情
func (s *GameServiceServer) GetGame(ctx context.Context, in *operator_game.GetGameRequest) (*operator_game.GetGameResp, error) {
	l := gameservicelogic.NewGetGameLogic(ctx, s.svcCtx)
	return l.GetGame(in)
}

// 更新游戏
func (s *GameServiceServer) UpdateGame(ctx context.Context, in *operator_game.UpdateGameRequest) (*operator_game.UpdateGameResp, error) {
	l := gameservicelogic.NewUpdateGameLogic(ctx, s.svcCtx)
	return l.UpdateGame(in)
}
