# API服务配置
Name: node-dispatch-api          # API服务名称
Host: 0.0.0.0                    # API监听地址
Port: 28001                      # API监听端口
Mode: test                       # 运行模式

# Node Dispatch RPC配置
NodeDispatchRpc:
  Etcd:
    Hosts:
      - 192.168.0.15:2379        # Etcd地址
    Key: node-dispatch-rpc       # RPC服务注册Key

# Core RPC配置
CoreRpc:
  Endpoints:
    - platform-core-rpc:19000    # Core RPC地址
  NonBlock: true                 # 非阻塞连接
  Timeout: 10000                 # 请求超时时间, 毫秒

# 国际化配置
I18n:
  DefaultLanguage: zh-CN         # 默认语言

# 链路追踪
Telemetry:
  Name: node-dispatch-api
  Endpoint: 192.168.0.15:4317
  Sampler: 1.0
  Batcher: otlpgrpc