// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: types/platform_operator_operator.proto

package operatorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 分站信息
type OperatorInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分站ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 分站业务编码
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	// 分站名称
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// 时区编码
	TimezoneCode string `protobuf:"bytes,4,opt,name=timezone_code,json=timezoneCode,proto3" json:"timezone_code,omitempty"`
	// 结算币种编码
	SettlementCurrencyCode string `protobuf:"bytes,5,opt,name=settlement_currency_code,json=settlementCurrencyCode,proto3" json:"settlement_currency_code,omitempty"`
	// 创建状态: 1草稿, 2已完成
	CreationStatus int64 `protobuf:"varint,6,opt,name=creation_status,json=creationStatus,proto3" json:"creation_status,omitempty"`
	// 发布状态: 1未发布, 2发布中, 3已发布, 4发布失败
	PublishStatus int64 `protobuf:"varint,7,opt,name=publish_status,json=publishStatus,proto3" json:"publish_status,omitempty"`
	// 分站状态: 1正常, 2暂停, 3关闭
	Status int64 `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	// 内部备注
	Remark *string `protobuf:"bytes,9,opt,name=remark,proto3,oneof" json:"remark,omitempty"`
	// 首次发布成功时间, Unix毫秒时间戳
	PublishedAt *int64 `protobuf:"varint,10,opt,name=published_at,json=publishedAt,proto3,oneof" json:"published_at,omitempty"`
	// 创建时间, Unix毫秒时间戳
	CreatedAt int64 `protobuf:"varint,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// 更新时间, Unix毫秒时间戳
	UpdatedAt     int64 `protobuf:"varint,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperatorInfo) Reset() {
	*x = OperatorInfo{}
	mi := &file_types_platform_operator_operator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatorInfo) ProtoMessage() {}

func (x *OperatorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_types_platform_operator_operator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatorInfo.ProtoReflect.Descriptor instead.
func (*OperatorInfo) Descriptor() ([]byte, []int) {
	return file_types_platform_operator_operator_proto_rawDescGZIP(), []int{0}
}

func (x *OperatorInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OperatorInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *OperatorInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OperatorInfo) GetTimezoneCode() string {
	if x != nil {
		return x.TimezoneCode
	}
	return ""
}

func (x *OperatorInfo) GetSettlementCurrencyCode() string {
	if x != nil {
		return x.SettlementCurrencyCode
	}
	return ""
}

func (x *OperatorInfo) GetCreationStatus() int64 {
	if x != nil {
		return x.CreationStatus
	}
	return 0
}

func (x *OperatorInfo) GetPublishStatus() int64 {
	if x != nil {
		return x.PublishStatus
	}
	return 0
}

func (x *OperatorInfo) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *OperatorInfo) GetRemark() string {
	if x != nil && x.Remark != nil {
		return *x.Remark
	}
	return ""
}

func (x *OperatorInfo) GetPublishedAt() int64 {
	if x != nil && x.PublishedAt != nil {
		return *x.PublishedAt
	}
	return 0
}

func (x *OperatorInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *OperatorInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// 创建分站请求
type CreateOperatorRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分站名称
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// 时区编码
	TimezoneCode string `protobuf:"bytes,2,opt,name=timezone_code,json=timezoneCode,proto3" json:"timezone_code,omitempty"`
	// 结算币种编码
	SettlementCurrencyCode string `protobuf:"bytes,3,opt,name=settlement_currency_code,json=settlementCurrencyCode,proto3" json:"settlement_currency_code,omitempty"`
	// 分站状态: 1正常, 2暂停, 3关闭
	Status *int64 `protobuf:"varint,4,opt,name=status,proto3,oneof" json:"status,omitempty"`
	// 内部备注
	Remark        *string `protobuf:"bytes,5,opt,name=remark,proto3,oneof" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOperatorRequest) Reset() {
	*x = CreateOperatorRequest{}
	mi := &file_types_platform_operator_operator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOperatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOperatorRequest) ProtoMessage() {}

func (x *CreateOperatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_platform_operator_operator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOperatorRequest.ProtoReflect.Descriptor instead.
func (*CreateOperatorRequest) Descriptor() ([]byte, []int) {
	return file_types_platform_operator_operator_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOperatorRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateOperatorRequest) GetTimezoneCode() string {
	if x != nil {
		return x.TimezoneCode
	}
	return ""
}

func (x *CreateOperatorRequest) GetSettlementCurrencyCode() string {
	if x != nil {
		return x.SettlementCurrencyCode
	}
	return ""
}

func (x *CreateOperatorRequest) GetStatus() int64 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *CreateOperatorRequest) GetRemark() string {
	if x != nil && x.Remark != nil {
		return *x.Remark
	}
	return ""
}

// 创建分站响应
type CreateOperatorResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分站ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 分站业务编码
	Code          string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOperatorResponse) Reset() {
	*x = CreateOperatorResponse{}
	mi := &file_types_platform_operator_operator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOperatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOperatorResponse) ProtoMessage() {}

func (x *CreateOperatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_platform_operator_operator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOperatorResponse.ProtoReflect.Descriptor instead.
func (*CreateOperatorResponse) Descriptor() ([]byte, []int) {
	return file_types_platform_operator_operator_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOperatorResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateOperatorResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// 修改分站请求
type UpdateOperatorRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分站ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 分站名称
	Name *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// 时区编码
	TimezoneCode *string `protobuf:"bytes,3,opt,name=timezone_code,json=timezoneCode,proto3,oneof" json:"timezone_code,omitempty"`
	// 结算币种编码
	SettlementCurrencyCode *string `protobuf:"bytes,4,opt,name=settlement_currency_code,json=settlementCurrencyCode,proto3,oneof" json:"settlement_currency_code,omitempty"`
	// 分站状态: 1正常, 2暂停, 3关闭
	Status *int64 `protobuf:"varint,5,opt,name=status,proto3,oneof" json:"status,omitempty"`
	// 内部备注
	Remark        *string `protobuf:"bytes,6,opt,name=remark,proto3,oneof" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOperatorRequest) Reset() {
	*x = UpdateOperatorRequest{}
	mi := &file_types_platform_operator_operator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOperatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOperatorRequest) ProtoMessage() {}

func (x *UpdateOperatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_platform_operator_operator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOperatorRequest.ProtoReflect.Descriptor instead.
func (*UpdateOperatorRequest) Descriptor() ([]byte, []int) {
	return file_types_platform_operator_operator_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateOperatorRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateOperatorRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateOperatorRequest) GetTimezoneCode() string {
	if x != nil && x.TimezoneCode != nil {
		return *x.TimezoneCode
	}
	return ""
}

func (x *UpdateOperatorRequest) GetSettlementCurrencyCode() string {
	if x != nil && x.SettlementCurrencyCode != nil {
		return *x.SettlementCurrencyCode
	}
	return ""
}

func (x *UpdateOperatorRequest) GetStatus() int64 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *UpdateOperatorRequest) GetRemark() string {
	if x != nil && x.Remark != nil {
		return *x.Remark
	}
	return ""
}

// 修改分站响应
type UpdateOperatorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOperatorResponse) Reset() {
	*x = UpdateOperatorResponse{}
	mi := &file_types_platform_operator_operator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOperatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOperatorResponse) ProtoMessage() {}

func (x *UpdateOperatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_platform_operator_operator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOperatorResponse.ProtoReflect.Descriptor instead.
func (*UpdateOperatorResponse) Descriptor() ([]byte, []int) {
	return file_types_platform_operator_operator_proto_rawDescGZIP(), []int{4}
}

// 获取分站请求
type GetOperatorRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分站ID
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperatorRequest) Reset() {
	*x = GetOperatorRequest{}
	mi := &file_types_platform_operator_operator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperatorRequest) ProtoMessage() {}

func (x *GetOperatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_platform_operator_operator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperatorRequest.ProtoReflect.Descriptor instead.
func (*GetOperatorRequest) Descriptor() ([]byte, []int) {
	return file_types_platform_operator_operator_proto_rawDescGZIP(), []int{5}
}

func (x *GetOperatorRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 获取分站响应
type GetOperatorResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分站信息
	Operator      *OperatorInfo `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperatorResponse) Reset() {
	*x = GetOperatorResponse{}
	mi := &file_types_platform_operator_operator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperatorResponse) ProtoMessage() {}

func (x *GetOperatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_platform_operator_operator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperatorResponse.ProtoReflect.Descriptor instead.
func (*GetOperatorResponse) Descriptor() ([]byte, []int) {
	return file_types_platform_operator_operator_proto_rawDescGZIP(), []int{6}
}

func (x *GetOperatorResponse) GetOperator() *OperatorInfo {
	if x != nil {
		return x.Operator
	}
	return nil
}

// 获取分站列表请求
type ListOperatorsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 页码, 从1开始
	Page int64 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	// 每页数量
	PageSize int64 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// 搜索关键字, 匹配分站编码或名称
	Keyword *string `protobuf:"bytes,3,opt,name=keyword,proto3,oneof" json:"keyword,omitempty"`
	// 创建状态: 1草稿, 2已完成
	CreationStatus *int64 `protobuf:"varint,4,opt,name=creation_status,json=creationStatus,proto3,oneof" json:"creation_status,omitempty"`
	// 发布状态: 1未发布, 2发布中, 3已发布, 4发布失败
	PublishStatus *int64 `protobuf:"varint,5,opt,name=publish_status,json=publishStatus,proto3,oneof" json:"publish_status,omitempty"`
	// 分站状态: 1正常, 2暂停, 3关闭
	Status        *int64 `protobuf:"varint,6,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOperatorsRequest) Reset() {
	*x = ListOperatorsRequest{}
	mi := &file_types_platform_operator_operator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOperatorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOperatorsRequest) ProtoMessage() {}

func (x *ListOperatorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_platform_operator_operator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOperatorsRequest.ProtoReflect.Descriptor instead.
func (*ListOperatorsRequest) Descriptor() ([]byte, []int) {
	return file_types_platform_operator_operator_proto_rawDescGZIP(), []int{7}
}

func (x *ListOperatorsRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListOperatorsRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListOperatorsRequest) GetKeyword() string {
	if x != nil && x.Keyword != nil {
		return *x.Keyword
	}
	return ""
}

func (x *ListOperatorsRequest) GetCreationStatus() int64 {
	if x != nil && x.CreationStatus != nil {
		return *x.CreationStatus
	}
	return 0
}

func (x *ListOperatorsRequest) GetPublishStatus() int64 {
	if x != nil && x.PublishStatus != nil {
		return *x.PublishStatus
	}
	return 0
}

func (x *ListOperatorsRequest) GetStatus() int64 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

// 获取分站列表响应
type ListOperatorsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 数据总数
	Total int64 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	// 分站列表
	List          []*OperatorInfo `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOperatorsResponse) Reset() {
	*x = ListOperatorsResponse{}
	mi := &file_types_platform_operator_operator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOperatorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOperatorsResponse) ProtoMessage() {}

func (x *ListOperatorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_platform_operator_operator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOperatorsResponse.ProtoReflect.Descriptor instead.
func (*ListOperatorsResponse) Descriptor() ([]byte, []int) {
	return file_types_platform_operator_operator_proto_rawDescGZIP(), []int{8}
}

func (x *ListOperatorsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListOperatorsResponse) GetList() []*OperatorInfo {
	if x != nil {
		return x.List
	}
	return nil
}

// 完成分站创建请求
type CompleteOperatorRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分站ID
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteOperatorRequest) Reset() {
	*x = CompleteOperatorRequest{}
	mi := &file_types_platform_operator_operator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteOperatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteOperatorRequest) ProtoMessage() {}

func (x *CompleteOperatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_platform_operator_operator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteOperatorRequest.ProtoReflect.Descriptor instead.
func (*CompleteOperatorRequest) Descriptor() ([]byte, []int) {
	return file_types_platform_operator_operator_proto_rawDescGZIP(), []int{9}
}

func (x *CompleteOperatorRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 完成分站创建响应
type CompleteOperatorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteOperatorResponse) Reset() {
	*x = CompleteOperatorResponse{}
	mi := &file_types_platform_operator_operator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteOperatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteOperatorResponse) ProtoMessage() {}

func (x *CompleteOperatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_platform_operator_operator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteOperatorResponse.ProtoReflect.Descriptor instead.
func (*CompleteOperatorResponse) Descriptor() ([]byte, []int) {
	return file_types_platform_operator_operator_proto_rawDescGZIP(), []int{10}
}

// 发布分站请求
type PublishOperatorRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分站ID
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishOperatorRequest) Reset() {
	*x = PublishOperatorRequest{}
	mi := &file_types_platform_operator_operator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishOperatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishOperatorRequest) ProtoMessage() {}

func (x *PublishOperatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_platform_operator_operator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishOperatorRequest.ProtoReflect.Descriptor instead.
func (*PublishOperatorRequest) Descriptor() ([]byte, []int) {
	return file_types_platform_operator_operator_proto_rawDescGZIP(), []int{11}
}

func (x *PublishOperatorRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 发布分站响应
type PublishOperatorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishOperatorResponse) Reset() {
	*x = PublishOperatorResponse{}
	mi := &file_types_platform_operator_operator_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishOperatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishOperatorResponse) ProtoMessage() {}

func (x *PublishOperatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_platform_operator_operator_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishOperatorResponse.ProtoReflect.Descriptor instead.
func (*PublishOperatorResponse) Descriptor() ([]byte, []int) {
	return file_types_platform_operator_operator_proto_rawDescGZIP(), []int{12}
}

// 同步分站发布状态请求
type SyncPublishStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分站ID
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncPublishStatusRequest) Reset() {
	*x = SyncPublishStatusRequest{}
	mi := &file_types_platform_operator_operator_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncPublishStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncPublishStatusRequest) ProtoMessage() {}

func (x *SyncPublishStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_platform_operator_operator_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncPublishStatusRequest.ProtoReflect.Descriptor instead.
func (*SyncPublishStatusRequest) Descriptor() ([]byte, []int) {
	return file_types_platform_operator_operator_proto_rawDescGZIP(), []int{13}
}

func (x *SyncPublishStatusRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 同步分站发布状态响应
type SyncPublishStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分站ID
	OperatorId int64 `protobuf:"varint,1,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	// 分站业务编码
	OperatorCode string `protobuf:"bytes,2,opt,name=operator_code,json=operatorCode,proto3" json:"operator_code,omitempty"`
	// 发布状态: 2发布中, 3已发布, 4发布失败
	PublishStatus int64 `protobuf:"varint,3,opt,name=publish_status,json=publishStatus,proto3" json:"publish_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncPublishStatusResponse) Reset() {
	*x = SyncPublishStatusResponse{}
	mi := &file_types_platform_operator_operator_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncPublishStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncPublishStatusResponse) ProtoMessage() {}

func (x *SyncPublishStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_platform_operator_operator_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncPublishStatusResponse.ProtoReflect.Descriptor instead.
func (*SyncPublishStatusResponse) Descriptor() ([]byte, []int) {
	return file_types_platform_operator_operator_proto_rawDescGZIP(), []int{14}
}

func (x *SyncPublishStatusResponse) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

func (x *SyncPublishStatusResponse) GetOperatorCode() string {
	if x != nil {
		return x.OperatorCode
	}
	return ""
}

func (x *SyncPublishStatusResponse) GetPublishStatus() int64 {
	if x != nil {
		return x.PublishStatus
	}
	return 0
}

// 处理分站发布结果请求
type HandlePublishResultRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 调度任务编号
	TaskNo        string `protobuf:"bytes,1,opt,name=task_no,json=taskNo,proto3" json:"task_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandlePublishResultRequest) Reset() {
	*x = HandlePublishResultRequest{}
	mi := &file_types_platform_operator_operator_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandlePublishResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandlePublishResultRequest) ProtoMessage() {}

func (x *HandlePublishResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_platform_operator_operator_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandlePublishResultRequest.ProtoReflect.Descriptor instead.
func (*HandlePublishResultRequest) Descriptor() ([]byte, []int) {
	return file_types_platform_operator_operator_proto_rawDescGZIP(), []int{15}
}

func (x *HandlePublishResultRequest) GetTaskNo() string {
	if x != nil {
		return x.TaskNo
	}
	return ""
}

// 处理分站发布结果响应
type HandlePublishResultResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分站ID
	OperatorId int64 `protobuf:"varint,1,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	// 分站业务编码
	OperatorCode string `protobuf:"bytes,2,opt,name=operator_code,json=operatorCode,proto3" json:"operator_code,omitempty"`
	// 发布状态: 3已发布, 4发布失败
	PublishStatus int64 `protobuf:"varint,3,opt,name=publish_status,json=publishStatus,proto3" json:"publish_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandlePublishResultResponse) Reset() {
	*x = HandlePublishResultResponse{}
	mi := &file_types_platform_operator_operator_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandlePublishResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandlePublishResultResponse) ProtoMessage() {}

func (x *HandlePublishResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_platform_operator_operator_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandlePublishResultResponse.ProtoReflect.Descriptor instead.
func (*HandlePublishResultResponse) Descriptor() ([]byte, []int) {
	return file_types_platform_operator_operator_proto_rawDescGZIP(), []int{16}
}

func (x *HandlePublishResultResponse) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

func (x *HandlePublishResultResponse) GetOperatorCode() string {
	if x != nil {
		return x.OperatorCode
	}
	return ""
}

func (x *HandlePublishResultResponse) GetPublishStatus() int64 {
	if x != nil {
		return x.PublishStatus
	}
	return 0
}

// 删除分站请求
type DeleteOperatorRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分站ID
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOperatorRequest) Reset() {
	*x = DeleteOperatorRequest{}
	mi := &file_types_platform_operator_operator_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOperatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOperatorRequest) ProtoMessage() {}

func (x *DeleteOperatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_platform_operator_operator_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOperatorRequest.ProtoReflect.Descriptor instead.
func (*DeleteOperatorRequest) Descriptor() ([]byte, []int) {
	return file_types_platform_operator_operator_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteOperatorRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 删除分站响应
type DeleteOperatorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOperatorResponse) Reset() {
	*x = DeleteOperatorResponse{}
	mi := &file_types_platform_operator_operator_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOperatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOperatorResponse) ProtoMessage() {}

func (x *DeleteOperatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_platform_operator_operator_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOperatorResponse.ProtoReflect.Descriptor instead.
func (*DeleteOperatorResponse) Descriptor() ([]byte, []int) {
	return file_types_platform_operator_operator_proto_rawDescGZIP(), []int{18}
}

// 分站初始化基础信息
type InitializationInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分站全局唯一业务编码
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// 分站名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// IANA 时区编码
	TimezoneCode string `protobuf:"bytes,3,opt,name=timezone_code,json=timezoneCode,proto3" json:"timezone_code,omitempty"`
	// 结算币种编码
	SettlementCurrencyCode string `protobuf:"bytes,4,opt,name=settlement_currency_code,json=settlementCurrencyCode,proto3" json:"settlement_currency_code,omitempty"`
	// 分站状态: 1正常, 2暂停, 3关闭
	Status        int64 `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializationInfo) Reset() {
	*x = InitializationInfo{}
	mi := &file_types_platform_operator_operator_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializationInfo) ProtoMessage() {}

func (x *InitializationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_types_platform_operator_operator_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializationInfo.ProtoReflect.Descriptor instead.
func (*InitializationInfo) Descriptor() ([]byte, []int) {
	return file_types_platform_operator_operator_proto_rawDescGZIP(), []int{19}
}

func (x *InitializationInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *InitializationInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InitializationInfo) GetTimezoneCode() string {
	if x != nil {
		return x.TimezoneCode
	}
	return ""
}

func (x *InitializationInfo) GetSettlementCurrencyCode() string {
	if x != nil {
		return x.SettlementCurrencyCode
	}
	return ""
}

func (x *InitializationInfo) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 分站初始化域名信息
type DomainInitializationInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 域名, 不包含协议和端口
	DomainName string `protobuf:"bytes,1,opt,name=domain_name,json=domainName,proto3" json:"domain_name,omitempty"`
	// 域名类型: 1分站后台, 2代理后台, 3会员H5
	DomainType    int64 `protobuf:"varint,2,opt,name=domain_type,json=domainType,proto3" json:"domain_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainInitializationInfo) Reset() {
	*x = DomainInitializationInfo{}
	mi := &file_types_platform_operator_operator_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainInitializationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainInitializationInfo) ProtoMessage() {}

func (x *DomainInitializationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_types_platform_operator_operator_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainInitializationInfo.ProtoReflect.Descriptor instead.
func (*DomainInitializationInfo) Descriptor() ([]byte, []int) {
	return file_types_platform_operator_operator_proto_rawDescGZIP(), []int{20}
}

func (x *DomainInitializationInfo) GetDomainName() string {
	if x != nil {
		return x.DomainName
	}
	return ""
}

func (x *DomainInitializationInfo) GetDomainType() int64 {
	if x != nil {
		return x.DomainType
	}
	return 0
}

type AdminInitializationInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 管理后台用户名
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// 管理后台密码
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	// 管理后台显示名称
	DisplayName   string `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminInitializationInfo) Reset() {
	*x = AdminInitializationInfo{}
	mi := &file_types_platform_operator_operator_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminInitializationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminInitializationInfo) ProtoMessage() {}

func (x *AdminInitializationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_types_platform_operator_operator_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminInitializationInfo.ProtoReflect.Descriptor instead.
func (*AdminInitializationInfo) Descriptor() ([]byte, []int) {
	return file_types_platform_operator_operator_proto_rawDescGZIP(), []int{21}
}

func (x *AdminInitializationInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AdminInitializationInfo) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AdminInitializationInfo) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

// 获取分站初始化数据请求
type GetInitializationDataRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分站全局唯一业务编码
	OperatorCode  string `protobuf:"bytes,1,opt,name=operator_code,json=operatorCode,proto3" json:"operator_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInitializationDataRequest) Reset() {
	*x = GetInitializationDataRequest{}
	mi := &file_types_platform_operator_operator_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInitializationDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInitializationDataRequest) ProtoMessage() {}

func (x *GetInitializationDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_platform_operator_operator_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInitializationDataRequest.ProtoReflect.Descriptor instead.
func (*GetInitializationDataRequest) Descriptor() ([]byte, []int) {
	return file_types_platform_operator_operator_proto_rawDescGZIP(), []int{22}
}

func (x *GetInitializationDataRequest) GetOperatorCode() string {
	if x != nil {
		return x.OperatorCode
	}
	return ""
}

// 获取分站初始化数据响应
type GetInitializationDataResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分站基础信息
	Operator *InitializationInfo `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	// 当前启用域名
	Domains []*DomainInitializationInfo `protobuf:"bytes,2,rep,name=domains,proto3" json:"domains,omitempty"`
	// 当前分配的语言编码
	LanguageCodes []string `protobuf:"bytes,3,rep,name=language_codes,json=languageCodes,proto3" json:"language_codes,omitempty"`
	// 当前分配的经营地区编码
	RegionCodes []string `protobuf:"bytes,4,rep,name=region_codes,json=regionCodes,proto3" json:"region_codes,omitempty"`
	// 当前分配的代理子线路编码
	AgentLineCodes []string `protobuf:"bytes,5,rep,name=agent_line_codes,json=agentLineCodes,proto3" json:"agent_line_codes,omitempty"`
	// 当前分配的管理后台信息
	Admins        []*AdminInitializationInfo `protobuf:"bytes,6,rep,name=admins,proto3" json:"admins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInitializationDataResponse) Reset() {
	*x = GetInitializationDataResponse{}
	mi := &file_types_platform_operator_operator_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInitializationDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInitializationDataResponse) ProtoMessage() {}

func (x *GetInitializationDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_platform_operator_operator_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInitializationDataResponse.ProtoReflect.Descriptor instead.
func (*GetInitializationDataResponse) Descriptor() ([]byte, []int) {
	return file_types_platform_operator_operator_proto_rawDescGZIP(), []int{23}
}

func (x *GetInitializationDataResponse) GetOperator() *InitializationInfo {
	if x != nil {
		return x.Operator
	}
	return nil
}

func (x *GetInitializationDataResponse) GetDomains() []*DomainInitializationInfo {
	if x != nil {
		return x.Domains
	}
	return nil
}

func (x *GetInitializationDataResponse) GetLanguageCodes() []string {
	if x != nil {
		return x.LanguageCodes
	}
	return nil
}

func (x *GetInitializationDataResponse) GetRegionCodes() []string {
	if x != nil {
		return x.RegionCodes
	}
	return nil
}

func (x *GetInitializationDataResponse) GetAgentLineCodes() []string {
	if x != nil {
		return x.AgentLineCodes
	}
	return nil
}

func (x *GetInitializationDataResponse) GetAdmins() []*AdminInitializationInfo {
	if x != nil {
		return x.Admins
	}
	return nil
}

var File_types_platform_operator_operator_proto protoreflect.FileDescriptor

var file_types_platform_operator_operator_proto_rawDesc = string([]byte{
	0x0a, 0x26, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x5f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f,
	0x72, 0x6d, 0x5f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x6f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x22, 0xac, 0x03, 0x0a, 0x0c, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a,
	0x0d, 0x74, 0x69, 0x6d, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x69, 0x6d, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x38, 0x0a, 0x18, 0x73, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x5f, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x16, 0x73, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x27, 0x0a, 0x0f,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68,
	0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x1b, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x88, 0x01,
	0x01, 0x12, 0x26, 0x0a, 0x0c, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x48, 0x01, 0x52, 0x0b, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x65, 0x64, 0x41, 0x74, 0x88, 0x01, 0x01, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x72, 0x65, 0x6d, 0x61,
	0x72, 0x6b, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64,
	0x5f, 0x61, 0x74, 0x22, 0xda, 0x01, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x23, 0x0a, 0x0d, 0x74, 0x69, 0x6d, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x5f, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x69, 0x6d, 0x65, 0x7a, 0x6f,
	0x6e, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x38, 0x0a, 0x18, 0x73, 0x65, 0x74, 0x74, 0x6c, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x5f, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x16, 0x73, 0x65, 0x74, 0x74, 0x6c, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x1b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a,
	0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52,
	0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b,
	0x22, 0x3c, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0xb1,
	0x02, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x88, 0x01,
	0x01, 0x12, 0x28, 0x0a, 0x0d, 0x74, 0x69, 0x6d, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x5f, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x0c, 0x74, 0x69, 0x6d, 0x65,
	0x7a, 0x6f, 0x6e, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x88, 0x01, 0x01, 0x12, 0x3d, 0x0a, 0x18, 0x73,
	0x65, 0x74, 0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x63, 0x79, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52,
	0x16, 0x73, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x63, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x48, 0x03, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72,
	0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48, 0x04, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72,
	0x6b, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x10, 0x0a,
	0x0e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x42,
	0x1b, 0x0a, 0x19, 0x5f, 0x73, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x42, 0x09, 0x0a, 0x07,
	0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x72, 0x65, 0x6d, 0x61,
	0x72, 0x6b, 0x22, 0x18, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x24, 0x0a, 0x12,
	0x47, 0x65, 0x74, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x5b, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x08, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x70, 0x6c,
	0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x5f,
	0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x22,
	0x9b, 0x02, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1d, 0x0a, 0x07, 0x6b, 0x65, 0x79,
	0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x6b, 0x65,
	0x79, 0x77, 0x6f, 0x72, 0x64, 0x88, 0x01, 0x01, 0x12, 0x2c, 0x0a, 0x0f, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x48, 0x01, 0x52, 0x0e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x88, 0x01, 0x01, 0x12, 0x2a, 0x0a, 0x0e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73,
	0x68, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x48, 0x02,
	0x52, 0x0d, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x88,
	0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x03, 0x48, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x88, 0x01, 0x01, 0x42,
	0x0a, 0x0a, 0x08, 0x5f, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x42, 0x12, 0x0a, 0x10, 0x5f,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42,
	0x11, 0x0a, 0x0f, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x5f, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x6b, 0x0a,
	0x15, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x3c, 0x0a, 0x04,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x70, 0x6c, 0x61,
	0x74, 0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x6f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x29, 0x0a, 0x17, 0x43, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x1a, 0x0a, 0x18, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74,
	0x65, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x28, 0x0a, 0x16, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x19, 0x0a, 0x17, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2a, 0x0a, 0x18, 0x53, 0x79, 0x6e, 0x63, 0x50, 0x75,
	0x62, 0x6c, 0x69, 0x73, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x88, 0x01, 0x0a, 0x19, 0x53, 0x79, 0x6e, 0x63, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1f, 0x0a, 0x0b, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x49,
	0x64, 0x12, 0x23, 0x0a, 0x0d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73,
	0x68, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x35, 0x0a,
	0x1a, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x74,
	0x61, 0x73, 0x6b, 0x5f, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61,
	0x73, 0x6b, 0x4e, 0x6f, 0x22, 0x8a, 0x01, 0x0a, 0x1b, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f,
	0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x73, 0x68, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0d, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x22, 0x27, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x18, 0x0a, 0x16, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0xb3, 0x01, 0x0a, 0x12, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c,
	0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x74, 0x69, 0x6d, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x5f,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x69, 0x6d, 0x65,
	0x7a, 0x6f, 0x6e, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x38, 0x0a, 0x18, 0x73, 0x65, 0x74, 0x74,
	0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x5f,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x16, 0x73, 0x65, 0x74, 0x74,
	0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x5c, 0x0a, 0x18, 0x44, 0x6f,
	0x6d, 0x61, 0x69, 0x6e, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x6f, 0x6d,
	0x61, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x64, 0x6f,
	0x6d, 0x61, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x22, 0x74, 0x0a, 0x17, 0x41, 0x64, 0x6d, 0x69,
	0x6e, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x64,
	0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x43,
	0x0a, 0x1c, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23,
	0x0a, 0x0d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x22, 0xfc, 0x02, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x69, 0x74, 0x69,
	0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f,
	0x72, 0x6d, 0x5f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x6f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f,
	0x72, 0x12, 0x4e, 0x0a, 0x07, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x34, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x6f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e,
	0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e,
	0x73, 0x12, 0x25, 0x0a, 0x0e, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x5f, 0x63, 0x6f,
	0x64, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x6c, 0x61, 0x6e, 0x67, 0x75,
	0x61, 0x67, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x67, 0x69,
	0x6f, 0x6e, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b,
	0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x28, 0x0a, 0x10, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x5f, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x6e, 0x65,
	0x43, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x4b, 0x0a, 0x06, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x73, 0x18,
	0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x5f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x6f, 0x72, 0x2e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69,
	0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x73, 0x42, 0x49, 0x5a, 0x47, 0x6f, 0x61, 0x2e, 0x39, 0x38, 0x65, 0x6e, 0x74, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x70, 0x39, 0x2f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2d, 0x6f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x2f, 0x70,
	0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x72,
	0x70, 0x63, 0x2f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_types_platform_operator_operator_proto_rawDescOnce sync.Once
	file_types_platform_operator_operator_proto_rawDescData []byte
)

func file_types_platform_operator_operator_proto_rawDescGZIP() []byte {
	file_types_platform_operator_operator_proto_rawDescOnce.Do(func() {
		file_types_platform_operator_operator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_platform_operator_operator_proto_rawDesc), len(file_types_platform_operator_operator_proto_rawDesc)))
	})
	return file_types_platform_operator_operator_proto_rawDescData
}

var file_types_platform_operator_operator_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_types_platform_operator_operator_proto_goTypes = []any{
	(*OperatorInfo)(nil),                  // 0: platform_operator_operator.OperatorInfo
	(*CreateOperatorRequest)(nil),         // 1: platform_operator_operator.CreateOperatorRequest
	(*CreateOperatorResponse)(nil),        // 2: platform_operator_operator.CreateOperatorResponse
	(*UpdateOperatorRequest)(nil),         // 3: platform_operator_operator.UpdateOperatorRequest
	(*UpdateOperatorResponse)(nil),        // 4: platform_operator_operator.UpdateOperatorResponse
	(*GetOperatorRequest)(nil),            // 5: platform_operator_operator.GetOperatorRequest
	(*GetOperatorResponse)(nil),           // 6: platform_operator_operator.GetOperatorResponse
	(*ListOperatorsRequest)(nil),          // 7: platform_operator_operator.ListOperatorsRequest
	(*ListOperatorsResponse)(nil),         // 8: platform_operator_operator.ListOperatorsResponse
	(*CompleteOperatorRequest)(nil),       // 9: platform_operator_operator.CompleteOperatorRequest
	(*CompleteOperatorResponse)(nil),      // 10: platform_operator_operator.CompleteOperatorResponse
	(*PublishOperatorRequest)(nil),        // 11: platform_operator_operator.PublishOperatorRequest
	(*PublishOperatorResponse)(nil),       // 12: platform_operator_operator.PublishOperatorResponse
	(*SyncPublishStatusRequest)(nil),      // 13: platform_operator_operator.SyncPublishStatusRequest
	(*SyncPublishStatusResponse)(nil),     // 14: platform_operator_operator.SyncPublishStatusResponse
	(*HandlePublishResultRequest)(nil),    // 15: platform_operator_operator.HandlePublishResultRequest
	(*HandlePublishResultResponse)(nil),   // 16: platform_operator_operator.HandlePublishResultResponse
	(*DeleteOperatorRequest)(nil),         // 17: platform_operator_operator.DeleteOperatorRequest
	(*DeleteOperatorResponse)(nil),        // 18: platform_operator_operator.DeleteOperatorResponse
	(*InitializationInfo)(nil),            // 19: platform_operator_operator.InitializationInfo
	(*DomainInitializationInfo)(nil),      // 20: platform_operator_operator.DomainInitializationInfo
	(*AdminInitializationInfo)(nil),       // 21: platform_operator_operator.AdminInitializationInfo
	(*GetInitializationDataRequest)(nil),  // 22: platform_operator_operator.GetInitializationDataRequest
	(*GetInitializationDataResponse)(nil), // 23: platform_operator_operator.GetInitializationDataResponse
}
var file_types_platform_operator_operator_proto_depIdxs = []int32{
	0,  // 0: platform_operator_operator.GetOperatorResponse.operator:type_name -> platform_operator_operator.OperatorInfo
	0,  // 1: platform_operator_operator.ListOperatorsResponse.list:type_name -> platform_operator_operator.OperatorInfo
	19, // 2: platform_operator_operator.GetInitializationDataResponse.operator:type_name -> platform_operator_operator.InitializationInfo
	20, // 3: platform_operator_operator.GetInitializationDataResponse.domains:type_name -> platform_operator_operator.DomainInitializationInfo
	21, // 4: platform_operator_operator.GetInitializationDataResponse.admins:type_name -> platform_operator_operator.AdminInitializationInfo
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_types_platform_operator_operator_proto_init() }
func file_types_platform_operator_operator_proto_init() {
	if File_types_platform_operator_operator_proto != nil {
		return
	}
	file_types_platform_operator_operator_proto_msgTypes[0].OneofWrappers = []any{}
	file_types_platform_operator_operator_proto_msgTypes[1].OneofWrappers = []any{}
	file_types_platform_operator_operator_proto_msgTypes[3].OneofWrappers = []any{}
	file_types_platform_operator_operator_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_platform_operator_operator_proto_rawDesc), len(file_types_platform_operator_operator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_platform_operator_operator_proto_goTypes,
		DependencyIndexes: file_types_platform_operator_operator_proto_depIdxs,
		MessageInfos:      file_types_platform_operator_operator_proto_msgTypes,
	}.Build()
	File_types_platform_operator_operator_proto = out.File
	file_types_platform_operator_operator_proto_goTypes = nil
	file_types_platform_operator_operator_proto_depIdxs = nil
}
