// Code generated by ent, DO NOT EDIT.

package game

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the game type in the database.
	Label = "game"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOpCode holds the string denoting the op_code field in the database.
	FieldOpCode = "op_code"
	// FieldGameCode holds the string denoting the game_code field in the database.
	FieldGameCode = "game_code"
	// FieldSourceID holds the string denoting the source_id field in the database.
	FieldSourceID = "source_id"
	// FieldCategoryCode holds the string denoting the category_code field in the database.
	FieldCategoryCode = "category_code"
	// FieldProviderCode holds the string denoting the provider_code field in the database.
	FieldProviderCode = "provider_code"
	// FieldChannelCode holds the string denoting the channel_code field in the database.
	FieldChannelCode = "channel_code"
	// FieldCurrencyList holds the string denoting the currency_list field in the database.
	FieldCurrencyList = "currency_list"
	// FieldProviderKey holds the string denoting the provider_key field in the database.
	FieldProviderKey = "provider_key"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldImageURL holds the string denoting the image_url field in the database.
	FieldImageURL = "image_url"
	// FieldSortNo holds the string denoting the sort_no field in the database.
	FieldSortNo = "sort_no"
	// FieldSupportsEmbed holds the string denoting the supports_embed field in the database.
	FieldSupportsEmbed = "supports_embed"
	// FieldSupportsRedirect holds the string denoting the supports_redirect field in the database.
	FieldSupportsRedirect = "supports_redirect"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the game in the database.
	Table = "game"
)

// Columns holds all SQL columns for game fields.
var Columns = []string{
	FieldID,
	FieldOpCode,
	FieldGameCode,
	FieldSourceID,
	FieldCategoryCode,
	FieldProviderCode,
	FieldChannelCode,
	FieldCurrencyList,
	FieldProviderKey,
	FieldName,
	FieldImageURL,
	FieldSortNo,
	FieldSupportsEmbed,
	FieldSupportsRedirect,
	FieldStatus,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Game queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByOpCode orders the results by the op_code field.
func ByOpCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOpCode, opts...).ToFunc()
}

// ByGameCode orders the results by the game_code field.
func ByGameCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGameCode, opts...).ToFunc()
}

// BySourceID orders the results by the source_id field.
func BySourceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceID, opts...).ToFunc()
}

// ByCategoryCode orders the results by the category_code field.
func ByCategoryCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCategoryCode, opts...).ToFunc()
}

// ByProviderCode orders the results by the provider_code field.
func ByProviderCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderCode, opts...).ToFunc()
}

// ByChannelCode orders the results by the channel_code field.
func ByChannelCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannelCode, opts...).ToFunc()
}

// ByProviderKey orders the results by the provider_key field.
func ByProviderKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderKey, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByImageURL orders the results by the image_url field.
func ByImageURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImageURL, opts...).ToFunc()
}

// BySortNo orders the results by the sort_no field.
func BySortNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSortNo, opts...).ToFunc()
}

// BySupportsEmbed orders the results by the supports_embed field.
func BySupportsEmbed(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSupportsEmbed, opts...).ToFunc()
}

// BySupportsRedirect orders the results by the supports_redirect field.
func BySupportsRedirect(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSupportsRedirect, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
