-- public.game 定义

-- Drop table

-- DROP TABLE game;

CREATE TABLE game (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	game_code varchar NOT NULL,
	source_id int8 NULL,
	category_code varchar NULL,
	provider_code varchar NULL,
	channel_code varchar NULL,
	currency_list jsonb NULL,
	provider_key varchar NULL,
	"name" varchar NULL,
	image_url varchar NULL,
	sort_no int8 NOT NULL,
	supports_embed bool NOT NULL,
	supports_redirect bool NOT NULL,
	status int8 NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	CONSTRAINT game_pkey PRIMARY KEY (id)
);
-- public.game_category 定义

-- Drop table

-- DROP TABLE game_category;

CREATE TABLE game_category (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	category_code varchar NOT NULL,
	sort_no int8 NOT NULL,
	source_status int8 NOT NULL,
	status int8 NOT NULL,
	deleted_at timestamptz NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	CONSTRAINT game_category_pkey PRIMARY KEY (id)
);
-- public.game_channel 定义

-- Drop table

-- DROP TABLE game_channel;

CREATE TABLE game_channel (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	channel_code varchar NOT NULL,
	sort_no int8 NOT NULL,
	load_type int8 NOT NULL,
	status int8 NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	CONSTRAINT game_channel_pkey PRIMARY KEY (id)
);

-- public.game_currency 定义

-- Drop table

-- DROP TABLE game_currency;

CREATE TABLE game_currency (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	game_code varchar NOT NULL,
	currency_code varchar NOT null,
	status int8 NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	CONSTRAINT game_currency_pkey PRIMARY KEY (id)
);


-- public.game_provider 定义

-- Drop table

-- DROP TABLE game_provider;

CREATE TABLE game_provider (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	provider_code varchar NOT NULL,
	channel_id int8 null,
	logo_url varchar NULL,
	sort_no int8 NOT NULL,
	status int8 NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	CONSTRAINT game_provider_pkey PRIMARY KEY (id)
);