// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.32.0
// source: types/platform_operator_operator_node.proto

package operatornodepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 分站部署节点信息
type OperatorNodeInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分站ID
	OperatorId int64 `protobuf:"varint,1,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	// 分站全局唯一业务编码
	OperatorCode string `protobuf:"bytes,2,opt,name=operator_code,json=operatorCode,proto3" json:"operator_code,omitempty"`
	// 节点业务编码
	NodeCode string `protobuf:"bytes,3,opt,name=node_code,json=nodeCode,proto3" json:"node_code,omitempty"`
	// 节点名称
	NodeName string `protobuf:"bytes,4,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	// 节点状态: 1启用, 2停用
	NodeStatus int64 `protobuf:"varint,5,opt,name=node_status,json=nodeStatus,proto3" json:"node_status,omitempty"`
	// 节点是否在线
	NodeOnline bool `protobuf:"varint,6,opt,name=node_online,json=nodeOnline,proto3" json:"node_online,omitempty"`
	// 节点最近一次活动时间, Unix毫秒时间戳
	NodeLastSeenAt *int64 `protobuf:"varint,7,opt,name=node_last_seen_at,json=nodeLastSeenAt,proto3,oneof" json:"node_last_seen_at,omitempty"`
	// 节点运维备注
	NodeRemark *string `protobuf:"bytes,8,opt,name=node_remark,json=nodeRemark,proto3,oneof" json:"node_remark,omitempty"`
	// 部署节点关系创建时间, Unix毫秒时间戳
	CreatedAt int64 `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// 部署节点关系更新时间, Unix毫秒时间戳
	UpdatedAt     int64 `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperatorNodeInfo) Reset() {
	*x = OperatorNodeInfo{}
	mi := &file_types_platform_operator_operator_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatorNodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatorNodeInfo) ProtoMessage() {}

func (x *OperatorNodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_types_platform_operator_operator_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatorNodeInfo.ProtoReflect.Descriptor instead.
func (*OperatorNodeInfo) Descriptor() ([]byte, []int) {
	return file_types_platform_operator_operator_node_proto_rawDescGZIP(), []int{0}
}

func (x *OperatorNodeInfo) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

func (x *OperatorNodeInfo) GetOperatorCode() string {
	if x != nil {
		return x.OperatorCode
	}
	return ""
}

func (x *OperatorNodeInfo) GetNodeCode() string {
	if x != nil {
		return x.NodeCode
	}
	return ""
}

func (x *OperatorNodeInfo) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *OperatorNodeInfo) GetNodeStatus() int64 {
	if x != nil {
		return x.NodeStatus
	}
	return 0
}

func (x *OperatorNodeInfo) GetNodeOnline() bool {
	if x != nil {
		return x.NodeOnline
	}
	return false
}

func (x *OperatorNodeInfo) GetNodeLastSeenAt() int64 {
	if x != nil && x.NodeLastSeenAt != nil {
		return *x.NodeLastSeenAt
	}
	return 0
}

func (x *OperatorNodeInfo) GetNodeRemark() string {
	if x != nil && x.NodeRemark != nil {
		return *x.NodeRemark
	}
	return ""
}

func (x *OperatorNodeInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *OperatorNodeInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// 保存分站部署节点请求
type SaveOperatorNodeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分站ID
	OperatorId int64 `protobuf:"varint,1,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	// 节点业务编码
	NodeCode      string `protobuf:"bytes,2,opt,name=node_code,json=nodeCode,proto3" json:"node_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveOperatorNodeRequest) Reset() {
	*x = SaveOperatorNodeRequest{}
	mi := &file_types_platform_operator_operator_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveOperatorNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveOperatorNodeRequest) ProtoMessage() {}

func (x *SaveOperatorNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_platform_operator_operator_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveOperatorNodeRequest.ProtoReflect.Descriptor instead.
func (*SaveOperatorNodeRequest) Descriptor() ([]byte, []int) {
	return file_types_platform_operator_operator_node_proto_rawDescGZIP(), []int{1}
}

func (x *SaveOperatorNodeRequest) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

func (x *SaveOperatorNodeRequest) GetNodeCode() string {
	if x != nil {
		return x.NodeCode
	}
	return ""
}

// 保存分站部署节点响应
type SaveOperatorNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveOperatorNodeResponse) Reset() {
	*x = SaveOperatorNodeResponse{}
	mi := &file_types_platform_operator_operator_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveOperatorNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveOperatorNodeResponse) ProtoMessage() {}

func (x *SaveOperatorNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_platform_operator_operator_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveOperatorNodeResponse.ProtoReflect.Descriptor instead.
func (*SaveOperatorNodeResponse) Descriptor() ([]byte, []int) {
	return file_types_platform_operator_operator_node_proto_rawDescGZIP(), []int{2}
}

// 获取分站部署节点请求
type GetOperatorNodeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分站ID
	OperatorId    int64 `protobuf:"varint,1,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperatorNodeRequest) Reset() {
	*x = GetOperatorNodeRequest{}
	mi := &file_types_platform_operator_operator_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperatorNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperatorNodeRequest) ProtoMessage() {}

func (x *GetOperatorNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_platform_operator_operator_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperatorNodeRequest.ProtoReflect.Descriptor instead.
func (*GetOperatorNodeRequest) Descriptor() ([]byte, []int) {
	return file_types_platform_operator_operator_node_proto_rawDescGZIP(), []int{3}
}

func (x *GetOperatorNodeRequest) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

// 获取分站部署节点响应
type GetOperatorNodeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分站部署节点信息, 尚未选择节点时为空
	OperatorNode  *OperatorNodeInfo `protobuf:"bytes,1,opt,name=operator_node,json=operatorNode,proto3" json:"operator_node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperatorNodeResponse) Reset() {
	*x = GetOperatorNodeResponse{}
	mi := &file_types_platform_operator_operator_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperatorNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperatorNodeResponse) ProtoMessage() {}

func (x *GetOperatorNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_platform_operator_operator_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperatorNodeResponse.ProtoReflect.Descriptor instead.
func (*GetOperatorNodeResponse) Descriptor() ([]byte, []int) {
	return file_types_platform_operator_operator_node_proto_rawDescGZIP(), []int{4}
}

func (x *GetOperatorNodeResponse) GetOperatorNode() *OperatorNodeInfo {
	if x != nil {
		return x.OperatorNode
	}
	return nil
}

var File_types_platform_operator_operator_node_proto protoreflect.FileDescriptor

const file_types_platform_operator_operator_node_proto_rawDesc = "" +
	"\n" +
	"+types/platform_operator_operator_node.proto\x12\x1fplatform_operator_operator_node\"\x8e\x03\n" +
	"\x10OperatorNodeInfo\x12\x1f\n" +
	"\voperator_id\x18\x01 \x01(\x03R\n" +
	"operatorId\x12#\n" +
	"\roperator_code\x18\x02 \x01(\tR\foperatorCode\x12\x1b\n" +
	"\tnode_code\x18\x03 \x01(\tR\bnodeCode\x12\x1b\n" +
	"\tnode_name\x18\x04 \x01(\tR\bnodeName\x12\x1f\n" +
	"\vnode_status\x18\x05 \x01(\x03R\n" +
	"nodeStatus\x12\x1f\n" +
	"\vnode_online\x18\x06 \x01(\bR\n" +
	"nodeOnline\x12.\n" +
	"\x11node_last_seen_at\x18\a \x01(\x03H\x00R\x0enodeLastSeenAt\x88\x01\x01\x12$\n" +
	"\vnode_remark\x18\b \x01(\tH\x01R\n" +
	"nodeRemark\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\x03R\tupdatedAtB\x14\n" +
	"\x12_node_last_seen_atB\x0e\n" +
	"\f_node_remark\"W\n" +
	"\x17SaveOperatorNodeRequest\x12\x1f\n" +
	"\voperator_id\x18\x01 \x01(\x03R\n" +
	"operatorId\x12\x1b\n" +
	"\tnode_code\x18\x02 \x01(\tR\bnodeCode\"\x1a\n" +
	"\x18SaveOperatorNodeResponse\"9\n" +
	"\x16GetOperatorNodeRequest\x12\x1f\n" +
	"\voperator_id\x18\x01 \x01(\x03R\n" +
	"operatorId\"q\n" +
	"\x17GetOperatorNodeResponse\x12V\n" +
	"\roperator_node\x18\x01 \x01(\v21.platform_operator_operator_node.OperatorNodeInfoR\foperatorNodeBMZKoa.98ent.com/p9/platform-operator/rpc/pb/platformoperatorrpc/operatornodepbb\x06proto3"

var (
	file_types_platform_operator_operator_node_proto_rawDescOnce sync.Once
	file_types_platform_operator_operator_node_proto_rawDescData []byte
)

func file_types_platform_operator_operator_node_proto_rawDescGZIP() []byte {
	file_types_platform_operator_operator_node_proto_rawDescOnce.Do(func() {
		file_types_platform_operator_operator_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_platform_operator_operator_node_proto_rawDesc), len(file_types_platform_operator_operator_node_proto_rawDesc)))
	})
	return file_types_platform_operator_operator_node_proto_rawDescData
}

var file_types_platform_operator_operator_node_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_types_platform_operator_operator_node_proto_goTypes = []any{
	(*OperatorNodeInfo)(nil),         // 0: platform_operator_operator_node.OperatorNodeInfo
	(*SaveOperatorNodeRequest)(nil),  // 1: platform_operator_operator_node.SaveOperatorNodeRequest
	(*SaveOperatorNodeResponse)(nil), // 2: platform_operator_operator_node.SaveOperatorNodeResponse
	(*GetOperatorNodeRequest)(nil),   // 3: platform_operator_operator_node.GetOperatorNodeRequest
	(*GetOperatorNodeResponse)(nil),  // 4: platform_operator_operator_node.GetOperatorNodeResponse
}
var file_types_platform_operator_operator_node_proto_depIdxs = []int32{
	0, // 0: platform_operator_operator_node.GetOperatorNodeResponse.operator_node:type_name -> platform_operator_operator_node.OperatorNodeInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_types_platform_operator_operator_node_proto_init() }
func file_types_platform_operator_operator_node_proto_init() {
	if File_types_platform_operator_operator_node_proto != nil {
		return
	}
	file_types_platform_operator_operator_node_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_platform_operator_operator_node_proto_rawDesc), len(file_types_platform_operator_operator_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_platform_operator_operator_node_proto_goTypes,
		DependencyIndexes: file_types_platform_operator_operator_node_proto_depIdxs,
		MessageInfos:      file_types_platform_operator_operator_node_proto_msgTypes,
	}.Build()
	File_types_platform_operator_operator_node_proto = out.File
	file_types_platform_operator_operator_node_proto_goTypes = nil
	file_types_platform_operator_operator_node_proto_depIdxs = nil
}
