// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.19.4
// source: op/game_category.proto

package operator_game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GameCategoryInfo 分类信息
type GameCategoryInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryCode  string                 `protobuf:"bytes,2,opt,name=category_code,json=categoryCode,proto3" json:"category_code,omitempty"`
	SortNo        int32                  `protobuf:"varint,4,opt,name=sort_no,json=sortNo,proto3" json:"sort_no,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameCategoryInfo) Reset() {
	*x = GameCategoryInfo{}
	mi := &file_op_game_category_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameCategoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameCategoryInfo) ProtoMessage() {}

func (x *GameCategoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_op_game_category_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameCategoryInfo.ProtoReflect.Descriptor instead.
func (*GameCategoryInfo) Descriptor() ([]byte, []int) {
	return file_op_game_category_proto_rawDescGZIP(), []int{0}
}

func (x *GameCategoryInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GameCategoryInfo) GetCategoryCode() string {
	if x != nil {
		return x.CategoryCode
	}
	return ""
}

func (x *GameCategoryInfo) GetSortNo() int32 {
	if x != nil {
		return x.SortNo
	}
	return 0
}

func (x *GameCategoryInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GameCategoryInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *GameCategoryInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// GetGameCategoryListRequest 获取游戏分类列表请求
type GetGameCategoryListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	CategoryCode  string                 `protobuf:"bytes,3,opt,name=category_code,json=categoryCode,proto3" json:"category_code,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameCategoryListRequest) Reset() {
	*x = GetGameCategoryListRequest{}
	mi := &file_op_game_category_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameCategoryListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameCategoryListRequest) ProtoMessage() {}

func (x *GetGameCategoryListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_op_game_category_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameCategoryListRequest.ProtoReflect.Descriptor instead.
func (*GetGameCategoryListRequest) Descriptor() ([]byte, []int) {
	return file_op_game_category_proto_rawDescGZIP(), []int{1}
}

func (x *GetGameCategoryListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetGameCategoryListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetGameCategoryListRequest) GetCategoryCode() string {
	if x != nil {
		return x.CategoryCode
	}
	return ""
}

func (x *GetGameCategoryListRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// GetGameCategoryListResp 游戏分类列表响应
type GetGameCategoryListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Items         []*GameCategoryInfo    `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameCategoryListResp) Reset() {
	*x = GetGameCategoryListResp{}
	mi := &file_op_game_category_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameCategoryListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameCategoryListResp) ProtoMessage() {}

func (x *GetGameCategoryListResp) ProtoReflect() protoreflect.Message {
	mi := &file_op_game_category_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameCategoryListResp.ProtoReflect.Descriptor instead.
func (*GetGameCategoryListResp) Descriptor() ([]byte, []int) {
	return file_op_game_category_proto_rawDescGZIP(), []int{2}
}

func (x *GetGameCategoryListResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetGameCategoryListResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetGameCategoryListResp) GetItems() []*GameCategoryInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetGameCategoryListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// GetGameCategoryRequest 获取单个游戏分类请求
type GetGameCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameCategoryRequest) Reset() {
	*x = GetGameCategoryRequest{}
	mi := &file_op_game_category_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameCategoryRequest) ProtoMessage() {}

func (x *GetGameCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_op_game_category_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameCategoryRequest.ProtoReflect.Descriptor instead.
func (*GetGameCategoryRequest) Descriptor() ([]byte, []int) {
	return file_op_game_category_proto_rawDescGZIP(), []int{3}
}

func (x *GetGameCategoryRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// GetGameCategoryResp 获取单个游戏分类响应
type GetGameCategoryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *GameCategoryInfo      `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameCategoryResp) Reset() {
	*x = GetGameCategoryResp{}
	mi := &file_op_game_category_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameCategoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameCategoryResp) ProtoMessage() {}

func (x *GetGameCategoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_op_game_category_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameCategoryResp.ProtoReflect.Descriptor instead.
func (*GetGameCategoryResp) Descriptor() ([]byte, []int) {
	return file_op_game_category_proto_rawDescGZIP(), []int{4}
}

func (x *GetGameCategoryResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetGameCategoryResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetGameCategoryResp) GetData() *GameCategoryInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

// UpdateGameCategoryRequest 更新分类请求
type UpdateGameCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SortNo        int32                  `protobuf:"varint,2,opt,name=sort_no,json=sortNo,proto3" json:"sort_no,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGameCategoryRequest) Reset() {
	*x = UpdateGameCategoryRequest{}
	mi := &file_op_game_category_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGameCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGameCategoryRequest) ProtoMessage() {}

func (x *UpdateGameCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_op_game_category_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGameCategoryRequest.ProtoReflect.Descriptor instead.
func (*UpdateGameCategoryRequest) Descriptor() ([]byte, []int) {
	return file_op_game_category_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateGameCategoryRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateGameCategoryRequest) GetSortNo() int32 {
	if x != nil {
		return x.SortNo
	}
	return 0
}

func (x *UpdateGameCategoryRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// UpdateGameCategoryResp 更新分类响应
type UpdateGameCategoryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *GameCategoryInfo      `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGameCategoryResp) Reset() {
	*x = UpdateGameCategoryResp{}
	mi := &file_op_game_category_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGameCategoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGameCategoryResp) ProtoMessage() {}

func (x *UpdateGameCategoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_op_game_category_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGameCategoryResp.ProtoReflect.Descriptor instead.
func (*UpdateGameCategoryResp) Descriptor() ([]byte, []int) {
	return file_op_game_category_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateGameCategoryResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateGameCategoryResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateGameCategoryResp) GetData() *GameCategoryInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_op_game_category_proto protoreflect.FileDescriptor

const file_op_game_category_proto_rawDesc = "" +
	"\n" +
	"\x16op/game_category.proto\x12\roperator_game\"\xb6\x01\n" +
	"\x10GameCategoryInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12#\n" +
	"\rcategory_code\x18\x02 \x01(\tR\fcategoryCode\x12\x17\n" +
	"\asort_no\x18\x04 \x01(\x05R\x06sortNo\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt\"\x8a\x01\n" +
	"\x1aGetGameCategoryListRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12#\n" +
	"\rcategory_code\x18\x03 \x01(\tR\fcategoryCode\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\"\x94\x01\n" +
	"\x17GetGameCategoryListResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x125\n" +
	"\x05items\x18\x03 \x03(\v2\x1f.operator_game.GameCategoryInfoR\x05items\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x03R\x05total\"(\n" +
	"\x16GetGameCategoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"x\n" +
	"\x13GetGameCategoryResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x123\n" +
	"\x04data\x18\x03 \x01(\v2\x1f.operator_game.GameCategoryInfoR\x04data\"\\\n" +
	"\x19UpdateGameCategoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\asort_no\x18\x02 \x01(\x05R\x06sortNo\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\"{\n" +
	"\x16UpdateGameCategoryResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x123\n" +
	"\x04data\x18\x03 \x01(\v2\x1f.operator_game.GameCategoryInfoR\x04dataB4Z2oa.98ent.com/p9/operator-game/rpc/pb/operator_gameb\x06proto3"

var (
	file_op_game_category_proto_rawDescOnce sync.Once
	file_op_game_category_proto_rawDescData []byte
)

func file_op_game_category_proto_rawDescGZIP() []byte {
	file_op_game_category_proto_rawDescOnce.Do(func() {
		file_op_game_category_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_op_game_category_proto_rawDesc), len(file_op_game_category_proto_rawDesc)))
	})
	return file_op_game_category_proto_rawDescData
}

var file_op_game_category_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_op_game_category_proto_goTypes = []any{
	(*GameCategoryInfo)(nil),           // 0: operator_game.GameCategoryInfo
	(*GetGameCategoryListRequest)(nil), // 1: operator_game.GetGameCategoryListRequest
	(*GetGameCategoryListResp)(nil),    // 2: operator_game.GetGameCategoryListResp
	(*GetGameCategoryRequest)(nil),     // 3: operator_game.GetGameCategoryRequest
	(*GetGameCategoryResp)(nil),        // 4: operator_game.GetGameCategoryResp
	(*UpdateGameCategoryRequest)(nil),  // 5: operator_game.UpdateGameCategoryRequest
	(*UpdateGameCategoryResp)(nil),     // 6: operator_game.UpdateGameCategoryResp
}
var file_op_game_category_proto_depIdxs = []int32{
	0, // 0: operator_game.GetGameCategoryListResp.items:type_name -> operator_game.GameCategoryInfo
	0, // 1: operator_game.GetGameCategoryResp.data:type_name -> operator_game.GameCategoryInfo
	0, // 2: operator_game.UpdateGameCategoryResp.data:type_name -> operator_game.GameCategoryInfo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_op_game_category_proto_init() }
func file_op_game_category_proto_init() {
	if File_op_game_category_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_op_game_category_proto_rawDesc), len(file_op_game_category_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_op_game_category_proto_goTypes,
		DependencyIndexes: file_op_game_category_proto_depIdxs,
		MessageInfos:      file_op_game_category_proto_msgTypes,
	}.Build()
	File_op_game_category_proto = out.File
	file_op_game_category_proto_goTypes = nil
	file_op_game_category_proto_depIdxs = nil
}
