// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.19.4
// source: op/game_channel.proto

package operator_game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GameChannelInfo 游戏渠道信息（包含名称）
type GameChannelInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ChannelCode   string                 `protobuf:"bytes,2,opt,name=channel_code,json=channelCode,proto3" json:"channel_code,omitempty"`
	ProviderCount int32                  `protobuf:"varint,3,opt,name=provider_count,json=providerCount,proto3" json:"provider_count,omitempty"`
	GameCount     int32                  `protobuf:"varint,4,opt,name=game_count,json=gameCount,proto3" json:"game_count,omitempty"`
	SortNo        int32                  `protobuf:"varint,5,opt,name=sort_no,json=sortNo,proto3" json:"sort_no,omitempty"`
	LoadType      int32                  `protobuf:"varint,6,opt,name=load_type,json=loadType,proto3" json:"load_type,omitempty"`
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameChannelInfo) Reset() {
	*x = GameChannelInfo{}
	mi := &file_op_game_channel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameChannelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameChannelInfo) ProtoMessage() {}

func (x *GameChannelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_op_game_channel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameChannelInfo.ProtoReflect.Descriptor instead.
func (*GameChannelInfo) Descriptor() ([]byte, []int) {
	return file_op_game_channel_proto_rawDescGZIP(), []int{0}
}

func (x *GameChannelInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GameChannelInfo) GetChannelCode() string {
	if x != nil {
		return x.ChannelCode
	}
	return ""
}

func (x *GameChannelInfo) GetProviderCount() int32 {
	if x != nil {
		return x.ProviderCount
	}
	return 0
}

func (x *GameChannelInfo) GetGameCount() int32 {
	if x != nil {
		return x.GameCount
	}
	return 0
}

func (x *GameChannelInfo) GetSortNo() int32 {
	if x != nil {
		return x.SortNo
	}
	return 0
}

func (x *GameChannelInfo) GetLoadType() int32 {
	if x != nil {
		return x.LoadType
	}
	return 0
}

func (x *GameChannelInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GameChannelInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *GameChannelInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// GetGameChannelRequest 获取单个游戏渠道请求
type GetGameChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameChannelRequest) Reset() {
	*x = GetGameChannelRequest{}
	mi := &file_op_game_channel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameChannelRequest) ProtoMessage() {}

func (x *GetGameChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_op_game_channel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameChannelRequest.ProtoReflect.Descriptor instead.
func (*GetGameChannelRequest) Descriptor() ([]byte, []int) {
	return file_op_game_channel_proto_rawDescGZIP(), []int{1}
}

func (x *GetGameChannelRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// GetGameChannelResp 获取单个游戏渠道响应
type GetGameChannelResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *GameChannelInfo       `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameChannelResp) Reset() {
	*x = GetGameChannelResp{}
	mi := &file_op_game_channel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameChannelResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameChannelResp) ProtoMessage() {}

func (x *GetGameChannelResp) ProtoReflect() protoreflect.Message {
	mi := &file_op_game_channel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameChannelResp.ProtoReflect.Descriptor instead.
func (*GetGameChannelResp) Descriptor() ([]byte, []int) {
	return file_op_game_channel_proto_rawDescGZIP(), []int{2}
}

func (x *GetGameChannelResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetGameChannelResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetGameChannelResp) GetData() *GameChannelInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

// GetGameChannelListRequest 获取游戏渠道列表请求
type GetGameChannelListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	ChannelCode   string                 `protobuf:"bytes,3,opt,name=channel_code,json=channelCode,proto3" json:"channel_code,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameChannelListRequest) Reset() {
	*x = GetGameChannelListRequest{}
	mi := &file_op_game_channel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameChannelListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameChannelListRequest) ProtoMessage() {}

func (x *GetGameChannelListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_op_game_channel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameChannelListRequest.ProtoReflect.Descriptor instead.
func (*GetGameChannelListRequest) Descriptor() ([]byte, []int) {
	return file_op_game_channel_proto_rawDescGZIP(), []int{3}
}

func (x *GetGameChannelListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetGameChannelListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetGameChannelListRequest) GetChannelCode() string {
	if x != nil {
		return x.ChannelCode
	}
	return ""
}

func (x *GetGameChannelListRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// GetGameChannelListResp 游戏渠道列表响应
type GetGameChannelListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Items         []*GameChannelInfo     `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameChannelListResp) Reset() {
	*x = GetGameChannelListResp{}
	mi := &file_op_game_channel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameChannelListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameChannelListResp) ProtoMessage() {}

func (x *GetGameChannelListResp) ProtoReflect() protoreflect.Message {
	mi := &file_op_game_channel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameChannelListResp.ProtoReflect.Descriptor instead.
func (*GetGameChannelListResp) Descriptor() ([]byte, []int) {
	return file_op_game_channel_proto_rawDescGZIP(), []int{4}
}

func (x *GetGameChannelListResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetGameChannelListResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetGameChannelListResp) GetItems() []*GameChannelInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetGameChannelListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// UpdateGameChannelRequest 更新渠道请求
type UpdateGameChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SortNo        int32                  `protobuf:"varint,2,opt,name=sort_no,json=sortNo,proto3" json:"sort_no,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGameChannelRequest) Reset() {
	*x = UpdateGameChannelRequest{}
	mi := &file_op_game_channel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGameChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGameChannelRequest) ProtoMessage() {}

func (x *UpdateGameChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_op_game_channel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGameChannelRequest.ProtoReflect.Descriptor instead.
func (*UpdateGameChannelRequest) Descriptor() ([]byte, []int) {
	return file_op_game_channel_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateGameChannelRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateGameChannelRequest) GetSortNo() int32 {
	if x != nil {
		return x.SortNo
	}
	return 0
}

func (x *UpdateGameChannelRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// UpdateGameChannelResp 更新渠道响应
type UpdateGameChannelResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *GameChannelInfo       `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGameChannelResp) Reset() {
	*x = UpdateGameChannelResp{}
	mi := &file_op_game_channel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGameChannelResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGameChannelResp) ProtoMessage() {}

func (x *UpdateGameChannelResp) ProtoReflect() protoreflect.Message {
	mi := &file_op_game_channel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGameChannelResp.ProtoReflect.Descriptor instead.
func (*UpdateGameChannelResp) Descriptor() ([]byte, []int) {
	return file_op_game_channel_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateGameChannelResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateGameChannelResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateGameChannelResp) GetData() *GameChannelInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_op_game_channel_proto protoreflect.FileDescriptor

const file_op_game_channel_proto_rawDesc = "" +
	"\n" +
	"\x15op/game_channel.proto\x12\roperator_game\"\x96\x02\n" +
	"\x0fGameChannelInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\fchannel_code\x18\x02 \x01(\tR\vchannelCode\x12%\n" +
	"\x0eprovider_count\x18\x03 \x01(\x05R\rproviderCount\x12\x1d\n" +
	"\n" +
	"game_count\x18\x04 \x01(\x05R\tgameCount\x12\x17\n" +
	"\asort_no\x18\x05 \x01(\x05R\x06sortNo\x12\x1b\n" +
	"\tload_type\x18\x06 \x01(\x05R\bloadType\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\x03R\tupdatedAt\"'\n" +
	"\x15GetGameChannelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"v\n" +
	"\x12GetGameChannelResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x122\n" +
	"\x04data\x18\x03 \x01(\v2\x1e.operator_game.GameChannelInfoR\x04data\"\x87\x01\n" +
	"\x19GetGameChannelListRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12!\n" +
	"\fchannel_code\x18\x03 \x01(\tR\vchannelCode\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\"\x92\x01\n" +
	"\x16GetGameChannelListResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x124\n" +
	"\x05items\x18\x03 \x03(\v2\x1e.operator_game.GameChannelInfoR\x05items\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x03R\x05total\"[\n" +
	"\x18UpdateGameChannelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\asort_no\x18\x02 \x01(\x05R\x06sortNo\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\"y\n" +
	"\x15UpdateGameChannelResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x122\n" +
	"\x04data\x18\x03 \x01(\v2\x1e.operator_game.GameChannelInfoR\x04dataB4Z2oa.98ent.com/p9/operator-game/rpc/pb/operator_gameb\x06proto3"

var (
	file_op_game_channel_proto_rawDescOnce sync.Once
	file_op_game_channel_proto_rawDescData []byte
)

func file_op_game_channel_proto_rawDescGZIP() []byte {
	file_op_game_channel_proto_rawDescOnce.Do(func() {
		file_op_game_channel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_op_game_channel_proto_rawDesc), len(file_op_game_channel_proto_rawDesc)))
	})
	return file_op_game_channel_proto_rawDescData
}

var file_op_game_channel_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_op_game_channel_proto_goTypes = []any{
	(*GameChannelInfo)(nil),           // 0: operator_game.GameChannelInfo
	(*GetGameChannelRequest)(nil),     // 1: operator_game.GetGameChannelRequest
	(*GetGameChannelResp)(nil),        // 2: operator_game.GetGameChannelResp
	(*GetGameChannelListRequest)(nil), // 3: operator_game.GetGameChannelListRequest
	(*GetGameChannelListResp)(nil),    // 4: operator_game.GetGameChannelListResp
	(*UpdateGameChannelRequest)(nil),  // 5: operator_game.UpdateGameChannelRequest
	(*UpdateGameChannelResp)(nil),     // 6: operator_game.UpdateGameChannelResp
}
var file_op_game_channel_proto_depIdxs = []int32{
	0, // 0: operator_game.GetGameChannelResp.data:type_name -> operator_game.GameChannelInfo
	0, // 1: operator_game.GetGameChannelListResp.items:type_name -> operator_game.GameChannelInfo
	0, // 2: operator_game.UpdateGameChannelResp.data:type_name -> operator_game.GameChannelInfo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_op_game_channel_proto_init() }
func file_op_game_channel_proto_init() {
	if File_op_game_channel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_op_game_channel_proto_rawDesc), len(file_op_game_channel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_op_game_channel_proto_goTypes,
		DependencyIndexes: file_op_game_channel_proto_depIdxs,
		MessageInfos:      file_op_game_channel_proto_msgTypes,
	}.Build()
	File_op_game_channel_proto = out.File
	file_op_game_channel_proto_goTypes = nil
	file_op_game_channel_proto_depIdxs = nil
}
