// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.19.4
// source: operator_game.proto

package operator_game

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GameService_GetGameList_FullMethodName = "/operator_game.GameService/GetGameList"
	GameService_GetGame_FullMethodName     = "/operator_game.GameService/GetGame"
	GameService_UpdateGame_FullMethodName  = "/operator_game.GameService/UpdateGame"
)

// GameServiceClient is the client API for GameService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GameService - 游戏服务
type GameServiceClient interface {
	// 获取游戏列表
	GetGameList(ctx context.Context, in *GetGameListRequest, opts ...grpc.CallOption) (*GetGameListResp, error)
	// 获取单个游戏详情
	GetGame(ctx context.Context, in *GetGameRequest, opts ...grpc.CallOption) (*GetGameResp, error)
	// 更新游戏
	UpdateGame(ctx context.Context, in *UpdateGameRequest, opts ...grpc.CallOption) (*UpdateGameResp, error)
}

type gameServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGameServiceClient(cc grpc.ClientConnInterface) GameServiceClient {
	return &gameServiceClient{cc}
}

func (c *gameServiceClient) GetGameList(ctx context.Context, in *GetGameListRequest, opts ...grpc.CallOption) (*GetGameListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGameListResp)
	err := c.cc.Invoke(ctx, GameService_GetGameList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GetGame(ctx context.Context, in *GetGameRequest, opts ...grpc.CallOption) (*GetGameResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGameResp)
	err := c.cc.Invoke(ctx, GameService_GetGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) UpdateGame(ctx context.Context, in *UpdateGameRequest, opts ...grpc.CallOption) (*UpdateGameResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateGameResp)
	err := c.cc.Invoke(ctx, GameService_UpdateGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameServiceServer is the server API for GameService service.
// All implementations must embed UnimplementedGameServiceServer
// for forward compatibility.
//
// GameService - 游戏服务
type GameServiceServer interface {
	// 获取游戏列表
	GetGameList(context.Context, *GetGameListRequest) (*GetGameListResp, error)
	// 获取单个游戏详情
	GetGame(context.Context, *GetGameRequest) (*GetGameResp, error)
	// 更新游戏
	UpdateGame(context.Context, *UpdateGameRequest) (*UpdateGameResp, error)
	mustEmbedUnimplementedGameServiceServer()
}

// UnimplementedGameServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameServiceServer struct{}

func (UnimplementedGameServiceServer) GetGameList(context.Context, *GetGameListRequest) (*GetGameListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGameList not implemented")
}
func (UnimplementedGameServiceServer) GetGame(context.Context, *GetGameRequest) (*GetGameResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGame not implemented")
}
func (UnimplementedGameServiceServer) UpdateGame(context.Context, *UpdateGameRequest) (*UpdateGameResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateGame not implemented")
}
func (UnimplementedGameServiceServer) mustEmbedUnimplementedGameServiceServer() {}
func (UnimplementedGameServiceServer) testEmbeddedByValue()                     {}

// UnsafeGameServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameServiceServer will
// result in compilation errors.
type UnsafeGameServiceServer interface {
	mustEmbedUnimplementedGameServiceServer()
}

func RegisterGameServiceServer(s grpc.ServiceRegistrar, srv GameServiceServer) {
	// If the following call panics, it indicates UnimplementedGameServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GameService_ServiceDesc, srv)
}

func _GameService_GetGameList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetGameList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_GetGameList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetGameList(ctx, req.(*GetGameListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GetGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_GetGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetGame(ctx, req.(*GetGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_UpdateGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).UpdateGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_UpdateGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).UpdateGame(ctx, req.(*UpdateGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GameService_ServiceDesc is the grpc.ServiceDesc for GameService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "operator_game.GameService",
	HandlerType: (*GameServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGameList",
			Handler:    _GameService_GetGameList_Handler,
		},
		{
			MethodName: "GetGame",
			Handler:    _GameService_GetGame_Handler,
		},
		{
			MethodName: "UpdateGame",
			Handler:    _GameService_UpdateGame_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "operator_game.proto",
}

const (
	GameCategoryService_GetGameCategoryList_FullMethodName = "/operator_game.GameCategoryService/GetGameCategoryList"
	GameCategoryService_GetGameCategory_FullMethodName     = "/operator_game.GameCategoryService/GetGameCategory"
	GameCategoryService_UpdateGameCategory_FullMethodName  = "/operator_game.GameCategoryService/UpdateGameCategory"
)

// GameCategoryServiceClient is the client API for GameCategoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GameCategoryService - 游戏分类服务
type GameCategoryServiceClient interface {
	// 获取游戏分类列表
	GetGameCategoryList(ctx context.Context, in *GetGameCategoryListRequest, opts ...grpc.CallOption) (*GetGameCategoryListResp, error)
	// 获取单个游戏分类
	GetGameCategory(ctx context.Context, in *GetGameCategoryRequest, opts ...grpc.CallOption) (*GetGameCategoryResp, error)
	// 更新游戏分类
	UpdateGameCategory(ctx context.Context, in *UpdateGameCategoryRequest, opts ...grpc.CallOption) (*UpdateGameCategoryResp, error)
}

type gameCategoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGameCategoryServiceClient(cc grpc.ClientConnInterface) GameCategoryServiceClient {
	return &gameCategoryServiceClient{cc}
}

func (c *gameCategoryServiceClient) GetGameCategoryList(ctx context.Context, in *GetGameCategoryListRequest, opts ...grpc.CallOption) (*GetGameCategoryListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGameCategoryListResp)
	err := c.cc.Invoke(ctx, GameCategoryService_GetGameCategoryList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameCategoryServiceClient) GetGameCategory(ctx context.Context, in *GetGameCategoryRequest, opts ...grpc.CallOption) (*GetGameCategoryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGameCategoryResp)
	err := c.cc.Invoke(ctx, GameCategoryService_GetGameCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameCategoryServiceClient) UpdateGameCategory(ctx context.Context, in *UpdateGameCategoryRequest, opts ...grpc.CallOption) (*UpdateGameCategoryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateGameCategoryResp)
	err := c.cc.Invoke(ctx, GameCategoryService_UpdateGameCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameCategoryServiceServer is the server API for GameCategoryService service.
// All implementations must embed UnimplementedGameCategoryServiceServer
// for forward compatibility.
//
// GameCategoryService - 游戏分类服务
type GameCategoryServiceServer interface {
	// 获取游戏分类列表
	GetGameCategoryList(context.Context, *GetGameCategoryListRequest) (*GetGameCategoryListResp, error)
	// 获取单个游戏分类
	GetGameCategory(context.Context, *GetGameCategoryRequest) (*GetGameCategoryResp, error)
	// 更新游戏分类
	UpdateGameCategory(context.Context, *UpdateGameCategoryRequest) (*UpdateGameCategoryResp, error)
	mustEmbedUnimplementedGameCategoryServiceServer()
}

// UnimplementedGameCategoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameCategoryServiceServer struct{}

func (UnimplementedGameCategoryServiceServer) GetGameCategoryList(context.Context, *GetGameCategoryListRequest) (*GetGameCategoryListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGameCategoryList not implemented")
}
func (UnimplementedGameCategoryServiceServer) GetGameCategory(context.Context, *GetGameCategoryRequest) (*GetGameCategoryResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGameCategory not implemented")
}
func (UnimplementedGameCategoryServiceServer) UpdateGameCategory(context.Context, *UpdateGameCategoryRequest) (*UpdateGameCategoryResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateGameCategory not implemented")
}
func (UnimplementedGameCategoryServiceServer) mustEmbedUnimplementedGameCategoryServiceServer() {}
func (UnimplementedGameCategoryServiceServer) testEmbeddedByValue()                             {}

// UnsafeGameCategoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameCategoryServiceServer will
// result in compilation errors.
type UnsafeGameCategoryServiceServer interface {
	mustEmbedUnimplementedGameCategoryServiceServer()
}

func RegisterGameCategoryServiceServer(s grpc.ServiceRegistrar, srv GameCategoryServiceServer) {
	// If the following call panics, it indicates UnimplementedGameCategoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GameCategoryService_ServiceDesc, srv)
}

func _GameCategoryService_GetGameCategoryList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameCategoryListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameCategoryServiceServer).GetGameCategoryList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameCategoryService_GetGameCategoryList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameCategoryServiceServer).GetGameCategoryList(ctx, req.(*GetGameCategoryListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameCategoryService_GetGameCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameCategoryServiceServer).GetGameCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameCategoryService_GetGameCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameCategoryServiceServer).GetGameCategory(ctx, req.(*GetGameCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameCategoryService_UpdateGameCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGameCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameCategoryServiceServer).UpdateGameCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameCategoryService_UpdateGameCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameCategoryServiceServer).UpdateGameCategory(ctx, req.(*UpdateGameCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GameCategoryService_ServiceDesc is the grpc.ServiceDesc for GameCategoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameCategoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "operator_game.GameCategoryService",
	HandlerType: (*GameCategoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGameCategoryList",
			Handler:    _GameCategoryService_GetGameCategoryList_Handler,
		},
		{
			MethodName: "GetGameCategory",
			Handler:    _GameCategoryService_GetGameCategory_Handler,
		},
		{
			MethodName: "UpdateGameCategory",
			Handler:    _GameCategoryService_UpdateGameCategory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "operator_game.proto",
}

const (
	GameProviderService_GetGameProviderList_FullMethodName = "/operator_game.GameProviderService/GetGameProviderList"
	GameProviderService_GetGameProvider_FullMethodName     = "/operator_game.GameProviderService/GetGameProvider"
	GameProviderService_UpdateGameProvider_FullMethodName  = "/operator_game.GameProviderService/UpdateGameProvider"
)

// GameProviderServiceClient is the client API for GameProviderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GameProviderService - 游戏供应商服务
type GameProviderServiceClient interface {
	// 获取游戏供应商列表
	GetGameProviderList(ctx context.Context, in *GetGameProviderListRequest, opts ...grpc.CallOption) (*GetGameProviderListResp, error)
	// 获取单个游戏供应商
	GetGameProvider(ctx context.Context, in *GetGameProviderRequest, opts ...grpc.CallOption) (*GetGameProviderResp, error)
	// 更新游戏供应商
	UpdateGameProvider(ctx context.Context, in *UpdateGameProviderRequest, opts ...grpc.CallOption) (*UpdateGameProviderResp, error)
}

type gameProviderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGameProviderServiceClient(cc grpc.ClientConnInterface) GameProviderServiceClient {
	return &gameProviderServiceClient{cc}
}

func (c *gameProviderServiceClient) GetGameProviderList(ctx context.Context, in *GetGameProviderListRequest, opts ...grpc.CallOption) (*GetGameProviderListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGameProviderListResp)
	err := c.cc.Invoke(ctx, GameProviderService_GetGameProviderList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameProviderServiceClient) GetGameProvider(ctx context.Context, in *GetGameProviderRequest, opts ...grpc.CallOption) (*GetGameProviderResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGameProviderResp)
	err := c.cc.Invoke(ctx, GameProviderService_GetGameProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameProviderServiceClient) UpdateGameProvider(ctx context.Context, in *UpdateGameProviderRequest, opts ...grpc.CallOption) (*UpdateGameProviderResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateGameProviderResp)
	err := c.cc.Invoke(ctx, GameProviderService_UpdateGameProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameProviderServiceServer is the server API for GameProviderService service.
// All implementations must embed UnimplementedGameProviderServiceServer
// for forward compatibility.
//
// GameProviderService - 游戏供应商服务
type GameProviderServiceServer interface {
	// 获取游戏供应商列表
	GetGameProviderList(context.Context, *GetGameProviderListRequest) (*GetGameProviderListResp, error)
	// 获取单个游戏供应商
	GetGameProvider(context.Context, *GetGameProviderRequest) (*GetGameProviderResp, error)
	// 更新游戏供应商
	UpdateGameProvider(context.Context, *UpdateGameProviderRequest) (*UpdateGameProviderResp, error)
	mustEmbedUnimplementedGameProviderServiceServer()
}

// UnimplementedGameProviderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameProviderServiceServer struct{}

func (UnimplementedGameProviderServiceServer) GetGameProviderList(context.Context, *GetGameProviderListRequest) (*GetGameProviderListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGameProviderList not implemented")
}
func (UnimplementedGameProviderServiceServer) GetGameProvider(context.Context, *GetGameProviderRequest) (*GetGameProviderResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGameProvider not implemented")
}
func (UnimplementedGameProviderServiceServer) UpdateGameProvider(context.Context, *UpdateGameProviderRequest) (*UpdateGameProviderResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateGameProvider not implemented")
}
func (UnimplementedGameProviderServiceServer) mustEmbedUnimplementedGameProviderServiceServer() {}
func (UnimplementedGameProviderServiceServer) testEmbeddedByValue()                             {}

// UnsafeGameProviderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameProviderServiceServer will
// result in compilation errors.
type UnsafeGameProviderServiceServer interface {
	mustEmbedUnimplementedGameProviderServiceServer()
}

func RegisterGameProviderServiceServer(s grpc.ServiceRegistrar, srv GameProviderServiceServer) {
	// If the following call panics, it indicates UnimplementedGameProviderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GameProviderService_ServiceDesc, srv)
}

func _GameProviderService_GetGameProviderList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameProviderListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameProviderServiceServer).GetGameProviderList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameProviderService_GetGameProviderList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameProviderServiceServer).GetGameProviderList(ctx, req.(*GetGameProviderListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameProviderService_GetGameProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameProviderServiceServer).GetGameProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameProviderService_GetGameProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameProviderServiceServer).GetGameProvider(ctx, req.(*GetGameProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameProviderService_UpdateGameProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGameProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameProviderServiceServer).UpdateGameProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameProviderService_UpdateGameProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameProviderServiceServer).UpdateGameProvider(ctx, req.(*UpdateGameProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GameProviderService_ServiceDesc is the grpc.ServiceDesc for GameProviderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameProviderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "operator_game.GameProviderService",
	HandlerType: (*GameProviderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGameProviderList",
			Handler:    _GameProviderService_GetGameProviderList_Handler,
		},
		{
			MethodName: "GetGameProvider",
			Handler:    _GameProviderService_GetGameProvider_Handler,
		},
		{
			MethodName: "UpdateGameProvider",
			Handler:    _GameProviderService_UpdateGameProvider_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "operator_game.proto",
}

const (
	GameChannelService_GetGameChannel_FullMethodName     = "/operator_game.GameChannelService/GetGameChannel"
	GameChannelService_GetGameChannelList_FullMethodName = "/operator_game.GameChannelService/GetGameChannelList"
	GameChannelService_UpdateGameChannel_FullMethodName  = "/operator_game.GameChannelService/UpdateGameChannel"
)

// GameChannelServiceClient is the client API for GameChannelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GameChannelService - 游戏渠道服务
type GameChannelServiceClient interface {
	// 获取单个游戏渠道
	GetGameChannel(ctx context.Context, in *GetGameChannelRequest, opts ...grpc.CallOption) (*GetGameChannelResp, error)
	// 获取游戏渠道列表
	GetGameChannelList(ctx context.Context, in *GetGameChannelListRequest, opts ...grpc.CallOption) (*GetGameChannelListResp, error)
	// 更新游戏渠道
	UpdateGameChannel(ctx context.Context, in *UpdateGameChannelRequest, opts ...grpc.CallOption) (*UpdateGameChannelResp, error)
}

type gameChannelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGameChannelServiceClient(cc grpc.ClientConnInterface) GameChannelServiceClient {
	return &gameChannelServiceClient{cc}
}

func (c *gameChannelServiceClient) GetGameChannel(ctx context.Context, in *GetGameChannelRequest, opts ...grpc.CallOption) (*GetGameChannelResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGameChannelResp)
	err := c.cc.Invoke(ctx, GameChannelService_GetGameChannel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameChannelServiceClient) GetGameChannelList(ctx context.Context, in *GetGameChannelListRequest, opts ...grpc.CallOption) (*GetGameChannelListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGameChannelListResp)
	err := c.cc.Invoke(ctx, GameChannelService_GetGameChannelList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameChannelServiceClient) UpdateGameChannel(ctx context.Context, in *UpdateGameChannelRequest, opts ...grpc.CallOption) (*UpdateGameChannelResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateGameChannelResp)
	err := c.cc.Invoke(ctx, GameChannelService_UpdateGameChannel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameChannelServiceServer is the server API for GameChannelService service.
// All implementations must embed UnimplementedGameChannelServiceServer
// for forward compatibility.
//
// GameChannelService - 游戏渠道服务
type GameChannelServiceServer interface {
	// 获取单个游戏渠道
	GetGameChannel(context.Context, *GetGameChannelRequest) (*GetGameChannelResp, error)
	// 获取游戏渠道列表
	GetGameChannelList(context.Context, *GetGameChannelListRequest) (*GetGameChannelListResp, error)
	// 更新游戏渠道
	UpdateGameChannel(context.Context, *UpdateGameChannelRequest) (*UpdateGameChannelResp, error)
	mustEmbedUnimplementedGameChannelServiceServer()
}

// UnimplementedGameChannelServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameChannelServiceServer struct{}

func (UnimplementedGameChannelServiceServer) GetGameChannel(context.Context, *GetGameChannelRequest) (*GetGameChannelResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGameChannel not implemented")
}
func (UnimplementedGameChannelServiceServer) GetGameChannelList(context.Context, *GetGameChannelListRequest) (*GetGameChannelListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGameChannelList not implemented")
}
func (UnimplementedGameChannelServiceServer) UpdateGameChannel(context.Context, *UpdateGameChannelRequest) (*UpdateGameChannelResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateGameChannel not implemented")
}
func (UnimplementedGameChannelServiceServer) mustEmbedUnimplementedGameChannelServiceServer() {}
func (UnimplementedGameChannelServiceServer) testEmbeddedByValue()                            {}

// UnsafeGameChannelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameChannelServiceServer will
// result in compilation errors.
type UnsafeGameChannelServiceServer interface {
	mustEmbedUnimplementedGameChannelServiceServer()
}

func RegisterGameChannelServiceServer(s grpc.ServiceRegistrar, srv GameChannelServiceServer) {
	// If the following call panics, it indicates UnimplementedGameChannelServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GameChannelService_ServiceDesc, srv)
}

func _GameChannelService_GetGameChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameChannelServiceServer).GetGameChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameChannelService_GetGameChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameChannelServiceServer).GetGameChannel(ctx, req.(*GetGameChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameChannelService_GetGameChannelList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameChannelListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameChannelServiceServer).GetGameChannelList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameChannelService_GetGameChannelList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameChannelServiceServer).GetGameChannelList(ctx, req.(*GetGameChannelListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameChannelService_UpdateGameChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGameChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameChannelServiceServer).UpdateGameChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameChannelService_UpdateGameChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameChannelServiceServer).UpdateGameChannel(ctx, req.(*UpdateGameChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GameChannelService_ServiceDesc is the grpc.ServiceDesc for GameChannelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameChannelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "operator_game.GameChannelService",
	HandlerType: (*GameChannelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGameChannel",
			Handler:    _GameChannelService_GetGameChannel_Handler,
		},
		{
			MethodName: "GetGameChannelList",
			Handler:    _GameChannelService_GetGameChannelList_Handler,
		},
		{
			MethodName: "UpdateGameChannel",
			Handler:    _GameChannelService_UpdateGameChannel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "operator_game.proto",
}

const (
	PublishDataService_SyncPublishedData_FullMethodName = "/operator_game.PublishDataService/SyncPublishedData"
)

// PublishDataServiceClient is the client API for PublishDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PublishDataService - 发布数据服务
type PublishDataServiceClient interface {
	// 同步已发布的游戏数据到分站
	SyncPublishedData(ctx context.Context, in *SyncPublishedDataRequest, opts ...grpc.CallOption) (*SyncPublishedDataResp, error)
}

type publishDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPublishDataServiceClient(cc grpc.ClientConnInterface) PublishDataServiceClient {
	return &publishDataServiceClient{cc}
}

func (c *publishDataServiceClient) SyncPublishedData(ctx context.Context, in *SyncPublishedDataRequest, opts ...grpc.CallOption) (*SyncPublishedDataResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncPublishedDataResp)
	err := c.cc.Invoke(ctx, PublishDataService_SyncPublishedData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PublishDataServiceServer is the server API for PublishDataService service.
// All implementations must embed UnimplementedPublishDataServiceServer
// for forward compatibility.
//
// PublishDataService - 发布数据服务
type PublishDataServiceServer interface {
	// 同步已发布的游戏数据到分站
	SyncPublishedData(context.Context, *SyncPublishedDataRequest) (*SyncPublishedDataResp, error)
	mustEmbedUnimplementedPublishDataServiceServer()
}

// UnimplementedPublishDataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPublishDataServiceServer struct{}

func (UnimplementedPublishDataServiceServer) SyncPublishedData(context.Context, *SyncPublishedDataRequest) (*SyncPublishedDataResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncPublishedData not implemented")
}
func (UnimplementedPublishDataServiceServer) mustEmbedUnimplementedPublishDataServiceServer() {}
func (UnimplementedPublishDataServiceServer) testEmbeddedByValue()                            {}

// UnsafePublishDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PublishDataServiceServer will
// result in compilation errors.
type UnsafePublishDataServiceServer interface {
	mustEmbedUnimplementedPublishDataServiceServer()
}

func RegisterPublishDataServiceServer(s grpc.ServiceRegistrar, srv PublishDataServiceServer) {
	// If the following call panics, it indicates UnimplementedPublishDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PublishDataService_ServiceDesc, srv)
}

func _PublishDataService_SyncPublishedData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncPublishedDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublishDataServiceServer).SyncPublishedData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublishDataService_SyncPublishedData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublishDataServiceServer).SyncPublishedData(ctx, req.(*SyncPublishedDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PublishDataService_ServiceDesc is the grpc.ServiceDesc for PublishDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PublishDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "operator_game.PublishDataService",
	HandlerType: (*PublishDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncPublishedData",
			Handler:    _PublishDataService_SyncPublishedData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "operator_game.proto",
}
