// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: operator_game.proto

package server

import (
	"context"

	"oa.98ent.com/p9/operator-game/rpc/internal/logic/gamechannelservice"
	"oa.98ent.com/p9/operator-game/rpc/internal/svc"
	"oa.98ent.com/p9/operator-game/rpc/pb/operator_game"
)

type GameChannelServiceServer struct {
	svcCtx *svc.ServiceContext
	operator_game.UnimplementedGameChannelServiceServer
}

func NewGameChannelServiceServer(svcCtx *svc.ServiceContext) *GameChannelServiceServer {
	return &GameChannelServiceServer{
		svcCtx: svcCtx,
	}
}

// 获取单个游戏渠道
func (s *GameChannelServiceServer) GetGameChannel(ctx context.Context, in *operator_game.GetGameChannelRequest) (*operator_game.GetGameChannelResp, error) {
	l := gamechannelservicelogic.NewGetGameChannelLogic(ctx, s.svcCtx)
	return l.GetGameChannel(in)
}

// 获取游戏渠道列表
func (s *GameChannelServiceServer) GetGameChannelList(ctx context.Context, in *operator_game.GetGameChannelListRequest) (*operator_game.GetGameChannelListResp, error) {
	l := gamechannelservicelogic.NewGetGameChannelListLogic(ctx, s.svcCtx)
	return l.GetGameChannelList(in)
}

// 更新游戏渠道
func (s *GameChannelServiceServer) UpdateGameChannel(ctx context.Context, in *operator_game.UpdateGameChannelRequest) (*operator_game.UpdateGameChannelResp, error) {
	l := gamechannelservicelogic.NewUpdateGameChannelLogic(ctx, s.svcCtx)
	return l.UpdateGameChannel(in)
}
