// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: operator_game.proto

package publishdataservice

import (
	"context"

	"oa.98ent.com/p9/operator-game/rpc/pb/operator_game"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	SyncPublishedDataRequest = operator_game.SyncPublishedDataRequest
	SyncPublishedDataResp    = operator_game.SyncPublishedDataResp

	PublishDataService interface {
		// 同步已发布的游戏数据到分站
		SyncPublishedData(ctx context.Context, in *SyncPublishedDataRequest, opts ...grpc.CallOption) (*SyncPublishedDataResp, error)
	}

	defaultPublishDataService struct {
		cli zrpc.Client
	}
)

func NewPublishDataService(cli zrpc.Client) PublishDataService {
	return &defaultPublishDataService{
		cli: cli,
	}
}

// 同步已发布的游戏数据到分站
func (m *defaultPublishDataService) SyncPublishedData(ctx context.Context, in *SyncPublishedDataRequest, opts ...grpc.CallOption) (*SyncPublishedDataResp, error) {
	client := operator_game.NewPublishDataServiceClient(m.cli.Conn())
	return client.SyncPublishedData(ctx, in, opts...)
}
